Repository alcionai/corso, pull requests merged in 2022-11, with the labels that each got.

#1408 Tag kopia snapshots for later lookups
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: enhancement, mergequeue

#1409 Actually enable Google Analytics for Corso docs
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: mergequeue

#1357 run the otel-daemon alongside load tests
  .github/workflows/load_test.yml
  src/Makefile
Labels: mergequeue, tests

#1422 Revert "⬆️ Bump @mdx-js/react from 1.6.22 to 2.1.5 in /docs (#1381)"
  docs/package-lock.json
  docs/package.json
Labels: mergequeue

#1413 Fix flipped description of Azure PS env variables
  docs/docs/quickstart.md
Labels: mergequeue

#1424 Clean up more in docs Makefile
  docs/Makefile
Labels: mergequeue

#1428 Add an FAQ to docs
  docs/.markdownlint.json
  docs/docs/support/faq.md
  docs/sidebars.js
Labels: mergequeue

#1417 Allow disabling TLS and TLS verification
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/repo/s3.go
  src/internal/common/slices.go
  src/internal/kopia/s3.go
  src/pkg/storage/s3.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage.go
Labels: mergequeue

#1423 Always validate building docs in CI for PRs
  .github/workflows/ci.yml
Labels: mergequeue

#1435 Always build cli-docs
  .github/workflows/ci.yml
Labels: mergequeue

#1431 Use same gtag as website
  docs/docusaurus.config.js
Labels: mergequeue

#1425 add path prefix/contains filters
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
  src/pkg/path/path.go
Labels: enhancement, mergequeue

#1356 Add qol generic selector Reduce func
  src/internal/operations/restore.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
Labels: enhancement, mergequeue

#1442 fix span reporting null check
  src/internal/diagnostics/diagnostics.go
Labels: bug, mergequeue

#1436 Store/Retrieve owner info for OneDrive files
  src/internal/connector/onedrive/item.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/testdata/details.go
Labels: mergequeue

#1441 Add a make clean step for the website
  website/Makefile
Labels: mergequeue

#1450 Add a sitemap to the docs site
  docs/docusaurus.config.js
Labels: mergequeue

#1445 Add FAQ to address if Corso works with consumer M365 subscriptions
  docs/docs/support/faq.md
Labels: mergequeue

#1444 GC SharePoint Collection Framework
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/datacategory_string.go
Labels: enhancement, mergequeue

#1407 replace golang purge script with powershell script
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci.yml
  .github/workflows/ci_test_cleanup.yml
  .github/workflows/load_test.yml
  docs/docs/developers/testing.md
  src/.golangci.yml
  src/cli/repo/s3.go
  src/internal/connector/graph_connector.go
  src/internal/tester/config.go
  src/internal/tester/users.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, tests

#1456 GC: Backup: Sharepoint: Mock Support
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
Labels: supportability

#1459 Add a blog to the Corso website
  website/src/assets/images/blog/office_desk.jpg
  website/src/assets/images/blog/work.jpg
  website/src/assets/images/people/nica.jpeg
  website/src/assets/scss/custom/pages/_hero.scss
  website/src/blog.html
  website/src/corso-announcement-free-backup-for-microsoft-365.html
  website/src/partials/footer/footer.html
  website/src/partials/navbar/nav-center.html
Labels: mergequeue

#1468 Open 'external' link in a new tab
  website/src/index.html
Labels: mergequeue

#1446 Add EndTime to Exchange events
  src/internal/common/time.go
  src/internal/connector/exchange/event.go
  src/internal/connector/exchange/event_test.go
  src/internal/connector/mockconnector/mock_data_event.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue

#1454 Sharepoint Feature: details.Sharepoint implementation
  src/internal/connector/sharepoint/listInfo.go
  src/internal/connector/sharepoint/listInfo_test.go
  src/pkg/backup/details/details.go
Labels: mergequeue

#1429 use path filters in folder selectors
  src/cli/backup/exchange_integration_test.go
  src/cli/restore/exchange_integration_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/service_functions_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
Labels: enhancement, mergequeue

#1443 applies folder matching behavior to cli input
  src/cli/utils/exchange.go
  src/cli/utils/exchange_test.go
  src/cli/utils/onedrive.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/utils.go
  src/cli/utils/utils_test.go
  src/internal/connector/exchange/service_functions_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/onedrive.go
Labels: enhancement, mergequeue

#1501 Add CORSO_SECONDARY_M365_TEST_USER_ID to integration test
  .github/workflows/ci.yml
Labels: mergequeue-priority

#1477 GC: Backup: Sharepoint: Collection Implementation
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/datacategory_string.go
Labels: mergequeue, backup

#1465 add sharepoint to path
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/listInfo.go
  src/internal/connector/sharepoint/listInfo_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
  src/pkg/path/service_category_test.go
  src/pkg/path/servicetype_string.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/service_string.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue

#1476 purge deletions and calendar logging
  .github/actions/purge-m365-user-data/action.yml
Labels: mergequeue

#1452 Add created and modified time to all
  .github/workflows/ci.yml
  src/internal/connector/exchange/contact.go
  src/internal/connector/exchange/contact_test.go
  src/internal/connector/exchange/event.go
  src/internal/connector/exchange/event_test.go
  src/internal/connector/exchange/message.go
  src/internal/connector/exchange/message_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: enhancement, mergequeue

#1469 CI for website
  .github/workflows/_filechange_checker.yml
  .github/workflows/website-ci.yml
  website/Makefile
Labels: workflows

#1491 Add size to all objects
  src/internal/connector/exchange/contact.go
  src/internal/connector/exchange/contact_test.go
  src/internal/connector/exchange/event.go
  src/internal/connector/exchange/event_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/message.go
  src/internal/connector/exchange/message_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/listInfo.go
  src/internal/connector/sharepoint/listInfo_test.go
  src/pkg/backup/details/details.go
Labels: enhancement

#1529 add failfast to ci test runs
  .github/workflows/ci.yml
Labels: mergequeue-priority, tests

#1523 Add container resolver tests back
  src/internal/connector/exchange/container_resolver_test.go
Labels: bug, mergequeue, tests

#1532 Reduce CI test times
  .github/workflows/ci.yml
  src/internal/connector/graph_connector_test.go
Labels: mergequeue-priority

#1358 Website publish action
  .github/workflows/website-publish.yml
  website/Makefile
Labels: mergequeue, workflows

#1534 Compile all tests in cache populate step
  .github/actions/go-setup-cache/action.yml
  .github/workflows/ci.yml
Labels: mergequeue-priority

#1518 GC. `EventCalendarResolver` Populate() refactor
  src/internal/connector/exchange/event_calendar_cache.go
Labels: mergequeue

#1524 Limit container resolver recursion depth
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
Labels: bug, mergequeue

#1521 remove unused purge code
  src/cmd/purge/purge.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_functions_test.go
Labels: mergequeue-priority, tests

#1537 Add docs landing page back
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/img/data.svg
  docs/static/img/savings.svg
  docs/static/img/security.svg
Labels: mergequeue

#1538 Add blogs back to docs page
  docs/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  docs/blog/authors.yml
  docs/docusaurus.config.js
Labels: mergequeue

#1485 Make `split` function `path` package public
  src/pkg/path/path.go
Labels: mergequeue

#1513 Consistent backup model types
  src/cli/utils/testdata/opts.go
  src/pkg/backup/backup.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_load_test.go
  src/pkg/store/backup.go
Labels: mergequeue

#1541 Correctly route docs pages
  docs/docs/developers/testing.md
  docs/docs/intro.md
  docs/docs/quickstart.md
  docs/docs/setup/concepts.md
  docs/docs/setup/configuration.md
  docs/docs/setup/repos.md
  docs/docs/support/faq.md
  docs/docusaurus.config.js
  docs/src/pages/index.js
Labels: mergequeue

#1539 Point the website to the docs blog
  website/src/partials/footer/footer.html
  website/src/partials/navbar/nav-center.html
Labels: mergequeue

#1507 connector data coll refactor
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/tester/integration_runners.go
Labels: blocked, mergequeue

#1508 Adds the foundation of sharepoint data coll
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/service_iterators.go
  src/internal/tester/config.go
  src/internal/tester/integration_runners.go
  src/internal/tester/resource_owners.go
Labels: enhancement, mergequeue

#1510 extract scope from qp
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/service.go
  src/internal/connector/sharepoint/service_iterators.go
  src/internal/tester/integration_runners.go
Labels: enhancement, mergequeue

#1548 Use prefix matching in GraphConnector tests
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
Labels: mergequeue, tests

#1540 adds tenant site lookup on new graph conn
  src/cmd/factory/factory.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/cache_container.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/exchange_vars.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_query.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/queries.go
  src/internal/connector/support/m365Transform.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/services/m365/m365.go
Labels: enhancement, mergequeue

#1545 Add progressbar for connecting to repo and add elapsed time to progressbars
  src/internal/observe/observe.go
  src/pkg/repository/repository.go
Labels: mergequeue

#1484 Use http client from msgraphcore
  src/internal/connector/onedrive/item.go
Labels: enhancement, mergequeue

#1173 OneDrive restore/backup test
  .github/workflows/ci.yml
  src/.golangci.yml
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
Labels: mergequeue, tests

#1561 Fixing Home Page Design
  docs/src/components/parts/Cookies.js
  docs/src/components/parts/FirstSection.js
  docs/src/components/parts/FourthSection.js
  docs/src/components/parts/SecondSection.js
  docs/src/components/parts/ThirdSection.js
  docs/src/css/custom.scss
  docs/tailwind.config.js
Labels: mergequeue

#1560 More website fixes for first push
  docs/Dockerfile
  docs/docusaurus.config.js
  docs/src/components/parts/FirstSection.js
  docs/src/components/parts/ThirdSection.js
  docs/static/img/why/chat.svg
  docs/static/img/why/data.svg
  docs/static/img/why/savings.svg
  docs/static/img/why/security.svg
Labels: mergequeue

#1562 Moar website fixes
  docs/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  docs/docusaurus.config.js
  docs/src/components/parts/FirstSection.js
  docs/src/components/parts/FourthSection.js
  docs/src/components/parts/ThirdSection.js
  docs/src/pages/index.js
Labels: mergequeue

#1564 Accordions fixed for the dropdown
  docs/src/css/custom.scss
  docs/static/assets/download.svg
  docs/static/assets/download_blue.svg
Labels: mergequeue

#1565 Add missing docs for TLS config
  docs/docs/setup/repos.md
Labels: mergequeue

#1563 More website tweaks
  docs/docusaurus.config.js
  docs/src/components/parts/FirstSection.js
  docs/static/robots.txt
Labels: mergequeue

#1503 Print version info to stdout instead of stderr
  src/cli/cli.go
  src/cli/print/print.go
Labels: mergequeue

#1573 Tell Tailwind to use the Docusorus dark-mode attribute
  docs/tailwind.config.js
Labels: mergequeue

#1574 Add `make serve` to serve static build.
  docs/Makefile
  docs/README.md
Labels: mergequeue

#1575 add sharepoint to testVerifyBackupinputs
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
Labels: bug, enhancement

#1555 migrate sharepoint cat from file to library
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/pkg/path/categorytype_string.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
  src/pkg/path/service_category_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue

#1577 add sharepoint backup to the cli
  src/cli/backup/backup.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/utils/utils.go
Labels: enhancement, mergequeue

#1578 observe always hides when told
  src/internal/observe/observe.go
Labels: bug, mergequeue

#1587 Fix some font issues in the docs landing page
  docs/src/components/parts/ThirdSection.js
Labels: mergequeue

#1576 Remove empty page
  docs/docs/developers/architecture.md
Labels: mergequeue

#1582 add flag to retain all progress bars
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
Labels: mergequeue, cli

#1554 filter out personal sites
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/queries.go
Labels: enhancement, mergequeue

#1572 Rename home page sections to reflect contents
  docs/src/components/parts/Demo.js
  docs/src/components/parts/Hero.js
  docs/src/components/parts/KeyLoveFAQ.js
  docs/src/components/parts/MainComp.js
Labels: mergequeue

#1589 errant fixes running sp backup cli
  src/internal/kopia/wrapper.go
  src/internal/observe/observe.go
  src/pkg/logger/logger.go
  src/pkg/selectors/selectors.go
Labels: mergequeue

#1593 Improve Rudderstack event logging
  src/internal/events/events.go
Labels: mergequeue

#1597 Fix README links to the website
  README.md
Labels: mergequeue, backup

#1598 Prep for docs versioning
  docs/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  docs/docs/setup/m365_access.md
  docs/docusaurus.config.js
  docs/src/pages/index.js
Labels: mergequeue

#1603 Enable trailing slashes for docs/website
  docs/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  docs/docs/developers/testing.md
  docs/docs/intro.md
  docs/docs/quickstart.md
  docs/docs/setup/concepts.md
  docs/docs/setup/configuration.md
  docs/docs/setup/m365_access.md
  docs/docs/setup/repos.md
  docs/docs/support/faq.md
  docs/docusaurus.config.js
Labels: mergequeue

#1599 retrieve all drives in each site
  src/internal/connector/data_collections_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/drive.go
  src/internal/observe/observe.go
Labels: mergequeue, backup

#1570 GC: Populate Refactor (Contacts)
  src/internal/connector/exchange/contact_folder_cache.go
Labels: mergequeue

#1504 fix: integration tests running on PRs from forks
  .github/workflows/ci.yml
  .github/workflows/ok-to-test.yml
Labels: mergequeue

#1610 Path: Category expanded to include SharePoint Lists
  src/pkg/path/categorytype_string.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: mergequeue

#1613 Add a thumbnail for the Corso demo video
  docs/src/components/parts/Demo.js
  docs/static/assets/images/corso_demo_thumbnail.png
Labels: mergequeue

#1627 Fix bad comparison due to timezone mismatch
  src/internal/connector/exchange/event_test.go
Labels: bug, mergequeue, tests

#1626 add a discrete clone method to scopes
  src/pkg/selectors/exchange.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
Labels: mergequeue

#1631 add Set func to logger package
  src/pkg/logger/logger.go
Labels: enhancement, mergequeue

#1600 add boilerplate integration tests for sharepoint
  src/cli/backup/sharepoint_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/operation.go
  src/internal/tester/resource_owners.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, tests

#1618 add sharepoint details command
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/pkg/backup/details/details.go
  src/pkg/selectors/testdata/details.go
Labels: mergequeue, backup

#1638 Prevent Test-Suite-Fork from running on main
  .github/workflows/ci.yml
Labels: mergequeue

#1643 Custom function to send get requests on delta queries
  src/internal/connector/exchange/delta_get.go
  src/internal/connector/exchange/query_options.go
Labels: mergequeue

#1634 Use latest golangci-lint version
  .github/workflows/ci.yml
  src/.golangci.yml
  src/Makefile
  src/internal/common/time_test.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/delta_get.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue

#1609 Split backups by (resource owner, service) at CLI layer
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/internal/connector/graph_connector.go
  src/pkg/services/m365/m365.go
Labels: enhancement, mergequeue
