Repository alcionai/corso, pull requests merged in 2022-12, with the labels that each got.

#1619 migrate tenant id out of event repoID
  src/internal/events/events.go
Labels: mergequeue

#1608 Speed up Exchange backup by parallelizing url fetch
  src/internal/connector/exchange/exchange_data_collection.go
Labels: mergequeue, perf

#1607 Parallelize OneDrive queries to get URL
  src/Makefile
  src/internal/connector/onedrive/collection.go
  src/internal/operations/backup.go
Labels: mergequeue, perf

#1650 GC: Restore: `exchange.Mail` Cache Resolver Change
  src/internal/connector/exchange/service_restore.go
Labels: bug

#1427 Find previous kopia snapshots for given set of tags
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: enhancement, mergequeue

#1655 purge onedrive folders on gh action
  .github/actions/purge-m365-user-data/action.yml
Labels: mergequeue

#1656 GC: Resolver: `exchange.Mail` versioning mail bug fix
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_functions.go
Labels: bug

#1658 Weaken test assertions so the test doesn't flake
  src/internal/kopia/snapshot_manager_test.go
Labels: bug, blocked, mergequeue-priority, tests

#1666 add shell to onedrive purge
  .github/actions/purge-m365-user-data/action.yml
Labels: bug, mergequeue

#1649 Add check using staticcheck
  .github/workflows/ci.yml
Labels: mergequeue

#1662 Fix OneDrive and Kopia Wrapper test flakes
  src/internal/connector/onedrive/drive.go
  src/internal/kopia/snapshot_manager_test.go
Labels: bug, mergequeue

#1620 Use delta endpoint to fetch exchange mail items
  src/internal/connector/exchange/delta_get.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
Labels: enhancement, mergequeue

#1659 add suffix and pathSuffix filters
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
Labels: enhancement, mergequeue

#1642 adds a flag for more readable console logs
  src/pkg/logger/logger.go
Labels: mergequeue

#1644 Contacts delta endpoint fetch
  src/internal/connector/exchange/delta_get.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1648 Show backup size for list commands
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
Labels: mergequeue

#1430 Use previous snapshots to allow kopia to find previous versions of files
  src/internal/kopia/conn.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/wrapper.go
Labels: enhancement, mergequeue

#1663 More consistent folder cleanup for OneDrive test
  src/internal/connector/onedrive/drive_test.go
Labels: mergequeue, tests

#1405 Set file mod time in KopiaWrapper
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/data/data_collection.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: enhancement, mergequeue

#1633 Backup: SharePoint: List content retrieval
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/list_test.go
Labels: mergequeue, backup

#1628 Manual iteration for calendar events
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1255 GC: Backup: Kiota Serialization Patch no longer required.
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/support/m365Transform.go
Labels: mergequeue, supportability

#1665 sharepoint webURL selector scopes
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue

#1676 Run docs dev without regenerating CLI docs
  website/Makefile
Labels: mergequeue

#1681 Fix CI step name
  .github/workflows/ci.yml
  .github/workflows/website-publish.yml
Labels: mergequeue

#1683 Fix website test publish from main
  .github/workflows/ci.yml
Labels: mergequeue

#1636 add sharepoint library restore
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: restore, mergequeue

#1689 add missing any/none target check for paths
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint_test.go
Labels: bug, mergequeue

#1686 Fix preview/card images for blog posts
  website/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  website/blog/2022-12-2-your-own-backups.md
  website/blog/images/corso_backup.png
  website/blog/images/gian_tweet_backups.png
  website/blog/images/office_desk.jpg
Labels: mergequeue

#1692 fixing loading for keylovefaq component
  website/src/components/parts/KeyLoveFAQ.js
  website/src/components/parts/MainComp.js
Labels: mergequeue

#1701 Update changelog for v0.0.3
  CHANGELOG.md
Labels: mergequeue

#1637 adds sharepoint restore cli commands
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/help/env.go
  src/cli/options/options.go
  src/cli/print/print.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cmd/factory/exchange.go
  src/cmd/factory/onedrive.go
  src/internal/observe/observe.go
  src/pkg/logger/logger.go
Labels: restore, mergequeue, cli

#1696 Return interface values instead of concrete type
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1711 fix date on blog post 2022-12-2-your-own-backups.md
  website/blog/2022-12-2-your-own-backups.md
Labels: mergequeue

#1690 OneDrive: TestOneDriveDriveSuite/TestCreateGetDeleteFolder Sub-Test ignored
  src/internal/connector/onedrive/drive_test.go
Labels: mergequeue, tests

#1717 Return delta tokens from fetch functions
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1718 Create path categories for metadata folders
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
  src/pkg/path/servicetype_string.go
Labels: mergequeue

#1606 Skip creating inline reference attachments
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/exchange_service_test.go
Labels: mergequeue

#1719 Create in-memory MetadataCollection type
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph/metadata_collection_test.go
Labels: mergequeue

#1710 Expand Stream and Collection interfaces for delta token-based incrementals
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/sharepoint/collection.go
  src/internal/data/data_collection.go
  src/internal/data/data_collection_test.go
  src/internal/kopia/data_collection.go
Labels: mergequeue

#1728 Disable kopia-assisted incrementals for OneDrive
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: bug, mergequeue

#1733 Support building Arm website Docker image
  website/Dockerfile
Labels: mergequeue

#1682 Fix staticcheck lint in CI
  .github/workflows/ci.yml
  src/cmd/getM365/getItem.go
  src/pkg/repository/repository_load_test.go
  src/staticcheck.conf
Labels: mergequeue

#1671 add a weburl to siteid reducer in gc
  src/cli/backup/sharepoint.go
  src/internal/connector/data_collections.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/pkg/services/m365/m365.go
Labels: mergequeue, backup

#1724 amend test user cleanup list
  .github/workflows/ci_test_cleanup.yml
  .github/workflows/load_test.yml
  src/internal/tester/resource_owners.go
Labels: mergequeue, tests

#1739 Use of NextLink
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
Labels: bug, tests

#1687 populate sharepoint itemInfo
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: enhancement, mergequeue

#1722 Persist Exchange delta tokens
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
Labels: mergequeue

#1731 Expand interfaces for components used during backup
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
Labels: mergequeue

#1730 Add note about email isRead marker with kopia-assisted incrementals
  website/docs/support/known_issues.md
Labels: documentation, mergequeue

#1729 minor refactor for cleanup in operations
  src/internal/operations/backup.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
Labels: mergequeue

#1479 GC: Go.Mod update
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/delta_get.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/exchange_vars.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/sharepoint/list.go
Labels: mergequeue, supportability

#1712 add weburl identification in the CLI
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/restore/sharepoint.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue, cli

#1741 export ownerCats and fetchPrevSnap
  src/internal/connector/exchange/service_iterators.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue

#1736 Refactor http client creation for onedrive file download
  src/internal/connector/graph/service_helper.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue

#1751 new blog post: "Setting up your own Microsoft 365 sandbox"
  website/blog/2022-12-09-m365-sandbox-setup.md
  website/blog/images/12-09-2022-a.png
  website/blog/images/12-09-2022-b.png
  website/blog/images/ar_sandbox.jpg
Labels: mergequeue

#1754 Enable vale for blog posts
  website/Makefile
  website/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
  website/blog/2022-12-09-m365-sandbox-setup.md
  website/blog/2022-12-2-your-own-backups.md
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#1758 add a truncate tag to the most recent blog post
  website/blog/2022-12-09-m365-sandbox-setup.md
Labels: mergequeue

#1759 Add a comment for updating Schema constants
  src/internal/model/model.go
Labels: mergequeue

#1742 aggregate categories from selector
  src/internal/connector/exchange/service_iterators.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
Labels: enhancement, mergequeue

#1750 export makeTagKV, fetchPrevSnapshotManifest
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue

#1764 Shuffle around some kopia snapshot code
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue

#1763 Rename events to adhere to the "Noun Action" naming convention
  src/internal/events/events.go
Labels: mergequeue

#1765 Track more info about collections during backup
  src/internal/kopia/upload.go
Labels: mergequeue

#1706 Validate release artifacts post release
  .github/actions/publish-website/action.yml
  .github/actions/website-linting/action.yml
  .github/workflows/ci.yml
  .github/workflows/website-publish.yml
Labels: mergequeue

#1769 Align logo and name to center in README
  README.md
Labels: mergequeue

#1753 Add Intel vs. Arm blog post
  website/blog/2022-12-12-benchmarking-intel-vs-arm-for-backup-applications.md
  website/blog/authors.yml
  website/blog/images/benchmarking/compression_relative.png
  website/blog/images/benchmarking/compression_througput.png
  website/blog/images/benchmarking/hash_relative.png
  website/blog/images/benchmarking/hash_througput.png
  website/blog/images/benchmarking/intel_vs_arm_heatmap.png
  website/blog/images/benchmarking/splitter_relative.png
  website/blog/images/benchmarking/splitter_througput.png
Labels: mergequeue

#1773 Fix heading align in README
  README.md
Labels: mergequeue

#1738 Don't retry unless timeout err
  src/internal/connector/onedrive/collection.go
Labels: mergequeue

#1782 GC: SharePoint: Helper function consolidation.
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/helper_test.go
Labels: mergequeue, supportability

#1744 retrieve manifests and metadata from kopia
  src/cli/repo/s3.go
  src/internal/connector/data_collections.go
  src/internal/connector/graph/service.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/streamstore.go
  src/internal/tester/integration_runners.go
Labels: enhancement, mergequeue, backup

#1590 add an examples test to selectors
  src/pkg/selectors/example_selectors_test.go
Labels: mergequeue

#1784 GC: Support Library Bump
  src/go.mod
  src/go.sum
Labels: mergequeue, supportability

#1787 rename graph.Service to Servicer
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_query.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/queries.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue

#1783 GC: BackUp: SharePoint Test Updates
  src/internal/connector/sharepoint/collection_test.go
Labels: mergequeue, supportability

#1768 consume old deltas on exchange mail backup
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/operations/backup.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, backup

#1794 Allow updating and returning non-default values
  src/internal/connector/mockconnector/mock_data_collection.go
Labels: mergequeue

#1632 Update to go1.19 for corso
  build/Dockerfile
  build/build.sh
  docker/Dockerfile
  src/cli/config/config_test.go
  src/go.mod
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/wrapper_test.go
  website/Makefile
Labels: mergequeue

#1789 Refactor service failfast
  src/cmd/getM365/getItem.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/service_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/operations/backup.go
Labels: mergequeue

#1749 add sharepoint output columns, fix flag bugs
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, mergequeue, cli

#1798 Speed up Windows Powershell download
  website/docs/setup/_download_binary.md
Labels: mergequeue

#1803 add sharepoint fullcontrol permission to docs
  website/docs/setup/m365_access.md
Labels: documentation, mergequeue

#1806 Add docs/rn question to the PR template
  .github/pull_request_template.md
Labels: mergequeue

#1790 move graphService to graph as Service
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/pkg/services/m365/m365.go
Labels: mergequeue

#1810 Force home page to dark mode while allowing choice for other pages
  website/docusaurus.config.js
  website/src/components/parts/Demo.js
  website/src/css/custom.scss
  website/src/pages/index.js
Labels: mergequeue

#1811 Say reasons why a base snapshot was selected
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
Labels: mergequeue

#1796 Helper function to load snapshot root directories
  src/internal/kopia/conn.go
Labels: mergequeue

#1797 Merge items in a single directory during snapshot
  src/internal/kopia/upload.go
Labels: mergequeue

#1816 Add a note describing Corso repository encryption
  website/docs/setup/repos.md
Labels: mergequeue

#1813 Add an `updated` flag to backup details
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/restore.go
  src/internal/kopia/upload.go
  src/internal/streamstore/streamstore_test.go
  src/pkg/backup/details/details.go
Labels: mergequeue

#1817 Clean up JS
  website/src/components/parts/CTA.js
  website/src/components/parts/FirstSection.js
  website/src/components/parts/MainComp.js
  website/src/components/parts/SecondSection.js
  website/src/components/parts/ThirdSection.js
Labels: mergequeue

#1819 Rackspace blog post
  website/blog/2022-12-16-not-your-backups-not-your-data.md
  website/blog/images/not_your_backups_not_your_data.png
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#1825 static aws creds for load test
  .github/workflows/load_test.yml
Labels: mergequeue-priority

#1827 Fix navbar transparency in light mode and some scss linter issues
  website/src/css/custom.scss
Labels: mergequeue

#1826 Serialize test runs
  .github/workflows/ci.yml
Labels: mergequeue-priority

#1830 correct backup tag key, metadata not found
  src/cli/backup/onedrive.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
Labels: bug, mergequeue

#1834 Website fixes
  src/cmd/mdgen/mdgen.go
  website/blog/2022-12-09-m365-sandbox-setup.md
  website/blog/2022-12-12-benchmarking-intel-vs-arm-for-backup-applications.md
  website/blog/2022-12-16-not-your-backups-not-your-data.md
  website/docs/developers/testing.md
  website/docs/quickstart.md
  website/docs/setup/m365-access.md
  website/docs/setup/repos.md
  website/docs/support/bugs-and-features.md
  website/docs/support/known-issues.md
  website/sidebars.js
  website/src/components/parts/CTA.js
  website/src/components/parts/Cookies.js
  website/src/components/parts/Demo.js
  website/src/components/parts/Hero.js
  website/src/components/parts/KeyLoveFAQ.js
  website/src/pages/cookies.md
Labels: mergequeue

#1835 temporarily skip e2e smoke tests
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/sharepoint_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
Labels: mergequeue-priority, tests

#1841 CI: Pick a M365 app from a pool
  .github/workflows/ci.yml
Labels: mergequeue

#1799 produce previousPaths metadata
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph/metadata_collection_test.go
  src/internal/connector/graph/service.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
Labels: enhancement, mergequeue, backup

#1802 consume prevPath on next backup
  src/internal/common/maps.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
Labels: enhancement, mergequeue, backup

#1845 Fix CLI auto-generated docs headers
  src/cmd/mdgen/mdgen.go
Labels: mergequeue

#1844 Add Algolia docsearch to Corso docs
  website/docusaurus.config.js
  website/src/css/custom.scss
Labels: mergequeue

#1801 Merge directory layout for kopia incremental backups
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
Labels: mergequeue

#1828 Select subtrees of data from base snapshots based on reason snapshot was picked
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/pkg/path/path.go
Labels: mergequeue

#1814 deduplicate cache folders
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/cache_container.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/service.go
Labels: mergequeue

#1849 Do not return an error if folder was deleted
  src/internal/connector/exchange/service_iterators.go
Labels: bug, mergequeue-priority

#1836 Select specific metadata from base snapshot by Reasons base snapshot was picked
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue

#1851 Update FolderEntry for size and modified time
  src/pkg/backup/details/details.go
Labels: mergequeue

#1848 Use leaf test instance for assertions
  src/internal/connector/exchange/exchange_service_test.go
Labels: bug, mergequeue, tests

#1831 Reuse base snapshots
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue

#1857 typo secrete -> secrets
  .github/workflows/load_test.yml
Labels: bug, mergequeue, tests

#1863 add testfolder to ci cleanup set
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue-priority, tests

#1862 Tweak preview image for owning ID blog post
  website/blog/2022-12-2-your-own-backups.md
  website/blog/images/you_are_your_own_brand.jpeg
Labels: mergequeue-priority, mergequeue

#1815 produce coll state and item deletion
  src/internal/common/maps.go
  src/internal/common/slices.go
  src/internal/common/strings.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/consts.go
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/sharepoint/collection.go
Labels: mergequeue, backup

#1833 Have BackupOp pass subtree paths to BackupCollections
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue

#1861 GC: MSGRAPH Linked Library Upgrades
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/sharepoint/list.go
Labels: mergequeue, supportability

#1867 Fetch isRead attribute in email delta queries
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1869 require complete previous data for increment
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue, backup

#1842 Speedup OneDrive backup by pulling urls in delta API
  CHANGELOG.md
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue

#1860 log non-2xx graph api calls
  .github/workflows/ci.yml
  .github/workflows/load_test.yml
  src/internal/connector/graph/service_helper.go
  src/pkg/logger/logger.go
Labels: mergequeue

#1871 Add GitHub form for bug reports
  .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
  .github/ISSUE_TEMPLATE/config.yml
Labels: mergequeue

#1875 Fix typo in bug report template
  .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Labels: mergequeue

#1876 Add info on getting logs to docs and the issue template
  .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
  website/docs/support/bugs-and-features.md
Labels: mergequeue

#1879 Create a security policy
  SECURITY.md
Labels: mergequeue

#1788 GC: Backup: SharePoint List Integration with Tests
  src/internal/connector/data_collections_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/list_test.go
  src/internal/connector/sharepoint/service_iterators.go
  src/internal/operations/backup_test.go
Labels: enhancement, mergequeue

#1870 debug logs only if testing with -v
  src/internal/tester/cli.go
Labels: mergequeue

#1818 move exchange data collections to exchange
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/support/status.go
Labels: mergequeue

#1885 remove common maps, add golang maps
  src/go.mod
  src/go.sum
  src/internal/common/configs.go
  src/internal/common/maps.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/kopia/model_store.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/wrapper_test.go
  src/internal/tester/config.go
  src/internal/tester/envvars.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
Labels: mergequeue

#1887 require resource owner set on selector create
  src/cli/backup/exchange.go
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_integration_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_integration_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange_test.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint_test.go
  src/cmd/factory/exchange.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/repository_load_test.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue

#1900 GC: Sharepoint selector added to the helper set.
  src/internal/connector/graph_connector_helper_test.go
Labels: mergequeue, tests

#1881 Update folder size and modified time in details
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/streamstore/streamstore_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue

#1903 enable incrementals with feature flags
  src/cli/backup/exchange.go
  src/cli/options/options.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/operations/backup.go
  src/pkg/control/options.go
Labels: enhancement, mergequeue, cli

#1880 Move OneDrive path helper func to path package
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/pkg/path/onedrive.go
  src/pkg/path/onedrive_test.go
Labels: mergequeue

#1883 Allow updating portions of ItemInfo for some types
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue

#1910 populate sharepoint selectors with scopes
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
Labels: bug, mergequeue

#1913 Address review feedback from #1896
  CHANGELOG.md
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue

#1886 do not return errs from tester setup funcs
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/sharepoint_integration_test.go
  src/cli/repo/s3_integration_test.go
  src/cli/restore/exchange_integration_test.go
  src/internal/tester/config.go
  src/internal/tester/loader.go
Labels: mergequeue, tests

#1902 Adding missing docs for deleting OD/EX
  website/sidebars.js
Labels: mergequeue

#1909 Stricter checking for how hierarchies are merged
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
Labels: mergequeue, tests, supportability

#1894 Factor out function to retrieve backup details
  src/internal/operations/common.go
  src/internal/operations/restore.go
Labels: mergequeue

#1882 handle invalid or expired deltas
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/onedrive/collection.go
Labels: mergequeue, backup

#1919 add doNotMerge func to collections
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/sharepoint/collection.go
  src/internal/data/data_collection.go
  src/internal/data/data_collection_test.go
  src/internal/kopia/data_collection.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup

#1892 Produce map of items that need backup details entries
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/streamstore.go
Labels: enhancement, mergequeue

#1921 set nomerge on delta reset
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue, backup

#1925 Lift'n'shift of existing code
  src/internal/kopia/upload.go
  src/pkg/backup/details/details.go
Labels: mergequeue

#1917 track tombstones by id, not path
  src/internal/connector/exchange/service_iterators.go
Labels: bug, mergequeue

#1924 reset container if deleted in flight, not delete
  src/internal/connector/exchange/service_iterators.go
Labels: mergequeue

#1904 Functions to merge a set of backup details
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/common.go
  src/internal/operations/restore.go
Labels: mergequeue

#1922 Handle DoNotMergeItems in hierarchy merge
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
Labels: bug, mergequeue
