Repository alcionai/corso, pull requests merged in 2022-10, with the labels that each got.

#1320 Add go report card badge
  README.md
Labels: mergequeue

#1321 Add Twitter preview card
  website/src/assets/images/cloudbackup.png
  website/src/partials/title-meta.html
Labels: mergequeue

#1313 Gc mock package
  src/cmd/getM365/getItem.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/service_helper.go
Labels: mergequeue

#1332 run restore on load test
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, tests

#1333 minro cleanup on duplicated load test code
  src/pkg/repository/repository_load_test.go
Labels: mergequeue

#1336 Add GetID() to model.BaseModel
  src/internal/model/model.go
  src/internal/model/model_test.go
Labels: mergequeue

#1335 export repoExists error from repository
  src/cli/repo/s3.go
  src/cli/repo/s3_integration_test.go
  src/pkg/repository/repository.go
Labels: enhancement, mergequeue

#1344 add scope category to path cat type func
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/graph_connector.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
Labels: enhancement, mergequeue

#1339 add rolling data production to load test
  .github/workflows/load_test.yml
  src/internal/tester/config.go
  src/internal/tester/users.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, tests

#1330 Add Twitter card for docs
  docs/docusaurus.config.js
  docs/static/img/cloudbackup.png
  website/src/partials/title-meta.html
Labels: mergequeue

#1337 Do not add README to the released archives
  src/.goreleaser.yaml
Labels: mergequeue

#1325 hand corso logger to rudderstack
  src/internal/events/events.go
  src/internal/events/events_test.go
  src/pkg/logger/logger.go
  src/pkg/repository/repository.go
Labels: mergequeue

#1111 Add AWS X-Ray support
  src/Makefile
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/restore.go
  src/internal/diagnostics/diagnostics.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/repository/repository_load_test.go
  src/pkg/selectors/scopes.go
  src/testfiles/otel_daemon/Dockerfile
Labels: mergequeue, tests

#1345 GC: Restore: MockEvent w/ Attachment
  src/cmd/factory/exchange.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/mockconnector/mock_data_event.go
Labels: mergequeue, tests

#1354 Fix minor website issues
  website/src/index.html
Labels: mergequeue

#1338 flush logs on cmd failure
  src/cmd/factory/factory.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
Labels: bug, mergequeue

#1350 Fix v prefix in binaries created by goreleaser
  src/.goreleaser.yaml
Labels: mergequeue

#1351 Push docs to root instead of /preview
  .github/workflows/ci.yml
Labels: mergequeue

#1340 revert DPanic log to Error in support pkg
  src/internal/connector/support/status.go
  src/internal/connector/support/status_test.go
Labels: mergequeue, tests

#1367 Remove Corso docs landing page
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/img/data.svg
  docs/static/img/savings.svg
  docs/static/img/security.svg
Labels: mergequeue

#1323 Fix version string for binaries inside docker images
  .github/workflows/ci.yml
Labels: mergequeue

#1368 Fix build.sh usage function
  build/build.sh
Labels: mergequeue

#1363 GC: Container Resolver tests consolidation
  src/internal/connector/exchange/contact_folder_cache_test.go
  src/internal/connector/exchange/folder_resolver_test.go
Labels: mergequeue, tests

#1364 replace golang purge script with powershell script
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  .gitignore
  src/cmd/purge/scripts/foldersAndItems.ps1
Labels: enhancement, mergequeue
