Repository alcionai/corso, pull requests merged in 2023-07, with the labels that each got.

#3677 remove discovery pkg
  CHANGELOG.md
  src/internal/m365/backup.go
  src/internal/m365/discovery/discovery.go
  src/internal/m365/discovery/discovery_test.go
  src/internal/m365/graph/errors.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, tech-debt, msgraph

#3737 Fix sanity concurrency middleware
  src/cmd/sanity_test/sanity_tests.go
Labels: bug, mergequeue, tests

#3736 bump clues to e24d794
  src/go.mod
  src/go.sum
Labels: mergequeue

#3701 Add custom github template to print duration
  src/.gotestfmt/github/package.gotpl
Labels: mergequeue, workflows, supportability

#3744 add authErr to users mailbox check
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: bug, mergequeue-priority, exchange, msgraph

#3729 Add Corso extensions package
  src/pkg/backup/details/details.go
  src/pkg/extensions/extensions.go
  src/pkg/extensions/extensions_test.go
  src/pkg/extensions/mock_extensions.go
Labels: enhancement, mergequeue, onedrive

#3747 remove goreleaser replacements property
  .github/actions/publish-binary/action.yml
  .github/workflows/binary-publish.yml
  .github/workflows/ci.yml
  src/.goreleaser.yaml
Labels: bug, ci

#3749 Add concurrency init to api
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/m365.go
Labels: supportability, sdk

#3742 update deprecated flag
  .github/actions/publish-binary/action.yml
Labels: mergequeue

#3688 handle file-folder collision cases
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/sharepoint/library_handler.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
Labels: restore, mergequeue, onedrive, sharepoint

#3740 Longevity test
  .github/workflows/longetivity_test.yml
Labels: mergequeue, tests, github_actions

#3739 Fix nightly test
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
Labels: mergequeue

#3727 Test cases for fetching configs from config file and flags
  src/cli/config/config_test.go
Labels: mergequeue

#3643 Onedrive restore- handle unknown path error
  src/go.sum
  src/internal/kopia/data_collection.go
  src/internal/kopia/wrapper.go
  src/internal/operations/restore.go
Labels: mergequeue

#3753 ignore provider check in init repo
  src/cli/config/account.go
Labels: mergequeue

#3732 Refactor populateItems
  src/internal/m365/onedrive/collection.go
Labels: mergequeue, tech-debt

#3754 aggregate backup operation test dependencies
  src/internal/operations/backup.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: tests

#3703 ensure od and exchange can restore in-place
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/handlers.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/exchange/restore_test.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: enhancement, restore, mergequeue

#3706 distribute operations integration tests
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/help_test.go
  src/internal/operations/operation.go
  src/internal/operations/opstatus_string.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: mergequeue, tests

#3730 use counter to display restore items skipped
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint.go
  src/cli/utils/restore_config.go
  src/cli/utils/restore_config_test.go
  src/internal/operations/restore.go
Labels: enhancement, restore, cli

#3713 fix restore to dest with leading slash
  src/cli/print/print.go
  src/pkg/control/options.go
  src/pkg/control/restore.go
  src/pkg/control/restore_test.go
Labels: bug, restore, mergequeue, cli

#3722 add counter for skip-collision counting
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint.go
  src/cli/utils/restore_config.go
  src/cli/utils/restore_config_test.go
  src/cli/utils/utils.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/factory/impl/sharepoint.go
  src/go.mod
  src/go.sum
  src/internal/kopia/conn.go
  src/internal/kopia/model_store.go
  src/internal/kopia/upload.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/handlers.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/exchange/restore_test.go
  src/internal/m365/graph/errors_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/inject/inject.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/internal/operations/test/helper_test.go
  src/pkg/count/count.go
  src/pkg/count/count_test.go
  src/pkg/count/keys.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager_test.go
Labels: restore, mergequeue

#3734 move default folder consts to api
  src/cli/backup/exchange_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/backup.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/exchange/consts.go
  src/internal/m365/exchange/contacts_backup.go
  src/internal/m365/exchange/container_resolver_test.go
  src/internal/m365/exchange/events_backup.go
  src/internal/m365/exchange/events_container_cache.go
  src/internal/m365/exchange/mail_backup.go
  src/internal/m365/exchange/mail_container_cache.go
  src/internal/m365/exchange/mail_container_cache_test.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/pkg/services/m365/api/consts.go
  src/pkg/services/m365/api/mail_pager_test.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
Labels: mergequeue, tech-debt, msgraph

#3756 final few changes from manual testing
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
Labels: bug, restore, cli

#3735 tweaks and fixes found while testing
  src/cli/restore/restore.go
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/container_resolver_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/handlers.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/graph/middleware.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/operations/restore.go
  src/pkg/backup/details/details.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events.go
Labels: bug, restore, mergequeue

#3750 Integrate extensions into drive item reader
  src/internal/kopia/upload.go
  src/internal/m365/onedrive/collection.go
  src/internal/m365/onedrive/collection_test.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/sharepoint/library_handler.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/backup/details/details.go
  src/pkg/extensions/extensions.go
  src/pkg/extensions/extensions_test.go
  src/pkg/extensions/mock_extensions.go
Labels: mergequeue, onedrive, sharepoint

#3757 remove getting s3 config from envvars
  src/cli/repo/s3.go
  src/pkg/storage/storage.go
Labels: mergequeue

#3775 Remove event instance backup issue from known issues
  website/docs/support/known-issues.md
Labels: mergequeue

#3781 Skip failing SharePoint pages tests
  src/internal/m365/sharepoint/api/pages_test.go
Labels: mergequeue, tests, sharepoint

#3752 Longetivity test
  .github/workflows/longetivity_test.yml
  .github/workflows/longevity_test.yml
  .github/workflows/weekly_cleanup.yml
Labels: mergequeue

#3778 Fixups for comparing details to expected set
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/onedrive_test.go
  src/pkg/backup/details/testdata/in_deets.go
Labels: bug, mergequeue, backup, tests

#3779 Add tests that boomerang items
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/onedrive_test.go
  src/pkg/services/m365/api/mail.go
Labels: mergequeue, backup, tests, exchange

#3784 Return original read closer if no extension factories are supplied
  src/internal/m365/onedrive/collection.go
  src/internal/m365/onedrive/collection_test.go
  src/pkg/extensions/extensions.go
  src/pkg/extensions/extensions_test.go
Labels: mergequeue, tech-debt

#3764 avoid provider check in init
  src/cli/backup/exchange_e2e_test.go
  src/cli/config/storage.go
  src/cli/repo/s3_e2e_test.go
  src/pkg/storage/testdata/storage.go
Labels: mergequeue

#3791 Add linter for struct tags
  .github/workflows/ci.yml
Labels: mergequeue, workflows, supportability

#3788 add counting for replace and new items
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/onedrive/restore.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/restore_helper_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/count/keys.go
Labels: restore, tests

#3789 share code between od and sp
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: tests, tech-debt

#3804 Fix details comparison
  src/pkg/backup/details/testdata/in_deets.go
Labels: bug, backup, tests

#3801 specify sharepoint restore libraries
  src/internal/m365/helper_test.go
  src/internal/operations/restore_test.go
  src/internal/tester/tconfig/consts.go
  src/pkg/backup/details/testdata/in_deets.go
  src/pkg/selectors/testdata/sharepoint.go
Labels: mergequeue-priority, tests, sharepoint

#3800 Upgrade to golangci-lint 1.53.3
  .github/workflows/ci.yml
  src/Makefile
Labels: mergequeue, dependencies, ci

#3810 add mask-data to but ticket log desc
  .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
Labels: mergequeue, ci

#3802 retry on http/2 stream errors
  CHANGELOG.md
  src/cmd/getM365/onedrive/get_item.go
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/onedrive/collection.go
  src/pkg/fault/fault.go
  src/pkg/selectors/selectors.go
Labels: bug, mergequeue, msgraph

#3812 add test for 503 resp body
  src/internal/m365/graph/errors_test.go
  src/internal/m365/graph/middleware.go
  src/internal/m365/graph/middleware_test.go
  src/internal/m365/graph/service.go
  src/pkg/services/m365/api/helper_test.go
Labels: mergequeue, tests, msgraph

#3783 add operations test for adv rest
  src/internal/kopia/conn.go
  src/internal/kopia/model_store.go
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/graph/middleware_test.go
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/sharepoint/library_handler.go
  src/internal/operations/backup.go
  src/internal/operations/common.go
  src/internal/operations/maintenance.go
  src/internal/operations/operation.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/restore_helper_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/count/keys.go
  src/pkg/repository/repository.go
  src/pkg/selectors/testdata/onedrive.go
  src/pkg/selectors/testdata/sharepoint.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mail_pager_test.go
  src/pkg/services/m365/m365_test.go
Labels: restore, mergequeue, tests

#3769 public cli and docs for intial advanced restore
  CHANGELOG.md
  src/cli/flags/restore_config.go
  src/cli/restore/restore.go
  website/docs/quickstart.md
  website/docs/setup/restore-options.md
  website/docs/support/known-issues.md
Labels: mergequeue, cli

#3790 Longevity test- delete backup after n days
  .github/workflows/longevity_test.yml
  src/cmd/longevity_test/longevity.go
Labels: mergequeue

#3796 config info in doc
  website/docs/setup/configuration.md
  website/docs/setup/m365-access.md
  website/docs/setup/repos.md
Labels: mergequeue

#3828 Add Restore options to side navbar
  website/sidebars.js
Labels: bug, documentation, mergequeue

#3831 Allow setting repo user and hostname
  src/cli/config/config.go
  src/cli/flags/maintenance.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/utils/options.go
  src/cli/utils/utils.go
Labels: mergequeue, cli, maintenance

#3830 First pass at documentation for maintenance
  src/cli/flags/maintenance.go
  src/cli/repo/repo.go
  website/docs/setup/maintenance.md
  website/sidebars.js
  website/styles/Vocab/Base/accept.txt
Labels: documentation, mergequeue, maintenance

#3833 Update CHANGELOG.md for v0.11.0 release
  CHANGELOG.md
Labels: mergequeue

#3839 Trivial: Fix title capitalization for consistency
  website/docs/setup/restore-options.md
Labels: mergequeue

#3795 create missing drives on restore
  CHANGELOG.md
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/sharepoint/restore.go
  src/pkg/control/restore.go
  src/pkg/services/m365/api/lists_test.go
  website/docs/support/known-issues.md
Labels: bug, restore, sharepoint

#3840 Persist repo owner info in config
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/restore.go
  src/cli/utils/utils.go
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, cli, maintenance

#3842 feed backup drive names into restore
  src/internal/common/idname/idname.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
Labels: restore, onedrive, sharepoint

#3792 Kopia wrapper code to set retention parameters
  .github/workflows/ci.yml
  src/go.mod
  src/go.sum
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/tester/suite.go
  src/internal/tester/suite_test.go
  src/pkg/control/repository/repo.go
  src/pkg/control/repository/retentionmode_string.go
Labels: mergequeue, kopia

#3860 Only match with viper config if it was read
  CHANGELOG.md
  src/cli/config/account.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
Labels: mergequeue

#3863 Update CHANGELOG for 0.11.1
  CHANGELOG.md
Labels: mergequeue

#3793 add api funcs for creating documentLibs
  CHANGELOG.md
  src/internal/common/idname/idname.go
  src/internal/data/mock/collection.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/library_handler.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/pkg/control/restore.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
  website/docs/support/known-issues.md
Labels: enhancement, mergequeue, msgraph

#3848 add library deletion to test cleanup
  .github/actions/purge-m365-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: tests, supportability

#3847 add integration tests for missing drives
  .github/actions/purge-m365-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/onedrivePurge.ps1
  src/internal/m365/graph/errors.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: restore, mergequeue, tests, sharepoint

#3871 single-line cleanup scripts in gh
  .github/actions/purge-m365-data/action.yml
Labels: bug, mergequeue-priority

#3872 give library prefix delete list a default val
  .github/actions/purge-m365-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: bug, mergequeue-priority

#3877 atttempt ternary for value
  .github/actions/purge-m365-data/action.yml
Labels: bug, mergequeue-priority, tests

#3868 Create an interface and implementation for Reason struct
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/test/helper_test.go
Labels: mergequeue, tech-debt

#3881 remove the getM365 cmd
  src/cmd/getM365/exchange/get_item.go
  src/cmd/getM365/main.go
  src/cmd/getM365/onedrive/get_item.go
Labels: mergequeue, tech-debt

#3882 use replace collisions for nightly tests
  .github/actions/backup-restore-test/action.yml
  src/internal/m365/controller_test.go
  src/internal/m365/onedrive_test.go
Labels: mergequeue, tests

#3869 Have kopia package generate tags during backup based on Reasons
  src/internal/kopia/base_finder.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, tech-debt

#3875 allow users to limit page size
  src/cli/backup/exchange.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/flags/options.go
  src/cli/utils/options.go
  src/cli/utils/options_test.go
  src/cli/utils/testdata/flags.go
  src/cli/utils/users.go
  src/internal/events/events.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/exchange/container_resolver_test.go
  src/internal/m365/exchange/helper_test.go
  src/internal/m365/exchange/mail_container_cache_test.go
  src/internal/m365/exchange/restore_test.go
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/service_test.go
  src/internal/m365/onedrive/url_cache_test.go
  src/internal/m365/sharepoint/backup_test.go
  src/internal/m365/sharepoint/collection_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/control/options.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/m365.go
Labels: enhancement, mergequeue, cli, msgraph

#3885 First draft of a community-contributed blog post on multi-tenant backup
  website/blog/2023-07-24-multi-tenant-backup-with-corso.md
  website/blog/images/data-center.jpg
Labels: mergequeue

#3886 Add a couple more linters
  src/.golangci.yml
  src/internal/m365/graph/http_wrapper_test.go
Labels: mergequeue, supportability, tech-debt

#3857 Cleanup figuring out kopia retention parameters
  src/internal/kopia/conn.go
  src/internal/kopia/retention/opts.go
  src/internal/kopia/retention/opts_test.go
  src/internal/kopia/wrapper.go
Labels: mergequeue, tech-debt, kopia

#3852 Require passing AWS bucket for integration tests
  src/internal/tester/tconfig/config.go
Labels: mergequeue, tests, ci

#3879 update all graph packages
  src/go.mod
  src/go.sum
  src/internal/m365/graph/errors.go
Labels: mergequeue, tech-debt

#3855 add restore things container, move perms
  src/cli/backup/help_e2e_test.go
  src/cli/repo/s3_e2e_test.go
  src/cli/utils/options.go
  src/cli/utils/restore_config.go
  src/cli/utils/restore_config_test.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/internal/events/events_test.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/exchange/collection_test.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/helper_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/collection_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/onedrive_test.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/backup_test.go
  src/internal/m365/sharepoint/collection_test.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/backup_test.go
  src/internal/operations/help_test.go
  src/internal/operations/inject/containers.go
  src/internal/operations/inject/inject.go
  src/internal/operations/maintenance_test.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/control/options.go
  src/pkg/control/restore.go
  src/pkg/repository/repository_test.go
Labels: restore, tech-debt

#3858 add restore to alternate resource
  src/internal/common/idname/idname_test.go
  src/internal/m365/backup.go
  src/internal/m365/controller.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_caches.go
  src/internal/m365/restore.go
  src/internal/operations/restore.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/internal/tester/tconfig/config.go
  src/internal/tester/tconfig/protected_resources.go
Labels: enhancement, restore

#3876 Pass BackupBases directly to ConsumeBackupCollections
  src/internal/kopia/inject/inject.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue, backup, kopia

#3896 pii handling for restore config
  src/internal/m365/restore.go
  src/pkg/control/restore.go
  src/pkg/services/m365/api/sites.go
Labels: enhancement, mergequeue

#3902 Hide storage path for merge collections
  src/internal/kopia/merge_collection.go
Labels: mergequeue, supportability, kopia

#3901 Minor code cleanup
  src/internal/kopia/wrapper.go
Labels: mergequeue, backup, tech-debt, kopia

#3614 centralize the slack message action
  .github/actions/slack-message/action.yml
  .github/workflows/ci_test_cleanup.yml
  .github/workflows/longevity_test.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  website/docs/developers/linters.md
Labels: mergequeue, supportability

#3820 Operations level changes for OneDrive exports
  src/internal/archive/zip.go
  src/internal/events/events.go
  src/internal/m365/controller.go
  src/internal/m365/mock/connector.go
  src/internal/m365/support/status.go
  src/internal/operations/export.go
  src/internal/operations/export_test.go
  src/internal/operations/inject/inject.go
Labels: enhancement, onedrive

#3912 use proper resource ids in factory
  .github/actions/slack-message/action.yml
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/factory/impl/sharepoint.go
Labels: bug, mergequeue-priority, tests

#3914 Delete details snapshot
  src/pkg/repository/repository.go
Labels: bug, mergequeue

#3916 rename export interface
  src/internal/m365/export.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/export.go
  src/internal/m365/onedrive/export_test.go
  src/internal/operations/export.go
  src/internal/operations/inject/inject.go
Labels: mergequeue, tech-debt

#3870 clean up exchange adv restore test
  src/internal/operations/test/exchange_test.go
Labels: mergequeue, tests, tech-debt

#3822 CLI for exporting data from OneDrive
  CHANGELOG.md
  src/cli/cli.go
  src/cli/export/export.go
  src/cli/export/export_test.go
  src/cli/export/onedrive.go
  src/cli/export/onedrive_test.go
  src/cli/flags/export.go
  src/cli/utils/export_config.go
  src/cli/utils/export_config_test.go
  src/cli/utils/onedrive.go
  src/cli/utils/testdata/flags.go
  src/internal/observe/observe.go
  src/pkg/control/restore.go
Labels: enhancement, mergequeue, onedrive

#3909 Separate pieces of sanity test into different package
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/restore/onedrive.go
  src/cmd/sanity_test/restore/sharepoint.go
  src/cmd/sanity_test/sanity_tests.go
  src/cmd/sanity_test/utils/utils.go
Labels: mergequeue, tests, tech-debt

#3910 Sanity tests for OneDrive exports
  .github/actions/backup-restore-test/action.yml
  src/cmd/sanity_test/common/common.go
  src/cmd/sanity_test/common/utils.go
  src/cmd/sanity_test/export/onedrive.go
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/restore/onedrive.go
  src/cmd/sanity_test/restore/sharepoint.go
  src/cmd/sanity_test/sanity_tests.go
Labels: mergequeue, onedrive, tests, export

#3903 Allow setting retention parameters on repo init
  src/cli/backup/help_e2e_test.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/operations/maintenance_test.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/helper_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, kopia

#3924 Pull backup deletion logic into function
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, tech-debt, ci

#3865 Retention update op
  src/internal/operations/retention_config.go
  src/internal/operations/retention_config_test.go
  src/pkg/repository/repository.go
Labels: mergequeue

#3930 Track and print stats about merging
  src/internal/kopia/upload.go
Labels: mergequeue, backup, supportability, tech-debt, kopia

#3933 Update clues dependency
  src/go.mod
  src/go.sum
  src/internal/common/pii/url.go
  src/internal/observe/observe.go
  src/pkg/control/restore.go
  src/pkg/filters/filters.go
  src/pkg/path/elements.go
  src/pkg/path/path.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
Labels: mergequeue, supportability, dependencies, tech-debt

#3925 Add test to lookup deleted backup by opening old version of repo
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, ci

#3934 Minor refactor for handling of LoggableDir
  src/pkg/path/elements.go
Labels: mergequeue, supportability, tech-debt

#3935 Better handling of clues, error, and log data if it's PII
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
Labels: mergequeue, supportability, tech-debt

#3938 Track when we skip merging due to DoNotMerge
  src/internal/kopia/upload.go
Labels: mergequeue, backup, supportability, kopia
