Repository alcionai/corso, pull requests merged in 2023-12, with the labels that each got.

#4583 prep groups handler for addition of conversations
  src/cli/backup/groups.go
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/groups_test.go
  src/cli/flags/groups.go
  src/cli/flags/testdata/flags.go
  src/cli/flags/testdata/groups.go
  src/cli/flags/testdata/sharepoint.go
  src/cli/utils/groups.go
  src/cli/utils/groups_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/groups/conversation_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/collection/groups/mock/getter.go
  src/internal/m365/service/groups/backup.go
  src/internal/operations/test/group_test.go
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/groups.go
  src/pkg/path/elements.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
  src/pkg/selectors/testdata/groups.go
Labels: mergequeue, backup, teams & groups

#4759 Minor update to secret name/step name
  .github/workflows/sanity-test.yaml
Labels: mergequeue, ci

#4766 Remove duplicate recoverable err during item download
  src/internal/m365/collection/drive/collection.go
Labels: mergequeue, tech-debt

#4776 add insufficient auth to graph, errs
  src/pkg/errs/errs.go
  src/pkg/errs/errs_test.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
  src/pkg/services/m365/api/graph/logging.go
Labels: mergequeue, msgraph

#4778 Fix panic in GroupByID call
  src/pkg/services/m365/api/groups.go
Labels: mergequeue

#4761 persist deleted file markers for exclude
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
Labels: bug, backup, onedrive

#4781 Skip nightly conversations details test
  src/cli/backup/groups_e2e_test.go
Labels: mergequeue, tests

#4763 Minio custom query params
  src/go.mod
  src/go.sum
  src/internal/kopia/s3.go
  src/pkg/storage/storage.go
Labels: mergequeue, supportability

#4724 add and delete file support in the tree
  src/.golangci.yml
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter.go
  src/pkg/count/keys.go
Labels: mergequeue, backup, onedrive

#4748 Remove sharepointids from delta query $select params
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/drive_pager_test.go
Labels: mergequeue, tech-debt

#4467 Rewrite remaining directory iteration during hierarchy merging
  src/internal/kopia/upload.go
Labels: mergequeue, backup, supportability, tech-debt, kopia

#4798 Allow setting the minimum epoch duration in kopia
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/pkg/control/repository/persistent_config.go
Labels: enhancement, mergequeue, kopia

#4801 Minor url cache logging & counting improvements
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/url_cache.go
  src/pkg/count/keys.go
Labels: mergequeue, tech-debt

#4788 [Snyk] Security upgrade ubuntu from mantic-20231011 to 23.10
  website/Dockerfile
Labels: mergequeue

#4756 Fix sanity tests for exchange emails export
  src/cmd/sanity_test/common/sanitree.go
  src/cmd/sanity_test/export/exchange.go
  src/cmd/sanity_test/restore/exchange.go
Labels: mergequeue, tests

#4773 Handle cases where we don't have attachment data
  src/internal/converters/eml/eml.go
Labels: mergequeue

#4774 Fix OneDrive sanity tests
  src/cmd/sanity_test/driveish/driveish.go
Labels: mergequeue, tests

#4799 Wire up setting min epoch duration
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/persistent_config.go
  src/internal/operations/persistent_config_test.go
  src/pkg/repository/repository.go
Labels: enhancement, mergequeue, kopia

#4787 fetches lists using Lists client wrapper
  src/internal/m365/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
Labels: backup, sharepoint, lists

#4786 implements lists backup handler
  src/internal/m365/backup_test.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/service/sharepoint/backup.go
Labels: backup, sharepoint, lists

#4735 swap stats for in-tree item counts for limits
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
Labels: backup, onedrive

#4783 Add custom drive item
  src/pkg/services/m365/custom/drive_item.go
  src/pkg/services/m365/custom/drive_item_test.go
Labels: mergequeue, backup, onedrive, perf

#4784 Switch to custom drive items for backup operations
  CHANGELOG.md
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/handler_utils.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/drive/user_drive_handler.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
  src/pkg/services/m365/custom/drive_item.go
  src/pkg/services/m365/custom/drive_item_test.go
Labels: mergequeue, onedrive, perf

#4807 Update kopia version
  src/go.mod
  src/go.sum
Labels: mergequeue, kopia

#4811 Add a GetTeamByID API to lookup a team by ID
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
Labels: mergequeue

#4814 reduce double-value logging
  src/pkg/logger/logger.go
Labels: supportability

#4746 require rootID on tree construction
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/drive/user_drive_handler.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/count/keys.go
Labels: mergequeue, backup, onedrive

#4809 fix messages backup deadlock
  CHANGELOG.md
  src/internal/m365/service/groups/backup.go
Labels: bug, mergequeue, backup, teams & groups

#4813 remove 'errors' from count keys
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_scale_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/collection/exchange/collection.go
  src/pkg/count/keys.go
  src/pkg/logger/logger.go
Labels: mergequeue, supportability

#4823 Adding new call to services middleware
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/groups_test.go
Labels: mergequeue

#4824 use cuustom.DriveItem, fix errors
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
Labels: bug, backup, onedrive

#4797 return global excluded file IDs with colls
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
Labels: backup, onedrive

#4796 swap tree file types for models.DriveItemable
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
Labels: backup, onedrive

#4795 produce collections from tree
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/pkg/count/keys.go
Labels: backup, onedrive

#4816 minor mail attachment cleanup
  src/pkg/services/m365/api/mail.go
Labels: mergequeue, tech-debt, exchange, msgraph

#4829 Add changelog for v0.17.0 release
  CHANGELOG.md
Labels: documentation, mergequeue-priority

#4777 add test.t and pfx to test tree generators
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/pkg/count/keys.go
Labels: mergequeue, backup, onedrive, tests

#4834 Skip emails that cannot be retrieved
  CHANGELOG.md
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/pkg/fault/item.go
  src/pkg/fault/skipped.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
Labels: mergequeue, backup, exchange, msgraph

#4840 Add retries for posting item attachments
  CHANGELOG.md
  src/internal/m365/collection/exchange/restore.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
Labels: bug, mergequeue, exchange, msgraph

#4821 errant minor fixes
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
Labels: backup, onedrive, tests

#4819 use a drive to identify all file paths
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/url_cache_test.go
Labels: backup, onedrive, tests

#4817 4689 cleanup 2
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
Labels: backup, onedrive, tests

#4843 Just pass in config to helpers
  src/internal/m365/controller_test.go
  src/internal/m365/onedrive_test.go
Labels: mergequeue, tests, tech-debt

#4842 Exit test early if setup fails
  src/internal/operations/test/exchange_test.go
Labels: mergequeue, tests, tech-debt

#4805 clean up drive unit test helpers
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
Labels: mergequeue, backup, onedrive, tests

#4856 deduplicate error messages for ease of debugging
  src/internal/m365/collection/exchange/export.go
Labels: mergequeue

#4857 Add config passing test that future PRs will leverage
  src/internal/operations/backup_test.go
Labels: mergequeue, backup, tests, tech-debt

#4825 fix up failures found when manually testing
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
Labels: bug, mergequeue, backup, onedrive

#4847 fetch fields data for a list item
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_pager_test.go
Labels: backup, sharepoint, lists

#4849 populates list items count to backup details info
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/lists_test.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/collection/site/restore.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: backup, sharepoint, lists

#4850 enables sharepoint lists category for backup
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/flags/sharepoint.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/selectors/testdata/sharepoint.go
Labels: backup, sharepoint, lists

#4863 patch byte limit handling
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
Labels: backup, onedrive

#4845 ensure the tree limiter handling is correct
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
Labels: backup, onedrive, tests

#4841 ensure creation of .dirmeta files
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/pkg/services/m365/custom/drive_item.go
Labels: bug, backup, onedrive

#4833 fix up test fullPath generation
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/pkg/services/m365/custom/drive_item.go
Labels: mergequeue, backup, onedrive, tests

#4854 implement lists restore handler
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/m365/service/sharepoint/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, sharepoint, lists

#4853 provision to post and delete lists or list items
  src/internal/common/keys/keys.go
  src/internal/common/keys/keys_test.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/m365/service/sharepoint/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, sharepoint, lists

#4852 relocate list and pages de-serialization functions
  src/internal/common/keys/keys.go
  src/internal/common/keys/keys_test.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/sharepoint/api/pages.go
  src/internal/m365/service/sharepoint/api/pages_test.go
  src/internal/m365/service/sharepoint/api/serialization.go
  src/internal/m365/service/sharepoint/api/serialization_test.go
  src/internal/m365/service/sharepoint/mock/mock_test.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/m365/service/sharepoint/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, sharepoint, lists

#4867 Do not try to export items with error
  src/cli/export/export.go
  src/pkg/export/consume.go
  src/pkg/export/consume_test.go
Labels: bug, mergequeue, export

#4868 Add shortref and rename item_id
  src/internal/converters/eml/eml.go
  src/internal/m365/collection/exchange/export.go
  src/internal/m365/service/exchange/export_test.go
Labels: mergequeue, export

#4869 Accept possibly incorrect email addressses in export
  src/go.mod
  src/go.sum
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
Labels: mergequeue, exchange, export

#4860 Add struct definitions and CLI helpers for backup options
  src/cli/backup/exchange_test.go
  src/cli/backup/groups_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/utils/options.go
  src/pkg/control/backup.go
  src/pkg/control/options.go
Labels: mergequeue, backup

#4875 beef up the unit tests
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
Labels: backup, onedrive, tests

#4879 Fix inline images for eml exports
  src/internal/converters/eml/eml.go
Labels: bug, mergequeue, exchange, export

#4880 Do not try to add empty attachments to eml export
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
Labels: mergequeue-priority, mergequeue, exchange, export

#4881 Add tests to check for invalid email addresses in eml export
  src/internal/converters/eml/eml_test.go
  src/internal/data/metrics.go
  src/internal/m365/collection/drive/export.go
  src/internal/m365/collection/exchange/export.go
  src/internal/m365/collection/groups/export.go
  src/internal/m365/collection/groups/export_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/service/exchange/export.go
  src/internal/m365/service/exchange/export_test.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
  src/internal/operations/export.go
  src/internal/operations/inject/inject.go
  src/pkg/export/export.go
  src/pkg/metrics/metrics.go
Labels: mergequeue-priority, mergequeue, tests, exchange, export

#4865 deltaURL stub refactor
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
Labels: mergequeue, backup, onedrive, tests

#4888 Remove other event fields ignored by server
  CHANGELOG.md
  src/internal/m365/collection/exchange/transform.go
  src/internal/m365/collection/exchange/transform_test.go
  src/internal/m365/service/exchange/mock/event.go
Labels: bug, mergequeue, exchange, msgraph

#4594 fix up cli tabular display and locationRef
  src/cli/backup/groups_e2e_test.go
  src/cli/utils/groups_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/groups/conversation_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/collection/groups/mock/getter.go
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/groups_test.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
  src/pkg/services/m365/api/conversations_test.go
Labels: mergequeue, backup, teams & groups

#4890 Exclude conversation selectors from export and restore
  src/cli/export/groups.go
  src/cli/restore/groups.go
Labels: bug, mergequeue, export, teams & groups

#4894 Update to latest go-simple-mail
  src/go.mod
  src/go.sum
  src/internal/converters/eml/eml.go
Labels: mergequeue, exchange, export

#4895 Remove options form service handler initializer
  src/cmd/factory/impl/common.go
  src/internal/m365/controller_test.go
  src/internal/m365/export.go
  src/internal/m365/service/exchange/export.go
  src/internal/m365/service/exchange/export_test.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/groups/restore_test.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/restore_helper_test.go
  src/pkg/repository/exports.go
  src/pkg/repository/restores.go
Labels: mergequeue

#4889 fix new backup excluded files
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/controller_test.go
Labels: bug, backup, onedrive, tests

#4887 add unselected collections to tree
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/controller_test.go
Labels: bug, backup, onedrive

#4886 remove the rootID in the tree
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/controller_test.go
  src/internal/operations/test/groups_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: bug, backup, onedrive

#4864 add incremental test coverage for tree backup
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/controller_test.go
  src/internal/operations/test/driveish_test.go
  src/internal/operations/test/groups_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: backup, onedrive, tests

#4870 ignore lists with webTemplateExtensionsList template while creation
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, sharepoint, lists

#4893 change kopia location directory from list name to id
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/collection.go
  src/pkg/backup/details/details_test.go
  src/pkg/services/m365/api/lists_test.go
Labels: backup, sharepoint, lists

#4871 filter out lists with template as 'webTemplateExtensionsList'
  src/cli/flags/sharepoint.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/selectors/sharepoint_test.go
Labels: backup, sharepoint, lists

#4851 updates sharepoint info to accommodate site-url and item-template
  src/cli/flags/sharepoint.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/backup/details/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: backup, sharepoint, lists

#4848 sharepoint lists backup details
  src/cli/flags/sharepoint.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/lists_test.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/backup/details/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: backup, sharepoint, lists

#4904 fix tests parameters
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/service/sharepoint/restore_test.go
Labels: sharepoint, lists

#4908 allow creation of restore paths for sharepoint lists
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/lists.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/builder.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: sharepoint, lists

#4898 Beef up Exchange export error handling
  src/internal/converters/eml/eml.go
  src/internal/m365/collection/exchange/export.go
Labels: mergequeue, supportability, exchange, export

#4911 separate operations tests into packages
  src/internal/operations/test/m365/backup_helper.go
  src/internal/operations/test/m365/driveish.go
  src/internal/operations/test/m365/exchange/exchange_test.go
  src/internal/operations/test/m365/groups/groups_test.go
  src/internal/operations/test/m365/helper.go
  src/internal/operations/test/m365/onedrive/onedrive_test.go
  src/internal/operations/test/m365/restore_helper.go
  src/internal/operations/test/m365/sharepoint/sharepoint_test.go
  src/internal/operations/test/onedrive_test.go
Labels: tests

#4885 use tree version in nightly tests
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/controller_test.go
  src/internal/m365/onedrive_test.go
  src/internal/operations/test/m365/backup_helper.go
  src/internal/operations/test/m365/driveish.go
  src/internal/operations/test/m365/exchange/exchange_test.go
  src/internal/operations/test/m365/groups/groups_test.go
  src/internal/operations/test/m365/helper.go
  src/internal/operations/test/m365/onedrive/onedrive_test.go
  src/internal/operations/test/m365/restore_helper.go
  src/internal/operations/test/m365/sharepoint/sharepoint_test.go
Labels: mergequeue, backup, onedrive, tests

#4901 Log and ignore sharing disabled errors when doing permissions restores
  CHANGELOG.md
  src/internal/m365/collection/drive/permission.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
Labels: bug, restore, mergequeue, onedrive, sharepoint, teams & groups

#4900 better parsing of graph odata errs
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
  src/pkg/services/m365/api/graph/testdata/errors.go
Labels: mergequeue, tech-debt

#4905 Note about anonymous link shares
  src/internal/m365/collection/drive/metadata/permissions.go
Labels: mergequeue

#4916 adds ListInfo details to SharepointInfo details
  src/internal/m365/collection/drive/helper_test.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/backup/details/sharepoint.go
  src/pkg/services/m365/api/graph/testdata/errors.go
Labels: mergequeue, backup, sharepoint, lists

#4919 adds list backup and restore handlers
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/mock/list.go
Labels: mergequeue, sharepoint, lists

#4920 enables sharepoint to use lists backup handler for lists ops
  src/internal/m365/backup_test.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/helper_test.go
  src/internal/m365/collection/site/lists.go
  src/internal/m365/collection/site/lists_test.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/operations/test/m365/sharepoint/sharepoint_test.go
  src/pkg/selectors/testdata/sharepoint.go
Labels: mergequeue, sharepoint, lists

#4924 cli changes for sharepoint lists
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/flags/sharepoint.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
Labels: mergequeue, sharepoint, lists

#4922 enable restore path creation for sharepoint lists
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/builder.go
Labels: mergequeue, sharepoint, lists

#4923 enables sharepoint to use lists restore handler for lists ops
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/helper_test.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/m365/service/sharepoint/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: mergequeue, sharepoint, lists

#4926 fix: integrate correct AddCategories
  src/cli/backup/sharepoint.go
  src/cli/utils/sharepoint.go
Labels: mergequeue, sharepoint, lists

#4906 Add prefetch collection for groups
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: mergequeue, tech-debt, teams & groups

#4907 Add feature flag to disable lazy item reader
  src/cli/backup/groups.go
  src/cli/backup/groups_test.go
  src/cli/flags/options.go
  src/cli/utils/options.go
  src/internal/operations/backup_test.go
  src/pkg/control/options.go
Labels: mergequeue, backup, cli, teams & groups

#4912 Minor refactor of status update code
  src/internal/m365/collection/groups/collection.go
Labels: mergequeue, tech-debt, teams & groups

#4930 Disable export and restore for sharepoint lists
  src/cli/export/sharepoint.go
  src/cli/restore/sharepoint.go
Labels: bug, mergequeue, tests

#4913 Add lazy item reader for groups
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: enhancement, mergequeue, teams & groups

#4925 JSON sanitizer and tests
  src/internal/common/sanitize/json.go
  src/internal/common/sanitize/json_test.go
  src/internal/converters/eml/tools/main.go
  src/pkg/services/m365/api/mail_test.go
Labels: bug, mergequeue, exchange

#4934 skip cleanup of hidden list
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue, ci

#4935 fixes lists delete in CI during sites purge
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue, ci

#4933 replaces deleteList with errors fault bus
  src/internal/m365/collection/site/handlers.go
  src/internal/m365/collection/site/lists_handler.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, mergequeue, sharepoint, lists

#4927 Some testing QoL functions
  src/internal/m365/helper_test.go
  src/internal/operations/backup_test.go
  src/internal/tester/check.go
Labels: mergequeue, tests, supportability

#4928 Sanitize JSON input if it's invalid on the first attempt
  CHANGELOG.md
  src/internal/m365/collection/exchange/restore.go
  src/internal/m365/controller_test.go
  src/internal/m365/service/exchange/export_test.go
  src/internal/m365/service/exchange/mock/mail.go
  src/pkg/services/m365/api/consts.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: bug, mergequeue, exchange

#4939 Skip group mailbox items that were deleted in flight
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: bug, mergequeue, teams & groups

#4921 Integrate lazy item reader into conversations backup
  CHANGELOG.md
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/service/groups/backup.go
  src/internal/operations/test/m365/groups/groups_test.go
Labels: mergequeue, teams & groups

#4940 skips backup of non-recoverable list templates
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: mergequeue, sharepoint, lists

#4942 Fix docs rendering by updating mdx-mermaid
  website/package-lock.json
  website/package.json
Labels: mergequeue

#4929 Remove duplicated integration tests for groups
  src/internal/operations/test/m365/groups/groups_test.go
Labels: mergequeue, tests, tech-debt

#4931 skips lists with certain templates from being backed-up
  src/internal/m365/collection/site/restore.go
  src/internal/m365/collection/site/restore_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/lists_test.go
Labels: restore, mergequeue, sharepoint, lists

#4945 implements lists lazy fetch
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/service/sharepoint/backup.go
Labels: backup, sharepoint, lists

#4944 lists collection stores last modified time
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/service/sharepoint/backup.go
  src/pkg/services/m365/api/lists_pager_test.go
Labels: backup, sharepoint, lists

#4943 lists prefetech
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/mock/list.go
  src/internal/m365/service/sharepoint/backup.go
  src/pkg/services/m365/api/lists_pager_test.go
Labels: mergequeue, backup, sharepoint, lists
