Repository alcionai/corso, pull requests merged in 2023-04, with the labels that each got.

#3005 introduce fail-after-recovery option
  src/cli/options/options.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/operations/backup.go
  src/internal/operations/helpers.go
  src/internal/operations/helpers_test.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/control/options.go
  src/pkg/repository/loadtest/repository_load_test.go
Labels: restore, mergequeue, backup

#2938 Enhancement Sanity Test: verify permissions and defined data
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/sanity_tests.go
  src/internal/common/time.go
  src/internal/tester/resource_owners.go
Labels: mergequeue

#2998 update failure logs
  src/cli/utils/utils.go
  src/internal/events/events.go
Labels: mergequeue, supportability

#3012 Log responses for 503
  src/internal/connector/graph/service.go
Labels: mergequeue

#3004 wrap repo backup data.notfound errors
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/store/backup.go
  src/pkg/store/backup_test.go
  src/pkg/store/mock/model_store.go
  src/pkg/store/mock/wrapper.go
Labels: enhancement, mergequeue, tests

#2829 Populate location for all Exchange data types
  CHANGELOG.md
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
Labels: bug, mergequeue, backup, exchange

#3014 Pull in modified kopia for mem usage
  src/go.mod
  src/go.sum
Labels: mergequeue, scalability

#2934 introduce idnamer
  src/internal/common/idname.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_connector.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
Labels: mergequeue, backup

#3009 clean up exchangePurge output
  src/cmd/purge/scripts/exchangePurge.ps1
Labels: bug, mergequeue

#2981 Enable permissions backup by default
  CHANGELOG.md
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/options/options.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/pkg/control/options.go
Labels: mergequeue

#3019 Cleanup birthday events for old contacts
  src/cmd/purge/scripts/exchangePurge.ps1
Labels: mergequeue

#3021 Remove unnecessary indirection for retries
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
Labels: mergequeue

#2994 add clues.Hide to various logs
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/logger/example_logger_test.go
  src/pkg/repository/repository.go
  src/pkg/services/m365/m365.go
Labels: mergequeue, supportability

#2955 introduce id-name lookup maps
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cmd/factory/impl/common.go
  src/internal/common/idname.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/services/m365/m365.go
Labels: mergequeue, backup, msgraph

#3030 fix preview text for blog post
  website/blog/2023-4-04-aws-storage-class.md
Labels: mergequeue

#3031 fix user validation in factory
  src/cmd/factory/impl/common.go
  src/pkg/services/m365/m365.go
Labels: bug, mergequeue-priority

#3033 Bump clues version to HEAD of main
  src/go.mod
  src/go.sum
Labels: bug, mergequeue

#3024 No warn logs
  src/.golangci.yml
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/events/events_signal_windows.go
Labels: mergequeue, tech-debt

#3037 add display name to m365 sites()
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: enhancement, msgraph

#2958 move sharepoint onto map-based lookup
  src/cli/backup/exchange.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/print/print.go
  src/internal/common/ptr/pointer.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/discovery/api/sites.go
  src/internal/connector/discovery/api/sites_test.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/discovery/discovery_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, backup, sharepoint

#3045 extend, rather than replace, NewBackup
  src/cli/backup/backup.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: enhancement, mergequeue-priority

#3038 Switch LocationPath return type
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/data/data_collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue, backup

#3026 Graph PowerShell troubleshooter
  src/cmd/graph_pwsh/Auth-Graph.ps1
  src/cmd/graph_pwsh/Dockerfile
  src/cmd/graph_pwsh/README.md
  src/cmd/graph_pwsh/env_names
Labels: mergequeue

#3058 use clues with plaintext as default
  src/go.mod
  src/go.sum
  src/internal/tester/suite.go
Labels: mergequeue, tests, supportability

#3052 force userPN on exchange, onedrive backup
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/pkg/repository/repository.go
Labels: bug, mergequeue-priority, backup, onedrive, exchange

#2991 Add GetUserInfo to services/m365
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/internal/common/idname.go
  src/internal/connector/data_collections.go
  src/internal/connector/discovery/api/users.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/discovery/discovery_test.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, msgraph

#3062 Folder display name fix
  src/cli/backup/exchange.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, mergequeue-priority, backup, exchange

#2999 options cli pkg cleanup
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/options/options.go
  src/cli/options/options_test.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
Labels: mergequeue, cli, tech-debt

#3051 Add support for remote scripts to pwsh troubleshooter
  src/cmd/graph_pwsh/Dockerfile
  src/cmd/graph_pwsh/Execute-Script.ps1
  src/cmd/graph_pwsh/README.md
Labels: mergequeue

#3066 centralized sdk err is checker
  src/pkg/err/err.go
  src/pkg/err/err_test.go
Labels: mergequeue, supportability

#2973 look up users and sites by id or name
  src/cli/backup/backup.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/discovery/api/sites.go
  src/internal/connector/discovery/api/sites_test.go
  src/internal/connector/discovery/api/users.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/tester/config.go
  src/internal/tester/resource_owners.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: mergequeue, backup, msgraph

#3071 Switching user identification and hashing
  src/internal/events/events.go
Labels: mergequeue

#2883 Exit early if context is marked as done
  src/internal/connector/graph/retry_middleware.go
Labels: mergequeue, supportability, tech-debt

#3054 Add basic prefix matcher type
  src/internal/common/prefixmatcher/prefix_matcher.go
  src/internal/common/prefixmatcher/prefix_matcher_test.go
Labels: enhancement, mergequeue

#3079 rename package to avoid varname shadowing
  src/pkg/errs/err.go
  src/pkg/errs/errs_test.go
Labels: mergequeue, tech-debt

#3065 split in pwsh, not gh action
  src/cmd/purge/scripts/exchangePurge.ps1
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue, supportability

#3084 Quick ci fix
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue-priority

#3057 optionally look up and union fallback manifests
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
Labels: enhancement, mergequeue, backup

#3055 Use prefix matcher when merging backup details
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/kopia/merge_details.go
  src/internal/kopia/merge_details_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/streamstore/streamstore.go
Labels: enhancement, mergequeue, backup

#3082 remove weburl suffix support from sharepoint
  src/cli/backup/sharepoint.go
  src/cli/restore/sharepoint.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/internal/connector/discovery/api/sites.go
  src/internal/connector/graph_connector.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, restore, mergequeue, backup, cli

#2664 Lint for using suite.T().Run instead of testify's suite.Run
  src/.golangci.yml
  src/internal/connector/sharepoint/pageInfo_test.go
  src/internal/operations/manifests_test.go
  src/pkg/account/account_test.go
  src/pkg/account/m365_test.go
  src/pkg/filters/filters_test.go
  src/pkg/path/path_test.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/sharepoint_test.go
  src/pkg/storage/common_test.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage_test.go
Labels: mergequeue, tests, supportability

#3046 Correct malware blog's slug
  website/blog/2023-04-08-malware.md
Labels: mergequeue

#3087 remove "errors" from log message
  src/internal/operations/helpers.go
Labels: mergequeue, supportability

#3088 cleanup external site
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue-priority, supportability

#3017 add Concealer compliance to paths
  src/internal/common/pii/pii.go
  src/internal/common/pii/pii_test.go
  src/internal/common/pii/url.go
  src/internal/common/pii/url_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/observe/observe.go
  src/internal/operations/backup.go
  src/pkg/path/elements.go
  src/pkg/path/elements_test.go
  src/pkg/path/onedrive.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: enhancement, mergequeue, supportability

#3095 separate matrix and job for site cleanup
  .github/actions/purge-m365-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  .github/workflows/load_test.yml
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue-priority, supportability

#3098 Log resource owner name, not full selector during backup
  src/internal/operations/backup.go
Labels: bug, mergequeue, backup, supportability

#3090 separate fault bus in fetch manifests
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
Labels: bug, mergequeue

#3056 Combine backup details merging structs
  src/internal/kopia/merge_details.go
  src/internal/kopia/merge_details_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup

#3022 Compute parent permissions from available metadata
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/permission_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
Labels: restore, mergequeue, onedrive

#3103 [Sanity test]- skip owner permission in onedrive restore check
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/sanity_tests.go
Labels: bug

#3105 fix sanity tests when no non-owner roles exist
  src/cmd/sanity_test/sanity_tests.go
Labels: bug, mergequeue-priority, tests

#3025 moving code around, no logic changes
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/retry_middleware.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/shared.go
Labels: mergequeue, tech-debt

#3100 Create abstraction to represent a unique location
  src/internal/operations/manifests_test.go
  src/internal/version/backup.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/path/onedrive.go
  src/pkg/path/onedrive_test.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
Labels: enhancement, mergequeue, backup

#3109 Fix NPE panic
  src/internal/operations/backup.go
Labels: bug, mergequeue, backup

#3107 sanity test: add assert func
  src/cmd/sanity_test/sanity_tests.go
Labels: mergequeue-priority, tests, supportability

#3006 Add misc typo fixes
  src/README.md
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/flags.go
  src/cli/utils/testdata/flags.go
  src/cli/utils/utils.go
  src/cmd/factory/factory.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/purge/scripts/onedrivePurge.ps1
  src/internal/common/ptr/pointer_test.go
  src/internal/connector/discovery/api/beta_service.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/graph/betasdk/models/horizontal_section.go
  src/internal/connector/graph/betasdk/models/vertical_section.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph_connector.go
  src/internal/connector/mockconnector/mock_data_message.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/m365Transform.go
  src/internal/connector/uploadsession/uploadsession_test.go
  src/internal/kopia/conn.go
  src/internal/kopia/model_store.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/streamstore/mock/mock.go
  src/internal/tester/resource_owners.go
  src/pkg/fault/fault.go
  src/pkg/fault/item.go
  src/pkg/logger/example_logger_test.go
  src/pkg/path/path.go
  website/blog/2022-12-12-benchmarking-intel-vs-arm-for-backup-applications.md
  website/docs/setup/m365-access.md
Labels: documentation, good first issue, mergequeue

#3104 Fix disable-incrementals flag in OneDrive
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/options/options.go
  src/cli/options/options_test.go
Labels: mergequeue

#3086 Fetch individual attachments in case of full download failure
  CHANGELOG.md
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/exchange/api/mock/mail.go
  src/internal/connector/graph/mock/service.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
Labels: mergequeue

#3068 clean up cli e2e tests
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/help_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/internal/tester/resource_owners.go
Labels: mergequeue, tests, tech-debt

#3018 rearranging paths funcs, no logic changes
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
Labels: mergequeue, tech-debt

#3110 Wire up LocationIRef stuff to details merge
  src/internal/data/data_collection.go
  src/internal/kopia/merge_details.go
  src/internal/kopia/merge_details_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: enhancement, mergequeue, backup

#3076 change user flag
  .github/workflows/load_test.yml
  .github/workflows/sanity-test.yaml
  src/cli/backup/exchange.go
  src/cli/cli.go
  src/cli/utils/flags.go
  website/docs/quickstart.md
Labels: mergequeue

#3085 Fix error with backup list --backup ID (backup created with an older corso version)
  src/cli/backup/backup.go
  src/pkg/repository/repository.go
Labels: mergequeue

#3123 correct usage of mailbox flag
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3118 fix overlapping bases after fallback union
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
Labels: bug, mergequeue, backup

#3000 add sensitive info flag to cli
  src/cli/cli.go
  src/cmd/sanity_test/sanity_tests.go
  src/internal/connector/graph/middleware.go
  src/pkg/logger/example_logger_test.go
  src/pkg/logger/logger.go
  src/pkg/logger/logger_test.go
Labels: mergequeue, supportability

#3111 Populate and persist OneDrive LocationRef
  CHANGELOG.md
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore_test.go
  src/internal/kopia/merge_details.go
  src/internal/kopia/merge_details_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/version/backup.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: enhancement, mergequeue, backup

#3127 clean unused options, reduce folders call
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/options.go
Labels: mergequeue, tech-debt, msgraph

#3044 add pii supporting stringers to filters
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
Labels: blocked, supportability

#3141 add NoBackup version const
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/data_collections_test.go
  src/internal/kopia/upload_test.go
  src/internal/operations/backup.go
  src/internal/version/backup.go
Labels: tech-debt

#3028 use slices for all filter targets
  src/internal/model/schema_string.go
  src/pkg/filters/comparator_string.go
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, supportability

#3143 Bump to rebased kopia fork
  src/go.mod
  src/go.sum
Labels: bug, mergequeue, dependencies

#3130 move largeItem client constructor into new GC
  src/cmd/factory/impl/common.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository.go
Labels: mergequeue, tech-debt, msgraph

#3157 Add immutable ID header to Get requests
  src/cmd/getM365/exchange/get_item.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/control/options.go
Labels: enhancement, mergequeue, backup, exchange

#3117 Update permissions diff computation
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/permission_test.go
  src/internal/tester/config.go
  src/internal/tester/resource_owners.go
Labels: mergequeue

#3166 [Feature] Move connector api module from internal -> pkg
  src/internal/connector/discovery/discovery.go
  src/internal/connector/discovery/discovery_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/restore.go
  src/pkg/services/m365/api/api.go
  src/pkg/services/m365/api/beta_service.go
  src/pkg/services/m365/api/beta_service_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
  src/pkg/services/m365/m365.go
Labels: mergequeue

#3145 use equals filter by default
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
Labels: mergequeue, tech-debt

#3155 send notification on action failure
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3140 Redo folder generation in backup details
  src/cli/backup/exchange_e2e_test.go
  src/internal/connector/exchange/mock/collections.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/data/mock/collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/repository/repository_unexported_test.go
Labels: enhancement, mergequeue, backup

#3168 Show name instead of id in onedrive backup progress
  src/internal/connector/onedrive/collection.go
Labels: mergequeue

#3174 clean metadata suffix from itemRef
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/utils/testdata/opts.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: backup

#3160 add itemref to details entry
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/utils/testdata/opts.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, restore, mergequeue, backup

#3176 Handle SyncStateInvalid error when ImmutableIDs are enabled after initial backup
  src/cli/backup/exchange.go
  src/cli/options/options.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
Labels: mergequeue

#3167 [Snyk] Security upgrade ubuntu from 22.04 to 22.10
  website/Dockerfile
Labels: mergequeue

#3133 New blog post on backup frequency
  website/blog/2023-04-24-backup-frequency.md
  website/blog/images/astro-clock.jpg
Labels: mergequeue

#3187 hold off on running the migratiton, will add later
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/version/backup.go
  src/pkg/repository/repository.go
Labels: backup

#3172 allow dir movements without locations
  src/internal/connector/graph/collections.go
  src/internal/connector/graph/collections_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/operations/backup_integration_test.go
  src/pkg/backup/details/mock/location_ider.go
Labels: bug, backup, tests

#3132 custom http wrapper for item downloads
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/api/mock/mail.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/http_wrapper.go
  src/internal/connector/graph/http_wrapper_test.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/mock/service.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: bug, mergequeue, msgraph

#3128 print stats after backup
  src/cli/backup/backup.go
  src/cli/print/print.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/backup/details/details.go
Labels: enhancement, mergequeue, cli

#3159 [Snyk] Security upgrade ubuntu from latest to 22.10
  docker/Dockerfile
Labels: mergequeue

#3190 fix the file/line output on panic recovery
  src/internal/common/crash/crash.go
  src/internal/common/crash/crash_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: bug, mergequeue

#3186 Handle subfolder moves and parent deletions right
  CHANGELOG.md
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
Labels: bug, mergequeue, backup, kopia

#3175 cleaning up some gc/selector test construction
  src/cmd/factory/impl/common.go
  src/cmd/purge/purge.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/help_test.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository.go
Labels: mergequeue, tests

#3003 move parallelism logs/checks upstream
  src/cli/backup/help_e2e_test.go
  src/cli/options/options.go
  src/cli/repo/s3_e2e_test.go
  src/cmd/factory/impl/exchange.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/consts.go
  src/internal/connector/graph/consts_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/events/events_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/control/options.go
  src/pkg/repository/repository_test.go
Labels: mergequeue, tech-debt

#3122 migrate onedrive using prefix collection
  src/cli/backup/backup.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/restore/exchange_e2e_test.go
  src/internal/common/idname.go
  src/internal/common/idname/idname.go
  src/internal/common/idname/mock/mock.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/collections.go
  src/internal/connector/graph/collections_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mock/connector.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/data_collections_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/data/data_collection.go
  src/internal/data/data_collection_test.go
  src/internal/kopia/model_store.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/path_encoder.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/model/model.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/common.go
  src/internal/operations/help_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore_test.go
  src/internal/version/backup.go
  src/pkg/backup/backup.go
  src/pkg/backup/details/mock/location_ider.go
  src/pkg/control/options.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/selectors/selectors.go
  src/pkg/services/m365/m365.go
Labels: enhancement, mergequeue, backup

#3182 Add concurrency limiter middleware package
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph/concurrency_limiter.go
  src/internal/connector/graph/concurrency_limiter_test.go
  src/internal/connector/graph/service.go
Labels: mergequeue, msgraph

#3189 fixup mailbox info
  src/internal/connector/discovery/discovery_test.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/onedrive/drive_test.go
  src/pkg/services/m365/api/users.go
Labels: bug, mergequeue-priority, msgraph

#3203 Add --disable-concurrency-limiter cli flag
  src/cli/backup/exchange.go
  src/cli/options/options.go
  src/cli/options/options_test.go
  src/internal/connector/exchange/data_collections.go
  src/pkg/control/options.go
Labels: mergequeue, cli

#3208 Show names in OneDrive restore progressbar
  src/internal/connector/onedrive/restore.go
Labels: mergequeue

#3214 Expose ErrResourceOwnerNotFound in err package
  src/pkg/errs/err.go
  src/pkg/errs/errs_test.go
Labels: mergequeue, supportability

#3213 CLI connect refactor
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
  src/cli/utils/utils_test.go
Labels: mergequeue, supportability, tech-debt

#3206 ditch userInfo middle struct
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/utils/users.go
  src/cmd/factory/impl/common.go
  src/internal/connector/discovery/discovery_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: bug, mergequeue, msgraph

#3205 use nanosecond folders for testing
  src/internal/connector/exchange/restore_test.go
  src/internal/operations/restore_test.go
Labels: bug, mergequeue, tests

#3201 errant cleanups before incremental support
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph/metadata/metadata.go
  src/internal/connector/graph/metadata/metadata_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/help_test.go
  src/internal/operations/restore_test.go
Labels: mergequeue, tech-debt, sharepoint

#3221 Add parent path information to malware detected items
  CHANGELOG.md
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/pkg/fault/item.go
Labels: mergequeue

#3230 Don't try to fetch backup version if no compete backups available
  src/internal/operations/backup.go
Labels: bug, mergequeue

#3233 Helper method to expose internal errors associated with a public error category
  src/pkg/errs/err.go
  src/pkg/errs/errs_test.go
Labels: mergequeue

#3220 cache created folders when restoring drive items
  CHANGELOG.md
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/folder_cache.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/restore.go
Labels: bug, restore, mergequeue-priority, onedrive

#3231 documentation update for new permission
  website/docs/setup/m365-access.md
Labels: mergequeue

#3237 don't give log-file prepopulate flag a default
  .github/workflows/sanity-test.yaml
  CHANGELOG.md
  src/pkg/logger/logger.go
Labels: bug, mergequeue-priority, cli

#3250 Don't go for snapshot deletion in case of empty backup
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/store/mock/wrapper.go
Labels: mergequeue

#3242 Return SharePoint exclude information
  src/internal/connector/sharepoint/data_collections.go
Labels: bug, mergequeue-priority, backup, sharepoint

#3234 minor errs cleanup
  src/internal/connector/discovery/discovery.go
  src/pkg/errs/errs.go
  src/pkg/errs/errs_test.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, tech-debt

#3236 Don't use RepoRef in selector reduction
  src/cli/utils/testdata/opts.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue, supportability

#3223 Allow overriding the default username/hostname in kopia
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/control/options.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
Labels: enhancement, mergequeue, kopia

#3253 Update golangci-lint to 1.52.2
  .github/workflows/ci.yml
  src/Makefile
  src/internal/common/crash/crash.go
Labels: mergequeue, workflows, supportability, github_actions

#3251 Fixup archive upload for sanity test
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue, workflows, supportability, github_actions

#3257 Introduce a UserCompatNoInfo call
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue-priority

#3254 Type out path instead of using env
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue, workflows, github_actions

#3259 Always attempt to upload test log
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue-priority, workflows, supportability, github_actions

#3263 Check for new and older content URLs
  src/internal/connector/onedrive/item.go
Labels: bug, mergequeue-priority, backup, onedrive, sharepoint

#3260 Only run on schedule, not merges
  .github/workflows/nightly_test.yml
Labels: bug, mergequeue, workflows, github_actions

#3219 Fix progress folder display for Exchange
  CHANGELOG.md
  src/internal/connector/exchange/exchange_data_collection.go
Labels: bug, mergequeue, backup, exchange

#3227 create onedrive custom drive
  .github/workflows/sanity-test.yaml
  src/cmd/factory/factory.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/sanity_test/sanity_tests.go
Labels: mergequeue
