Repository alcionai/corso, pull requests merged in 2023-01, with the labels that each got.

#2017 GC: Sharepoint: List: Delete feature added
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/list_test.go
Labels: mergequeue

#1979 add move folder delta test
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_restore.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#1981 add folder muation tests
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#2001 remove optionIdentifier
  src/cmd/getM365/getItem.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/optionidentifier_string.go
  src/internal/connector/exchange/query_options.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
Labels: mergequeue, tech-debt

#2011 GC: Restore: SharePoint: ListItem modification on upload
  src/internal/connector/support/m365Transform.go
Labels: enhancement, restore, mergequeue

#1982 add item mutation tests
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#2002 remove exchangeService for graph.Service
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/service_functions.go
Labels: mergequeue, tech-debt

#2004 switch trivial for tech-debt
  .github/pull_request_template.md
Labels: mergequeue, tech-debt

#1889 split selectors on discrete resource owners
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
Labels: enhancement, mergequeue

#2005 No tester errors 2
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/sharepoint_integration_test.go
  src/cli/config/config_test.go
  src/cli/repo/s3_integration_test.go
  src/cli/restore/exchange_integration_test.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/list_test.go
  src/internal/events/events_test.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/streamstore_test.go
  src/internal/tester/envvars.go
  src/internal/tester/envvars_test.go
  src/internal/tester/integration_runners.go
  src/pkg/repository/repository_load_test.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, tech-debt

#1986 remove 0-item progress bars
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/observe/observe.go
  src/internal/operations/backup.go
Labels: mergequeue

#1983 tetst fixes and touchups
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#2003 first pass migrate graph api to subfolder
  src/cmd/getM365/getItem.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_service_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_query.go
  src/internal/connector/exchange/service_restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/tester/integration_runners.go
Labels: mergequeue, tests

#2021 Reduce parallelism of goreleaser to 1
  .github/workflows/ci.yml
Labels: mergequeue

#2008 methodize all api funcs to the Client
  src/cmd/factory/exchange.go
  src/cmd/factory/factory.go
  src/cmd/getM365/getItem.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
Labels: mergequeue, tests

#2019 Mock: SharePoint: List objects expansion
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/sharepoint/collection_test.go
Labels: mergequeue, tests

#2030 Allow incremental backups for multiple data categories if some metadata is missing
  src/internal/operations/backup.go
Labels: bug, mergequeue

#1890 use selector owners, not scope owners
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository_test.go
  src/pkg/selectors/selectors.go
Labels: enhancement, mergequeue

#2009 migrate resolver iterators
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/cache_container.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
Labels: mergequeue, tests

#2032 GC: Framework to use adapter's serialization writer.
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
Labels: mergequeue, backup, tech-debt

#2033 Fix --users "*' not finding user in tenant
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/pkg/services/m365/m365.go
Labels: bug, mergequeue

#1891 Match resource owners at top of reduce
  CHANGELOG.md
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange.go
  src/cli/utils/exchange_test.go
  src/cli/utils/onedrive.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors_test.go
Labels: enhancement, mergequeue

#1964 GC: Restore: SharePoint List Workflow
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/m365Transform.go
Labels: restore, mergequeue

#2010 transition api methods to interfaces
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#1895 remove resource owners from scopes
  src/cli/backup/exchange.go
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_integration_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_integration_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange.go
  src/cli/utils/exchange_test.go
  src/cli/utils/onedrive.go
  src/cli/utils/sharepoint.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/repository_load_test.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue

#2046 [Bug Fix] GC: Backup: Onedrive: Context timeout during drive retrieval fix
  src/internal/connector/onedrive/drive.go
Labels: bug, mergequeue

#2042 use stringslice for users in onedrive
  CHANGELOG.md
  src/cli/backup/onedrive.go
Labels: bug, mergequeue, cli

#2020 test service_iterators with mocks
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/tester/resource_owners.go
Labels: mergequeue, tests, releaseblocker

#2049 full backup if prev snapshots have no details
  src/internal/kopia/snapshot_manager.go
  src/internal/operations/backup.go
Labels: mergequeue, backup

#2050 Only make incremental backup if Reason:base is 1:1
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue

#2051 Invert incremental flags, default to incremental
  CHANGELOG.md
  src/cli/backup/exchange.go
  src/cli/options/options.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/pkg/control/options.go
Labels: mergequeue, backup, cli

#2060 Run staticcheck on make lint
  src/Makefile
Labels: mergequeue

#2054 Add a common prefix to test storage prefixes
  src/internal/tester/storage.go
Labels: mergequeue, tests, supportability

#2063 protect against missing backups in manifests
  src/internal/operations/backup.go
Labels: bug, mergequeue, backup

#2034 remove selector printable, list discreteOwner
  src/cli/utils/exchange_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/repository.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  website/docs/quickstart.md
Labels: mergequeue, tech-debt

#2055 Don't use OwnersCats struct
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue

#2083 Prevent config-file default repeating in help
  src/cli/config/config.go
Labels: mergequeue

#2088 Patch: Direct Import of Minimal Beta packages for Feature Development
  src/go.mod
  src/go.sum
  src/internal/connector/sharepoint/site_page.go
  src/internal/connector/sharepoint/site_pageable.go
Labels: backup

#2066 details and restore exit on missing backup
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange.go
  src/cli/utils/onedrive.go
Labels: restore, mergequeue, cli

#2085 Backup Details: Onedrive details expanded
  src/internal/connector/onedrive/item.go
  src/pkg/backup/details/details.go
Labels: mergequeue, supportability

#2089 Fix unit tests that fail when not running with env vars
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/service_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/tester/account.go
Labels: bug, mergequeue, tests

#2087 Refactor the Reason struct and how tags for lookups are generated
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
Labels: mergequeue

#1906 refactors the exchange fetchIDs iters
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
Labels: mergequeue, tech-debt

#2036 remove DiscreteScopes() from selectors
  src/internal/connector/exchange/data_collections.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/backup/details/details.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, tech-debt

#2092 Fix compile error in factory script
  src/cmd/factory/factory.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/cmd/factory/impl/onedrive.go
Labels: mergequeue

#2097 remove design/cli.md; conflicts with docs
  design/cli.md
Labels: mergequeue

#2105 Update list of skus that license onedrive
  CHANGELOG.md
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2081 Support specifying an AWS credential provider
  src/go.mod
  src/go.sum
  src/internal/kopia/s3.go
  src/pkg/repository/repository_test.go
  src/pkg/storage/storage.go
Labels: mergequeue

#2090 CLI: Adds to the displayable headers for OneDrive and SharePoint.
  src/internal/connector/onedrive/item.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue, supportability

#2093 Remove dead code from refactoring Resource struct
  src/internal/kopia/snapshot_manager.go
Labels: mergequeue

#2109 Path: Add category --> Pages.
  src/pkg/path/categorytype_string.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: mergequeue

#2118 Dedupe collection items for OneDrive
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: mergequeue

#2119 Don't set updated in backup details for cached items
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue

#2126 Re-Enable Kopia-assisted incrementals for OneDrive
  src/go.mod
  src/go.sum
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/operations/backup.go
  src/pkg/backup/details/details.go
Labels: mergequeue

#2127 Update CHANGELOG for v0.1.0 release
  CHANGELOG.md
Labels: mergequeue

#2132 Disable kopia incrementals for OneDrive
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: mergequeue

#2136 Update to fork of kopia with patch
  src/go.mod
  src/go.sum
Labels: bug, mergequeue

#2006 new blog post on backing up with Corso on your coffee break
  website/blog/2023-1-4-backups-on-your-coffee-break.md
  website/blog/images/coffee_break.jpg
Labels: mergequeue

#2134 Document ability to download latest binary artifacts from CI job
  .github/workflows/ci.yml
  website/docs/developers/build.md
Labels: mergequeue

#2116 Dedupe collection item IDs prior to fetching item data
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue

#2082 Write logs to disk by default
  CHANGELOG.md
  src/cli/cli.go
  src/pkg/logger/logger.go
  src/pkg/logger/logpath_darwin.go
  src/pkg/logger/logpath_windows.go
  src/pkg/logger/logpath_xdg.go
  website/docs/setup/configuration.md
  website/docs/support/bugs-and-features.md
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#2141 Update log file docs
  .github/ISSUE_TEMPLATE/BUG-REPORT.yaml
  website/docs/setup/configuration.md
Labels: mergequeue

#2131 Update changelog header for v0.1.0 release
  CHANGELOG.md
Labels: mergequeue

#2073 log observed messages
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/kopia/upload.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: mergequeue, supportability

#2142 Switch to "delete wins" merge strategy for Exchange IDs
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue

#2140 Fix ci test cleanup script
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#2150 add item fetching and serialization to api
  src/cmd/getM365/getItem.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/contacts_test.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/events_test.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/exchange/contact.go
  src/internal/connector/exchange/event.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/message.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
Labels: mergequeue, tech-debt

#2095 populate colls in manifest test
  src/internal/operations/backup_test.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, tests

#2144 Begin persisting OneDrive/SharePoint library metdata
  src/internal/connector/data_collections_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue, onedrive

#2091 migrate, test manifest+meta producer
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, tests

#2151 Add logging for bases in incremental backups
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
Labels: mergequeue, supportability

#2153 Add tags to checkpoints in kopia
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/wrapper.go
Labels: mergequeue

#2156 Check whether the user has an exchange mailbox
  CHANGELOG.md
  src/internal/connector/data_collections.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/graph/errors.go
Labels: mergequeue

#2048 Middleware: Context timeout expansion
  src/internal/connector/graph/errors.go
Labels: mergequeue

#2155 extra loggng and error wraps
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/support/errors.go
Labels: mergequeue, supportability

#2164 Minor snapshot lookup refactor and logging addition
  src/internal/kopia/snapshot_manager.go
Labels: mergequeue, supportability

#2165 Use same tags for checkpoints and snapshots
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/wrapper.go
Labels: mergequeue

#2166 Delete details snapshot on backup delete
  src/pkg/repository/repository.go
Labels: bug, mergequeue

#2154 use delta queries for calendar events
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
Labels: enhancement, mergequeue

#2111 Selectors: Add selectors for new sharepoint category
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue

#2098 GC: Backup: Sharepoint libraries to omit site drive.
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue, backup

#2114 GC: Restore: SharePoint add case for Page Category in Workflow.
  src/internal/connector/sharepoint/restore.go
Labels: bug, restore, mergequeue

#2084 MetaData: Pages Backup Info Support
  src/internal/connector/sharepoint/listInfo_test.go
  src/internal/connector/sharepoint/pageInfo.go
  src/internal/connector/sharepoint/pageInfo_test.go
  src/internal/connector/sharepoint/site_page.go
  src/internal/connector/sharepoint/site_pageable.go
Labels: restore, mergequeue, backup, supportability

#2161 Handle ResourceNotFound error when fetching drive
  CHANGELOG.md
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2172 set new CI test user default
  src/internal/tester/config.go
Labels: mergequeue

#2162 standardizes the calendar resolver interface
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_restore.go
Labels: mergequeue, tech-debt

#2189 GC: Backup: [FIX]Embedded image requires download
  CHANGELOG.md
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
Labels: mergequeue, backup

#2201 Use mutex when appending to error
  src/internal/connector/exchange/exchange_data_collection.go
Labels: bug, mergequeue

#2202 Check for and ignore item not found errors
  src/internal/connector/exchange/exchange_data_collection.go
Labels: mergequeue

#2195 Record graph error
  src/internal/connector/exchange/exchange_data_collection.go
Labels: bug, mergequeue, supportability

#2192 Update OneDrive metadata with folder deletions
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue

#2199 Fail operation if we failed to fetch item data
  src/internal/operations/backup.go
Labels: bug, mergequeue-priority

#2193 Update OneDrive metadata with folder moves
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue

#2188 discovery api, filter guest and external users
  CHANGELOG.md
  src/internal/connector/data_collections.go
  src/internal/connector/discovery/api/api.go
  src/internal/connector/discovery/api/users.go
  src/internal/connector/discovery/api/users_test.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/pkg/services/m365/m365.go
Labels: enhancement, mergequeue

#2210 Move to wow.js fork
  website/package-lock.json
  website/package.json
  website/src/components/parts/KeyLoveFAQ.js
Labels: mergequeue

#2191 CLI: Updates for Exchange Help
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
Labels: mergequeue

#2206 Report errors when building details
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
Labels: bug, mergequeue

#2213 CLI: Backup: SharePoint: Pages Enable
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
Labels: mergequeue, backup, cli

#2232 link directly to getting started directions
  README.md
Labels: mergequeue

#2233 Don't retry if an item was not found
  src/internal/connector/exchange/exchange_data_collection.go
Labels: bug, mergequeue-priority

#2167 Issue 2022 eventincr
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#2248 return gc stats errors in backup
  src/internal/connector/support/status.go
  src/internal/operations/backup.go
Labels: bug, mergequeue

#2222 [BUG FIX]: CLI: Details: Sharepoint
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, backup, cli

#2143 Add a set of items that will be excluded from base directories during backup
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
Labels: enhancement, mergequeue, onedrive

#2250 Add deleted files to OneDrive excluded file list
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: enhancement, mergequeue, backup, onedrive

#2260 Remove duplicate string->path.CategoryType helper function
  src/cmd/getM365/getItem.go
  src/internal/connector/graph/service_helper.go
  src/pkg/path/resource_path.go
  src/pkg/path/service_category_test.go
Labels: mergequeue, supportability

#2214 adds clues package to begin structured logging
  src/go.mod
  src/go.sum
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue, tech-debt

#2236 Add fault pkg and errors struct
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
Labels: mergequeue, supportability, tech-debt

#2265 Fix case comparison in switch cases
  src/pkg/path/resource_path.go
  src/pkg/path/service_category_test.go
Labels: bug, mergequeue-priority

#2266 add itemClient for re-usable od item downloads
  src/cli/backup/sharepoint.go
  src/cmd/factory/impl/common.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/operation.go
  src/pkg/services/m365/m365.go
Labels: bug, mergequeue

#2269 Print Corso version on one line
  src/cli/cli.go
Labels: mergequeue, backup

#2275 Remove OneDrive license GUID check
  CHANGELOG.md
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2274 Fix direct GH docs edit link
  website/docusaurus.config.js
Labels: mergequeue

#2276 Re-use client for OneDrive item downloads
  src/cli/backup/sharepoint.go
  src/cmd/factory/impl/common.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/operation.go
  src/pkg/services/m365/m365.go
Labels: mergequeue

#2268 wrap item get in lazy reader
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: bug, mergequeue, backup

#2285 scrub pii from observe logs
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: mergequeue, supportability

#2283 re-fetch file download url after expiration
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue, backup

#2281 Bulk up kopia wrapper error checking in BackupOp
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
Labels: bug, mergequeue, backup

#2286 clean up graph errors
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/errors.go
  src/internal/connector/onedrive/collection.go
Labels: mergequeue, tech-debt

#2289 Reword docs about latest binary artifact downloads
  website/docs/developers/build.md
Labels: mergequeue

#2182 GC: Backup: SharePoint: Test Fetch/Get Functions
  src/internal/connector/sharepoint/site_page_test.go
Labels: backup, tests

#2244 Wire kopia exclude list up to BackupOp
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup, onedrive

#2288 update from Google Analytics to Google Tag Manager
  website/docusaurus.config.js
Labels: mergequeue

#2301 quick graph client refactor
  src/cli/backup/sharepoint.go
  src/cmd/factory/impl/common.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_helper.go
  src/internal/connector/graph/service_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/operation.go
  src/pkg/services/m365/m365.go
Labels: mergequeue, tech-debt

#2304 Hide sharepoint details command
  src/cli/backup/sharepoint.go
Labels: mergequeue

#2307 Warning in the help messages for pre-release hidden commands
  src/cli/backup/sharepoint.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
Labels: mergequeue

#2302 refactor exchange attachment downloads
  CHANGELOG.md
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/service.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
Labels: enhancement, mergequeue, backup

#2303 Upgrade to Docusaurus 2.3.0
  website/package-lock.json
  website/package.json
Labels: mergequeue

#2306 Use mocks to test getting drive info from Graph API
  CHANGELOG.md
  src/cmd/purge/purge.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue, onedrive, tests, supportability

#2308 Create helper functions/interfaces to retrieve next and delta links
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/graph/api/api.go
  src/internal/connector/graph/api/api_test.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
Labels: mergequeue, supportability

#2305 add getItem unit with retries
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_message.go
Labels: mergequeue, tests

#2311 Remove new line check for new version
  .github/workflows/ci.yml
Labels: mergequeue

#2312 Changelog update post release
  CHANGELOG.md
Labels: mergequeue

#2316 BUG Fix: Restore: Operations
  src/internal/operations/restore.go
Labels: restore, mergequeue

#2315 Add guidance on using Corso repos
  website/docs/setup/repos.md
Labels: mergequeue

#2247 remove operation "started"
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
Labels: mergequeue, tech-debt

#2246 standardize deleteContainer func in exch api
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/restore_test.go
  src/internal/kopia/upload.go
  src/internal/operations/backup_integration_test.go
  src/internal/tester/storage.go
Labels: mergequeue, tech-debt

#2245 Wire up GraphConnector <-> BackupOp item exclude list
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/operations/backup.go
Labels: enhancement, mergequeue, backup, onedrive

#2317 enable onedrive backup for single user
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, tests

#1756 Bump slash-command-dispatch and avoid running unverified commit in ok-to-test
  .github/workflows/ci.yml
  .github/workflows/ok-to-test.yml
Labels: mergequeue

#2313 Add docs page for fault-tolerance
  CHANGELOG.md
  website/docs/setup/fault-tolerance.md
  website/sidebars.js
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#2331 add version to clues, log cli command and flags
  src/cli/cli.go
  src/cli/config/config.go
  src/go.mod
  src/internal/version/version.go
  src/pkg/logger/logger.go
Labels: mergequeue, supportability, tech-debt

#2298 GC: Add Service to `graph/betasdk` package
  src/internal/connector/discovery/api/beta_service.go
  src/internal/connector/discovery/api/beta_service_test.go
  src/internal/connector/graph/betasdk/beta_client.go
Labels: enhancement, mergequeue

#2237 store errors in operation
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, supportability, tech-debt

#2328 Retry handling for delta queries in Exchange
  CHANGELOG.md
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue

#2239 update operation/backup errs
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/mock/mock.go
Labels: mergequeue, supportability, tech-debt

#2263 Deserialize OneDrive metadata during backup
  src/internal/connector/data_collections.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/sharepoint/data_collections.go
Labels: enhancement, mergequeue, backup, onedrive
