Repository alcionai/corso, pull requests merged in 2023-10, with the labels that each got.

#4344 Backup/Restore/Export multiples sites in Groups
  CHANGELOG.md
  src/cli/flags/testdata/backup_list.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/internal/m365/restore.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/groups/restore_test.go
  src/internal/operations/test/onedrive_test.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/sites.go
Labels: restore, mergequeue, backup, export, teams & groups

#4394 Return tombstone instead of canUsePreviousBackup
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/service/groups/backup.go
Labels: mergequeue, backup, teams & groups

#4412 Revert "move drive pagers to pager pattern (#4316)"
  src/cmd/purge/scripts/onedrivePurge.ps1
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/fault/fault.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/delta.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue, revert

#4420 provide expected repo cfg in e2e tests
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/helpers_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/s3_e2e_test.go
Labels: bug, mergequeue, cli, tests

#4428 export path string to service type
  src/pkg/path/category_type.go
  src/pkg/path/service_category_test.go
  src/pkg/path/service_type.go
  src/pkg/path/servicetype_string.go
Labels: enhancement, mergequeue-priority

#4424 Use local fs for non-retention tests
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue, tests, perf, kopia

#4406 update Kopia password
  src/internal/kopia/conn.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: mergequeue

#4437 Temporary removal of OneNote file size check
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
Labels: mergequeue

#4436 hand resource down to drive controller
  src/cmd/factory/impl/common.go
  src/internal/common/idname/idname.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handler_utils.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/internal/operations/help_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/internal/operations/test/helper_test.go
  src/pkg/repository/backups.go
Labels: bug, restore, mergequeue, teams & groups

#4449 Temporarily disable restoring to alternate resource for Groups
  CHANGELOG.md
  src/cli/flags/restore_config.go
  src/cli/restore/exchange.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/internal/operations/test/group_test.go
  website/docs/support/known-issues.md
Labels: restore, mergequeue, teams & groups

#4452 Update CHANGELOG.md for v0.14.0
  CHANGELOG.md
Labels: mergequeue-priority, mergequeue

#4417 Add logic to check if the JWT token has expired
  src/go.mod
  src/internal/common/jwt/jwt.go
  src/internal/common/jwt/jwt_test.go
  src/internal/common/url.go
  src/internal/common/url_test.go
Labels: mergequeue, onedrive, sharepoint, msgraph

#4419 Skip graph call if the download url has expired
  CHANGELOG.md
  src/internal/common/url.go
  src/internal/m365/collection/drive/item.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
Labels: mergequeue, onedrive, sharepoint, msgraph

#4327 Add benchmark for backup/hierarchy merging
  src/internal/kopia/wrapper_scale_test.go
Labels: mergequeue, tests, perf, kopia

#4450 Uncomment exchange e2e tests
  src/internal/operations/test/exchange_test.go
Labels: bug, mergequeue, tests, exchange

#4421 Rename generic item structs and functions
  src/internal/data/item.go
  src/internal/data/item_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/graph/metadata_collection.go
  src/internal/m365/graph/metadata_collection_test.go
  src/internal/m365/service/sharepoint/api/pages_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup, tech-debt

#4456 Revert "Revert "move drive pagers to pager pattern (#4316)" (#4412)"
  src/cmd/purge/scripts/onedrivePurge.ps1
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/fault/fault.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/delta.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue

#4434 adds purely informational alerts to the fault bus
  src/cli/backup/backup.go
  src/cli/flags/backup_list.go
  src/cli/flags/options.go
  src/cli/flags/testdata/backup_list.go
  src/internal/operations/helpers.go
  src/pkg/fault/fault.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
Labels: enhancement, mergequeue

#4435 remove local bus struct
  src/pkg/fault/alert.go
  src/pkg/fault/alert_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
  src/pkg/fault/skipped.go
  src/pkg/fault/skipped_test.go
Labels: mergequeue, tech-debt

#4442 remove start events from operations
  src/internal/events/events.go
  src/internal/operations/backup.go
  src/internal/operations/export.go
  src/internal/operations/maintenance.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/restore_helper_test.go
Labels: mergequeue

#4463 Disable contact category checks in integration tests
  src/internal/m365/helper_test.go
Labels: mergequeue-priority, tests, msgraph

#4393 Push item download requests through drive rate limiter
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/graph/concurrency_middleware.go
  src/internal/m365/graph/http_wrapper.go
  src/pkg/services/m365/api/item_pager.go
Labels: mergequeue, msgraph

#4465 catch and sentinel resource locked error case
  CHANGELOG.md
  src/internal/m365/controller.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/internal/m365/service/onedrive/enabled.go
  src/internal/m365/service/onedrive/enabled_test.go
  src/pkg/errs/errs.go
  src/pkg/errs/errs_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
Labels: bug, mergequeue, msgraph

#4460 Allow delta enum callers to specify $select properties
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
Labels: bug, mergequeue, perf

#4472 modify onenote skip, clues add collection scope
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collections.go
  src/pkg/backup/backup.go
  src/pkg/fault/skipped.go
Labels: mergequeue, supportability

#4461 Add stats to export operations
  CHANGELOG.md
  src/cli/export/export.go
  src/internal/data/metrics.go
  src/internal/m365/collection/drive/export.go
  src/internal/m365/collection/groups/export.go
  src/internal/m365/collection/groups/export_test.go
  src/internal/m365/export.go
  src/internal/m365/mock/connector.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
  src/internal/operations/export.go
  src/internal/operations/inject/inject.go
  src/pkg/export/export.go
Labels: mergequeue, export

#4480 refer to env instead of secrets in ci
  .github/workflows/longevity_test.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue-priority, ci

#4477 Refactor drive handler logic
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/handler_utils.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
Labels: mergequeue, onedrive, supportability, tech-debt, sharepoint, teams & groups

#4479 Rename drive handlers to better match uses
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/group_handler_test.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/drive/site_handler_test.go
  src/internal/m365/collection/drive/user_drive_handler.go
  src/internal/m365/collection/drive/user_drive_handler_test.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/restore.go
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: mergequeue, onedrive, supportability, tech-debt, sharepoint

#4468 Move Reasoner implementation to identity package
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/cleanup_backups_test.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_scale_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/service/groups/backup_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/backup/identity/identity.go
Labels: mergequeue, backup, supportability

#4469 Consolidate Reasoner implementations
  src/pkg/selectors/reasons.go
Labels: mergequeue, backup, supportability

#4416 apply channels and streaming to drive collections
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/fault/skipped.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/item_pager.go
Labels: onedrive, tech-debt

#4488 fix failing item replace test
  src/pkg/services/m365/api/drive_test.go
Labels: bug, mergequeue-priority, tests

#4486 ensure api layer provides non-empty modtime
  CHANGELOG.md
  src/internal/common/dttm/dttm.go
  src/internal/common/dttm/dttm_test.go
  src/internal/common/ptr/pointer.go
  src/internal/common/ptr/pointer_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
Labels: bug, mergequeue, msgraph

#4489 nil pointer protection in populateResource
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
Labels: bug, mergequeue

#4485 Fail backups if we see an item has a zero mod time
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
Labels: bug, blocked, mergequeue, backup

#4493 fix message size report
  CHANGELOG.md
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: bug, mergequeue-priority, backup, exchange

#4481 filter out system messages
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
Labels: mergequeue, tech-debt, teams & groups

#4427 add groups to sanity tests, plus some renaming and cleanup
  .github/actions/backup-restore-test/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/common/common.go
  src/cmd/sanity_test/driveish/export.go
  src/cmd/sanity_test/driveish/restore.go
  src/cmd/sanity_test/export/groups.go
  src/cmd/sanity_test/restore/exchange.go
Labels: tests, teams & groups

#4490 Log the categories participating in an operation
  src/internal/operations/backup.go
  src/internal/operations/export.go
  src/internal/operations/restore.go
  src/pkg/selectors/selectors.go
Labels: mergequeue, supportability, qol

#4425 refactor drive restore & export to use sanitree
  .github/actions/backup-restore-test/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/common/common.go
  src/cmd/sanity_test/common/filepath.go
  src/cmd/sanity_test/common/sanitree.go
  src/cmd/sanity_test/common/utils.go
  src/cmd/sanity_test/driveish/driveish.go
  src/cmd/sanity_test/driveish/export.go
  src/cmd/sanity_test/driveish/restore.go
  src/cmd/sanity_test/export/groups.go
  src/cmd/sanity_test/export/onedrive.go
  src/cmd/sanity_test/export/sharepoint.go
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/restore/groups.go
  src/cmd/sanity_test/restore/onedrive.go
  src/cmd/sanity_test/restore/sharepoint.go
  src/cmd/sanity_test/sanity_tests.go
  src/internal/tester/tconfig/protected_resources.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/client.go
Labels: mergequeue-priority, tests

#4499 add extra catches for resource locked
  src/pkg/errs/errs.go
  src/pkg/errs/errs_test.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, tech-debt

#4414 iterate pager results with channels
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/drive/user_drive_handler.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/fault/skipped.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue-priority, tech-debt, msgraph

#4504 Update golang in build script
  build/build.sh
Labels: mergequeue

#4397 Update kopia password
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/export/onedrive_test.go
  src/cli/flags/repo.go
  src/cli/flags/testdata/repo.go
  src/cli/repo/repo.go
  src/cli/repo/repo_test.go
  src/cli/utils/flags_test.go
Labels: mergequeue

#4502 fix group site url ref in sanity yml
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue, tests, teams & groups

#4496 Enforce site filter for Groups restore
  CHANGELOG.md
  src/cli/backup/sharepoint.go
  src/cli/export/groups.go
  src/cli/flags/sharepoint.go
  src/cli/flags/testdata/flags.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/utils/groups.go
  src/cli/utils/groups_test.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
Labels: restore, mergequeue, cli, export, teams & groups

#4508 Fix sanity test backup arg for Groups
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/common/common.go
  src/cmd/sanity_test/export/groups.go
  src/cmd/sanity_test/restore/groups.go
  src/internal/tester/tconfig/config.go
  src/internal/tester/tconfig/protected_resources.go
Labels: mergequeue, tests, teams & groups

#4516 Include docs on adding GC debug logs
  website/docs/support/bugs-and-features.md
Labels: mergequeue, azure

#4517 Enhance OneNote skip check
  CHANGELOG.md
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
Labels: mergequeue

#4510 Check if user provided webURL before trying to access it
  src/cli/utils/groups.go
Labels: mergequeue, teams & groups

#4521 Don't update prev delta url
  src/internal/m365/collection/drive/url_cache.go
Labels: bug, mergequeue

#4459 Add tests which were rolled back with 4456
  src/internal/m365/collection/drive/item_test.go
Labels: bug, mergequeue

#4498 replace col scope with bool
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
Labels: bug, mergequeue, backup, onedrive

#4482 use count bus in kopia backups
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/merge_collection_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_scale_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/stats/stats.go
  src/internal/streamstore/streamstore.go
  src/pkg/count/count.go
  src/pkg/count/keys.go
Labels: mergequeue, backup, tech-debt

#4532 expose sitesInGroup to sdk consumers
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/groups_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/sites.go
  src/pkg/services/m365/users.go
Labels: mergequeue, msgraph, teams & groups

#4531 rename group handler interface
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/collection/groups/mock/getter.go
Labels: mergequeue, tech-debt, teams & groups

#4534 Adding email fallback to Groups getByID api
  src/internal/tester/tconfig/config.go
  src/internal/tester/tconfig/protected_resources.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/groups_test.go
  src/pkg/services/m365/sites.go
Labels: mergequeue

#4501 mark complete subtrees as packages
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/service/sharepoint/backup_test.go
Labels: bug, mergequeue, backup, onedrive

#4478 extract container transforms from the api layer
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/contacts_container_cache.go
  src/internal/m365/collection/exchange/container_resolver.go
  src/internal/m365/collection/exchange/events_container_cache.go
  src/internal/m365/collection/exchange/mail_container_cache.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue, tech-debt, msgraph

#4402 Unify backup bases fields
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/mock_backup_base.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, supportability, tech-debt

#4535 Minor url cache test enhancement
  src/internal/m365/collection/drive/url_cache_test.go
Labels: mergequeue, tests

#4470 Builder pattern for BackupBase struct
  src/internal/kopia/mock_backup_base.go
Labels: mergequeue, backup, tests, tech-debt, kopia

#4538 [Bugfix] Fixing getting owner email
  src/pkg/services/m365/api/mock/site.go
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/sites.go
  src/pkg/services/m365/sites_test.go
Labels: bug, mergequeue, msgraph, teams & groups

#4544 fix api/mock circular ref
  src/cli/backup/helpers_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/collection/drive/site_handler.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/drive/user_drive_handler.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/handlers.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mock/mail.go
  src/pkg/services/m365/api/mock/pager.go
  src/pkg/services/m365/api/pagers/pagers.go
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, tech-debt, msgraph

#4541 Remove site name validation check
  CHANGELOG.md
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
Labels: mergequeue, backup, sharepoint

#4547 Unexport functions and fields in api package
  src/pkg/services/m365/api/access_test.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/channels_test.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/contacts_test.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/item_serialization_test.go
  src/pkg/services/m365/api/lists_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager_test.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
  src/pkg/services/m365/sites_test.go
Labels: mergequeue, supportability

#4548 Refactor site exclusion logic
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
Labels: mergequeue, supportability

#4554 Fix export stalling when run with progressbars
  CHANGELOG.md
  src/cli/export/export.go
Labels: mergequeue, cli

#4539 expose additional channel metadata
  CHANGELOG.md
  src/internal/m365/collection/groups/export.go
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/groups_test.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/channels_test.go
Labels: enhancement, mergequeue, teams & groups

#4471 Cleanup API for BackupBases
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/mock_backup_base.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_scale_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/backup.go
  src/internal/m365/mock/connector.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/inject/mock/inject.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/test/helper_test.go
Labels: mergequeue, backup, tech-debt, kopia

#4500 Remove Controller stats for export
  src/internal/operations/export.go
  src/internal/operations/export_test.go
Labels: mergequeue, supportability, export

#4556 make channel message html human readable
  src/go.mod
  src/go.sum
  src/internal/m365/collection/groups/export.go
  src/pkg/backup/details/groups.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_test.go
Labels: enhancement, mergequeue-priority, mergequeue, teams & groups

#4558 add real world test examples
  src/pkg/services/m365/api/channels_test.go
Labels: mergequeue, tests

#4557 Helper function to add common backup flags
  src/cli/backup/exchange.go
  src/cli/backup/groups.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/flags/backup_create.go
Labels: mergequeue, backup, onedrive, cli, exchange, sharepoint, teams & groups

#4563 Add timeouts to CI steps
  .github/workflows/ci.yml
  .github/workflows/longevity_test.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue, ci

#4566 include assist bases in min backup version
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/operations/backup.go
Labels: enhancement, backup

#4567 Check for no backup version
  src/internal/operations/backup.go
Labels: backup, perf, teams & groups

#4562 Groups version bump tests
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: backup, tests, teams & groups

#4568 Add tests on assist bases for drive-backed services for groups bump
  src/internal/operations/test/group_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: backup, tests, teams & groups

#4561 Groups version bump
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/m365/onedrive_test.go
  src/internal/m365/service/onedrive/restore_test.go
  src/internal/m365/service/onedrive/stub/stub.go
  src/internal/operations/backup.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/internal/version/backup.go
Labels: mergequeue, backup, teams & groups

#4576 Add GODEBUG to memory debug commands
  website/docs/support/bugs-and-features.md
Labels: mergequeue

#4574 Go back to old way of testing
  src/internal/m365/onedrive_test.go
Labels: mergequeue, onedrive, tests, sharepoint

#4533 introduce debug commands
  src/cli/debug/debug.go
  src/cli/debug/exchange.go
  src/cli/debug/exchange_test.go
  src/cli/debug/groups.go
  src/cli/debug/groups_test.go
  src/cli/debug/onedrive.go
  src/cli/debug/onedrive_test.go
  src/cli/debug/sharepoint.go
  src/cli/debug/sharepoint_test.go
  src/cli/flags/repo.go
  src/cli/utils/debug.go
  src/cli/utils/utils.go
Labels: mergequeue, cli

#4577 Teams notification action
  .github/actions/slack-message/action.yml
  .github/actions/teams-message/action.yml
  .github/workflows/ci_test_cleanup.yml
  .github/workflows/longevity_test.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  .github/workflows/testnotification.yml
Labels: mergequeue

#4507 add changelog for repo update-passphrase command
  CHANGELOG.md
  website/sidebars.js
Labels: mergequeue

#4590 Update CHANGELOG.md for v0.15.0
  CHANGELOG.md
Labels: mergequeue

#4586 Refactor base finder tests to be more compact and easier to make
  src/internal/kopia/base_finder_test.go
Labels: mergequeue, tests, supportability, kopia

#4587 Test variable rename
  src/internal/kopia/base_finder_test.go
Labels: mergequeue, tests, supportability, kopia
