Repository alcionai/corso, pull requests merged in 2023-09, with the labels that each got.

#4168 Remove stray print statement
  src/internal/kopia/upload.go
Labels: mergequeue

#4176 fix language issues with default contacts
  CHANGELOG.md
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/contacts_restore.go
  src/pkg/services/m365/api/contacts_pager.go
Labels: bug, mergequeue, backup, exchange

#4177 Mark all folders we're not keeping as tombstoned
  src/internal/m365/collection/exchange/backup.go
Labels: bug, mergequeue, backup, exchange

#4185 Tweak main page HTML headings
  website/src/components/parts/Hero.js
Labels: mergequeue

#4127 Add common code to check if services are enabled
  src/internal/m365/graph/errors.go
  src/internal/m365/service/exchange/enabled.go
  src/internal/m365/service/exchange/enabled_test.go
  src/internal/m365/service/onedrive/enabled.go
  src/internal/m365/service/onedrive/enabled_test.go
  src/internal/m365/service/sharepoint/enabled.go
  src/internal/m365/service/sharepoint/enabled_test.go
  src/pkg/services/m365/api/mock/user_info.go
  src/pkg/services/m365/api/user_info.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, msgraph, sdk

#4136 use channels api to run backups
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/collection/groups/testdata/channels.go
  src/internal/m365/service/groups/backup.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/testdata/groups.go
Labels: mergequeue, backup, groups

#4148 gather replies when streaming message items
  src/internal/common/str/str.go
  src/internal/common/str/str_test.go
  src/internal/m365/collection/drive/handler_utils.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/pkg/backup/details/groups.go
  src/pkg/selectors/groups.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/events.go
Labels: enhancement, backup, teams, groups

#4145 enumerate ids, get messages in Items()
  src/internal/common/str/str.go
  src/internal/common/str/str_test.go
  src/internal/m365/collection/drive/handler_utils.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/onedrive_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/backup/details/groups.go
  src/pkg/selectors/groups.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/events.go
Labels: enhancement, teams, groups

#4169 Add sites to metadata path
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/group_handler_test.go
Labels: mergequeue, backup

#4096 Add service isolation
  src/cli/backup/backup.go
  src/internal/m365/backup.go
  src/internal/m365/controller_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/restore.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/groups/enabled.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/pkg/services/m365/api/user_info.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/users.go
Labels: mergequeue, msgraph, sdk

#4201 Upgrade browserlist for the website
  website/Dockerfile
Labels: mergequeue

#4184 Add sites metadata in Groups backup
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/group_handler_test.go
  src/internal/m365/service/groups/backup.go
Labels: mergequeue, backup, groups

#4195 Misc fixes for handling groups
  src/internal/m365/graph/metadata/metadata.go
  src/internal/m365/graph/metadata/metadata_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/groups.go
Labels: mergequeue

#4190 Handle groups when setting currency middleware defaults
  src/internal/m365/graph/concurrency_middleware.go
  src/internal/m365/graph/middleware_test.go
Labels: mergequeue

#4204 Actually upgrade the website browserlist
  website/Dockerfile
  website/package-lock.json
Labels: mergequeue

#4199 remove redundant type check
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/factory/impl/sharepoint.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/helper_test.go
  src/internal/m365/onedrive_test.go
  src/internal/m365/stub/stub.go
  src/internal/operations/help_test.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/restore_helper_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/iteminfo_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: bug, mergequeue, backup, teams, groups

#4192 add a BuildMetadata func to path package
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/graph/metadata_collection_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/test/helper_test.go
  src/pkg/path/builder.go
  src/pkg/path/path.go
  src/pkg/path/resource_path_test.go
Labels: mergequeue, tech-debt

#4197 add drive info to site get by id
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
Labels: mergequeue, sharepoint, msgraph

#4186 Wire service isolation changes into SDK code
  src/internal/m365/service/exchange/enabled.go
  src/internal/m365/service/exchange/enabled_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/users.go
  src/pkg/services/m365/users_test.go
Labels: mergequeue, msgraph, sdk

#4189 Cleanup old user info code
  src/pkg/services/m365/api/user_info.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
  src/pkg/services/m365/users.go
  src/pkg/services/m365/users_test.go
Labels: mergequeue, msgraph, sdk

#4206 add site owner to site struct
  src/pkg/services/m365/sites.go
Labels: mergequeue, msgraph, teams, groups

#4210 Typo in docs
  website/docs/setup/restore-options.md
Labels: mergequeue

#4095 Handle groups without SharePoint sites
  src/internal/m365/service/groups/backup.go
Labels: mergequeue, backup, teams, groups

#4221 Disable command to disable retention
  .github/actions/purge-m365-data/action.yml
Labels: bug, mergequeue-priority, ci

#4215 Rename s3checker cmd flags
  .github/workflows/longevity_test.yml
  src/cmd/s3checker/s3checker.go
Labels: mergequeue, tech-debt

#4179 Setup for separating base sets
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/mock_backup_base.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
Labels: mergequeue, backup, kopia

#4220 Ignore permissions restore failure with a log
  src/internal/m365/collection/drive/permission.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/internal/operations/test/onedrive_test.go
Labels: mergequeue

#4223 Fix reference to test site ID
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue, ci, teams, groups

#4224 Temporarily disable groups and teams tests
  .github/workflows/sanity-test.yaml
Labels: mergequeue, ci, teams, groups

#4181 Track assist bases and merge bases separately
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/mock_backup_base.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, backup, kopia

#4174 Delay getting ItemInfo when uploading data
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/m365/service/exchange/mock/collections.go
Labels: mergequeue, backup, kopia

#4217 Switch to using BuildMetadata helper
  src/internal/m365/backup_test.go
  src/internal/m365/service/groups/backup.go
Labels: mergequeue

#4214 Add CI to check for trailing comma
  .github/workflows/ci.yml
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/teams_e2e_test.go
Labels: mergequeue, ci

#4216 Move S3 bucket flags to flags pkg
  src/cli/flags/s3.go
  src/cli/repo/s3.go
  src/cli/utils/flags_test.go
Labels: mergequeue, cli, tech-debt

#4211 add get site by ID to service api
  src/pkg/services/m365/sites.go
Labels: sharepoint, msgraph

#4203 adds export to groups channels
  src/internal/m365/collection/groups/export.go
  src/internal/m365/collection/groups/export_test.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
Labels: enhancement, export, teams, groups

#4173 fixing bugs found during extensive manual tests
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/metadata.go
  src/internal/operations/backup.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/sites.go
  website/docs/support/known-issues.md
Labels: bug, mergequeue, backup, teams, groups

#4227 Upgrade linter to 1.54.2
  .github/workflows/ci.yml
  src/Makefile
Labels: mergequeue, ci

#4183 Update item info api
  src/internal/data/collection.go
  src/internal/data/mock/collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/helper_test.go
Labels: mergequeue, backup

#4193 path pkg rename resouceOwner to protectedResource
  src/internal/kopia/wrapper_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/item_collector.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/restore_caches.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/service.go
  src/internal/m365/helper_test.go
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/m365/stub/stub.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/builder.go
  src/pkg/path/drive_test.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/scopes.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue, tech-debt

#4225 use alias for teams cli
  .github/workflows/sanity-test.yaml
  src/cli/backup/backup.go
  src/cli/backup/groups.go
  src/cli/backup/teams.go
  src/cli/backup/teams_e2e_test.go
  src/cli/backup/teams_test.go
  src/cli/export/export.go
  src/cli/export/groups.go
  src/cli/export/teams.go
  src/cli/export/teams_test.go
  src/cli/restore/groups.go
  src/cli/restore/restore.go
  src/cli/restore/teams.go
  src/cli/restore/teams_test.go
Labels: mergequeue, cli, teams & groups

#4230 Website: Upgrade Ubuntu and Node install process
  website/Dockerfile
  website/Makefile
Labels: mergequeue

#4182 Turn merge bases into assist bases when disabling them
  CHANGELOG.md
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/model/model.go
Labels: bug, mergequeue, backup, kopia

#4229 add non-delta message paging path
  src/internal/common/str/str.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: bug, mergequeue, backup, teams & groups

#4228 Minor refactor of storage provider stringer
  src/cli/backup/helpers_test.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/pkg/storage/providertype_string.go
  src/pkg/storage/storage.go
  src/pkg/storage/storage_test.go
  src/pkg/storage/storageprovider_string.go
Labels: mergequeue, tech-debt

#4235 fix: nightly test
  src/cli/backup/groups_e2e_test.go
Labels: mergequeue

#4240 Fix repo maintenance command
  src/cli/repo/repo.go
Labels: bug, mergequeue, cli, maintenance

#4241 Add repo maintenance command to sanity tests
  .github/workflows/sanity-test.yaml
Labels: mergequeue, maintenance, ci

#4205 Incrementals for Groups SharePoint backup
  src/internal/data/mock/collection.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/backup.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/groups/export_test.go
  src/internal/m365/mock/collection.go
  src/internal/m365/mock/connector.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/groups/backup_test.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export_test.go
  src/internal/m365/stub/stub.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/inject/mock/inject.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/pkg/path/path_test.go
Labels: mergequeue, backup

#4209 Restore for Groups SharePoint Sites
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/restore.go
  src/internal/m365/service/groups/restore.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/internal/operations/restore.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/drive.go
Labels: mergequeue

#4218 CLI and selector changes for groups restore
  src/cli/flags/groups.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/utils/groups.go
  src/cli/utils/groups_test.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/library_handler.go
  src/pkg/selectors/groups.go
Labels: mergequeue

#4242 use display name to look up groups
  src/internal/m365/graph/errors.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/sites.go
Labels: enhancement, mergequeue, backup, teams & groups

#4233 uncomment code to remove deleted messages
  src/internal/m365/collection/groups/collection.go
Labels: bug, backup, teams & groups

#4231 add groups cli selectors
  src/cli/backup/groups.go
  src/cli/export/groups.go
  src/cli/flags/groups.go
  src/cli/flags/onedrive.go
  src/cli/utils/groups.go
  src/cli/utils/groups_test.go
  src/cli/utils/onedrive.go
Labels: enhancement, mergequeue, cli, teams & groups

#4232 get replies when getting message
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/exchange/mock/item.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/collection/groups/mock/getter.go
  src/internal/operations/test/helper_test.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_test.go
  src/pkg/services/m365/api/contacts_test.go
Labels: bug, mergequeue, backup, teams & groups

#4252 Fxi issues with GetMetadataPaths
  src/internal/m365/backup.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, tests

#4250 SharePoint MatchesInfo tests
  src/pkg/selectors/groups_test.go
Labels: mergequeue, tests, teams & groups

#4246 Add linter for checking with empty string
  .github/workflows/ci.yml
  src/cli/config/config.go
  src/cmd/mdgen/mdgen.go
  src/internal/m365/collection/drive/metadata/permissions.go
  src/internal/m365/graph/betasdk/beta_client.go
  src/internal/m365/graph/betasdk/sites/item_pages_item_canvas_layout_horizontal_sections_horizontal_section_item_request_builder.go
  src/internal/m365/graph/betasdk/sites/item_pages_item_canvas_layout_horizontal_sections_item_columns_horizontal_section_column_item_request_builder.go
  src/internal/m365/graph/betasdk/sites/item_pages_item_canvas_layout_request_builder.go
  src/internal/m365/graph/betasdk/sites/item_pages_item_canvas_layout_vertical_section_request_builder.go
  src/internal/m365/graph/betasdk/sites/item_pages_site_page_item_request_builder.go
  src/internal/m365/graph/betasdk/sites/site_item_request_builder.go
  src/internal/m365/graph/middleware.go
  src/internal/m365/graph/uploadsession.go
  src/internal/operations/export_test.go
  src/internal/tester/tester.go
  src/pkg/backup/details/groups.go
  src/pkg/logger/logpath_xdg.go
  src/pkg/services/m365/api/item_pager_test.go
Labels: mergequeue, ci

#4258 Skip exporting SharePoint Libraries from Groups
  src/internal/m365/service/groups/export.go
Labels: mergequeue, export, teams & groups

#4253 add the test teams site to the purge list
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue, ci

#4257 handle path for channel
  src/internal/m365/service/onedrive/restore.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
Labels: mergequeue

#4263 filter backupable groups
  src/internal/m365/backup.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/exchange/enabled_test.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/groups/enabled.go
  src/internal/m365/service/groups/enabled_test.go
  src/pkg/services/m365/api/groups.go
Labels: bug, backup, teams & groups

#4255 match item type in groups selectors info filter
  src/internal/m365/backup.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/exchange/enabled_test.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/groups/enabled.go
  src/internal/m365/service/groups/enabled_test.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
  src/pkg/services/m365/api/groups.go
Labels: bug, mergequeue, teams & groups

#4245 minimize channel messages exports
  src/cli/export/groups_test.go
  src/cli/export/onedrive_test.go
  src/cli/export/sharepoint_test.go
  src/cli/flags/export.go
  src/cli/flags/export_test.go
  src/cli/utils/export_config.go
  src/cli/utils/testdata/flags.go
  src/internal/m365/collection/drive/export.go
  src/internal/m365/collection/groups/export.go
  src/internal/m365/collection/groups/export_test.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/pkg/control/export.go
  src/pkg/export/export.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/serialization.go
Labels: enhancement, mergequeue, export, teams & groups

#4248 Add incremental backup test for groups
  src/internal/m365/collection/exchange/metadata.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/path/drive.go
Labels: mergequeue, backup, tests, teams & groups

#4267 Update Discord link to Corso Discord
  website/blog/2023-07-24-multi-tenant-backup-with-corso.md
Labels: mergequeue

#4249 Add restore tests for groups
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
  src/internal/tester/tconfig/config.go
  src/internal/tester/tconfig/protected_resources.go
Labels: restore, mergequeue, tests, teams & groups

#4278 Fix incorrect sharepoint export test
  src/internal/m365/service/sharepoint/export_test.go
Labels: mergequeue, tests, sharepoint, export

#4280 Drop TODOs that are not relevant anymore
  src/cli/utils/groups.go
  src/internal/archive/zip.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/export.go
  src/internal/operations/export.go
Labels: mergequeue

#4237 Remove tight CLI coupling with S3 storage provider
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/groups.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/cli.go
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/export/export.go
  src/cli/flags/s3.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/restore.go
  src/cli/utils/utils.go
  src/cmd/longevity_test/longevity.go
  src/cmd/s3checker/s3checker.go
  src/internal/operations/backup_test.go
  src/pkg/account/account.go
  src/pkg/storage/storage.go
Labels: mergequeue, tech-debt

#4279 Move MetadataFileNames to test file
  src/internal/m365/collection/exchange/metadata.go
  src/internal/operations/test/exchange_test.go
Labels: mergequeue

#4251 Introduce new interfaces for storage configuration
  src/cli/backup/helpers_test.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/flags/s3.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/utils/utils.go
  src/cmd/s3checker/s3checker.go
  src/internal/events/events_test.go
  src/internal/kopia/s3.go
  src/pkg/storage/s3.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage.go
  src/pkg/storage/testdata/storage.go
Labels: mergequeue, tech-debt

#4277 Add flags for disabling incrementals for groups
  src/cli/backup/groups.go
  src/cli/backup/groups_test.go
Labels: mergequeue, cli, teams & groups

#4244 Minor test expansion for failed backup cleanup
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/cleanup_backups_test.go
Labels: mergequeue, tests, kopia, maintenance

#4282 add humanstring to path category type
  src/cmd/factory/impl/common.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/restore.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/sharepoint/backup.go
  src/pkg/path/category_type.go
  src/pkg/path/category_type_test.go
Labels: mergequeue, cli, tech-debt

#4283 Refactor exchange collection
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
Labels: mergequeue, backup, tech-debt, exchange

#4266 Fetch mod time when getting added and removed items
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/handlers.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/operations/test/exchange_test.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue, backup, msgraph

#4132 Allow getting a path prefix from a string
  src/pkg/path/path.go
  src/pkg/path/path_test.go
Labels: mergequeue

#4284 quick mod tidy
  src/go.mod
Labels: mergequeue

#4286 bump docker actions
  .github/workflows/ci.yml
Labels: mergequeue, ci

#4238 document and release groups and teams
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/backup/groups.go
  src/cli/export/export.go
  src/cli/export/groups.go
  src/cli/export/onedrive.go
  src/cli/export/sharepoint.go
  src/cli/restore/groups.go
  src/cli/restore/onedrive.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
  src/cmd/mdgen/mdgen.go
  website/docs/developers/linters.md
  website/docs/quickstart.md
  website/docs/setup/m365-access.md
  website/docs/support/known-issues.md
  website/sidebars.js
Labels: documentation, mergequeue-priority, teams & groups

#4285 Rename existing Exchange collection implementation
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
Labels: mergequeue, backup, tech-debt, exchange

#4243 Add CLI for local storage
  src/cli/cli.go
  src/cli/config/config.go
  src/cli/config/storage.go
  src/cli/flags/filesystem.go
  src/cli/flags/repo.go
  src/cli/flags/s3.go
  src/cli/repo/filesystem.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/filesystem_test.go
  src/cli/repo/repo.go
  src/cli/utils/flags_test.go
  src/cli/utils/utils.go
  src/cli/utils/utils_test.go
  src/internal/kopia/conn.go
  src/internal/kopia/filesystem.go
  src/internal/tester/tconfig/config.go
  src/pkg/storage/filesystem.go
  src/pkg/storage/storage.go
  src/pkg/storage/testdata/storage.go
Labels: enhancement, mergequeue

#4287 Create documentation for filesystem repositories
  CHANGELOG.md
  website/docs/setup/repos.md
Labels: documentation, mergequeue

#4296 Switch to long-lived AWS credentials
  .github/workflows/nightly_test.yml
Labels: mergequeue, ci

#4295 Add a minor fix for make buildimage
  website/Dockerfile
Labels: documentation, mergequeue

#4133 Implement selective subtree pruning
  CHANGELOG.md
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
Labels: mergequeue, backup, perf, kopia

#4134 Test cleanup
  src/internal/kopia/upload_test.go
Labels: mergequeue, tests, supportability

#4302 Support opening repository in read-only mode
  src/internal/kopia/conn.go
  src/pkg/control/repository/repo.go
  src/pkg/repository/repository_test.go
Labels: mergequeue

#4260 Add export support for Group SharePoint
  src/internal/m365/collection/drive/export.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/export.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
Labels: mergequeue, export, teams & groups

#4304 Expand readonly mode test slightly
  src/pkg/repository/repository_test.go
Labels: mergequeue, tests

#4143 Snapshot function parameter refactor
  src/internal/kopia/upload.go
Labels: mergequeue, backup, tech-debt, kopia

#4300 Lazily fetch Exchange item data when possible
  CHANGELOG.md
  src/internal/kopia/upload.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/exchange/mock/item.go
Labels: mergequeue, backup, perf, exchange

#4317 formalizes ErrApplicationThrottled
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/graph/service.go
  src/pkg/errs/errs.go
Labels: enhancement, mergequeue, msgraph

#4322 Move BaseCollection to different package
  src/internal/data/collection_test.go
  src/internal/data/implementations.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
Labels: mergequeue, supportability, tech-debt

#4323 Fix extracting category from BaseCollection
  src/internal/m365/collection/exchange/collection.go
Labels: bug, mergequeue, backup, exchange

#4288 utilize format validation check
  src/cli/export/export.go
  src/cli/flags/export.go
  src/cli/flags/export_test.go
  src/cli/restore/restore.go
  src/cli/utils/exchange.go
  src/cli/utils/export_config.go
  src/cli/utils/export_config_test.go
  src/cli/utils/groups.go
  src/cli/utils/onedrive.go
  src/cli/utils/restore_config.go
  src/cli/utils/restore_config_test.go
  src/cli/utils/sharepoint.go
  src/pkg/control/restore.go
Labels: mergequeue, cli, export

#4324 Use BaseCollection in groups implementation
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: mergequeue, supportability, tech-debt

#4276 Use HumanString for export folder names
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
Labels: mergequeue, export, teams & groups

#4320 Improve error handling during backup persistence
  src/internal/operations/backup.go
Labels: mergequeue, tech-debt

#4314 Bump msgraph sdk to 1.19.0
  src/cmd/factory/impl/common.go
  src/cmd/sanity_test/export/onedrive.go
  src/cmd/sanity_test/export/sharepoint.go
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/restore/onedrive.go
  src/cmd/sanity_test/restore/sharepoint.go
  src/go.mod
  src/go.sum
  src/internal/m365/collection/exchange/restore_test.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/lists.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/graph/middleware_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/lists.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mail_pager_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, msgraph

#4333 Upgrade Docusaurus to v2.4.3
  website/package-lock.json
  website/package.json
Labels: mergequeue

#4325 Add helper function to get category
  src/internal/data/collection_test.go
  src/internal/data/implementations.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: mergequeue, supportability, tech-debt

#4315 Use backupBase internally in base finder code
  src/internal/kopia/base_finder.go
Labels: mergequeue, supportability, tech-debt, kopia

#4091 Wire backup cleanup into maintenance operation
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/maintenance.go
  src/internal/operations/maintenance_test.go
  src/pkg/control/repository/repo.go
  src/pkg/repository/repository.go
Labels: mergequeue, kopia, maintenance

#4326 bump clues to latest version
  src/go.mod
  src/go.sum
Labels: mergequeue

#4318 add throttling, token counters to operation
  src/internal/m365/graph/concurrency_middleware.go
  src/internal/m365/graph/middleware.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/count/count.go
  src/pkg/count/keys.go
Labels: enhancement, mergequeue, msgraph

#4339 Create and use generic tombstone collection
  src/internal/data/collection_test.go
  src/internal/data/implementations.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/groups/backup.go
Labels: mergequeue, backup, tech-debt

#4334 Do not try to restore channel messages for Groups
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/groups/restore_test.go
  src/pkg/storage/testdata/storage.go
Labels: bug, restore, mergequeue, teams & groups

#4313 skip-permissions flag to stop restoring of permissions of Onedrive
  .github/workflows/sanity-test.yaml
  src/cli/flags/options.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/options_test.go
  src/cli/utils/restore_config.go
  src/cli/utils/restore_config_test.go
  src/cli/utils/testdata/flags.go
Labels: mergequeue

#4342 do not mark not-found items as skipped
  src/internal/m365/collection/drive/collection.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/item.go
  src/pkg/services/m365/api/mail.go
Labels: mergequeue, onedrive, tech-debt

#4298 move container enum to pager pattern
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/contacts_container_cache.go
  src/internal/m365/collection/exchange/container_resolver.go
  src/internal/m365/collection/exchange/events_container_cache.go
  src/internal/m365/collection/exchange/mail_container_cache.go
  src/internal/m365/controller_test.go
  src/internal/m365/graph/cache_container.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue, tech-debt, exchange, msgraph

#4348 Tweak fs repo docs
  website/docs/setup/repos.md
Labels: mergequeue

#4349 Revert "⬆️ Bump tw-elements from 1.0.0-alpha13 to 1.0.0-beta1 in /website"
  website/package-lock.json
  website/package.json
Labels: mergequeue

#4359 Increase nightly test timeout to 2hrs
  .github/workflows/nightly_test.yml
Labels: mergequeue, msgraph

#4350 Make generic version of item structs
  src/internal/data/item.go
  src/internal/data/item_test.go
Labels: mergequeue, supportability, tech-debt

#4363 add missing recoverable errs
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/groups/collection.go
Labels: bug, mergequeue, backup, teams & groups

#4362 move drive expand to config property
  src/internal/m365/collection/site/collection.go
  src/internal/m365/controller.go
  src/internal/m365/mock/id_name_getter.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/sites.go
Labels: mergequeue, backup, sharepoint

#4294 add standardized tests for flags in backup cmds
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_test.go
  src/cli/backup/groups.go
  src/cli/backup/groups_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/export/export.go
  src/cli/export/groups.go
  src/cli/export/groups_test.go
  src/cli/export/onedrive.go
  src/cli/export/onedrive_test.go
  src/cli/export/sharepoint.go
  src/cli/export/sharepoint_test.go
  src/cli/flags/backup_list.go
  src/cli/flags/options.go
  src/cli/flags/repo.go
  src/cli/flags/testdata/backup_list.go
  src/cli/flags/testdata/flags.go
  src/cli/flags/testdata/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_test.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/options_test.go
  src/go.mod
  src/go.sum
Labels: mergequeue, cli, tests

#4360 Disable Exchange kopia assisted incrementals
  src/internal/m365/collection/exchange/backup.go
Labels: mergequeue, backup, exchange

#4351 Exch generic item
  src/internal/data/item.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
Labels: mergequeue, backup, supportability, tech-debt, exchange

#4343 split repo create and init/cnn
  src/cli/backup/backup.go
  src/cli/backup/helpers_test.go
  src/cli/repo/filesystem.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/utils/utils.go
  src/cmd/longevity_test/longevity.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: mergequeue, cli, tech-debt

#4353 Groups generic item
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
Labels: mergequeue, backup, supportability, tech-debt, teams & groups

#4356 Generic item api update
  src/internal/data/item.go
  src/internal/data/item_test.go
  src/internal/m365/collection/exchange/collection.go
Labels: mergequeue, backup, supportability, tech-debt

#4357 Use generic item in Drive backup
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/helper_test.go
Labels: mergequeue, backup, onedrive, supportability, tech-debt, sharepoint

#4335 allow delete of multiple backup IDs
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/groups.go
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/flags/repo.go
  src/cli/restore/groups.go
Labels: mergequeue

#4374 Fix NPE in Exchange CLI restore E2E setup suite
  src/cli/restore/exchange_e2e_test.go
Labels: bug, mergequeue, tests, exchange

#4375 separate delta not supported from invalid
  CHANGELOG.md
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/item_pager.go
Labels: bug, mergequeue-priority, backup, teams & groups

#4373 Add sanity tests for Groups incrementals and restore
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests

#4368 graph debug logging improvements
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/graph/logging.go
  src/internal/m365/graph/middleware.go
  src/internal/m365/graph/service.go
Labels: mergequeue, tech-debt

#4377 remove expand drive from root site
  src/internal/m365/service/sharepoint/enabled.go
  src/internal/m365/service/sharepoint/enabled_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
Labels: bug, mergequeue, backup, sharepoint

#4376 fix getting owner of sites
  src/pkg/services/m365/sites.go
  src/pkg/services/m365/sites_test.go
Labels: mergequeue

#4383 call repo connect in connect S3 cmd
  src/cli/repo/s3.go
Labels: mergequeue

#4347 quick cleanup before next step
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/groups.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/export/export.go
  src/cli/restore/restore.go
  src/cli/utils/utils.go
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, cli, tech-debt

#4390 Use non-zero time as fallback
  src/pkg/services/m365/api/item_pager.go
Labels: bug, mergequeue-priority, backup, exchange

#4384 Fix nightly tests for exchange, onedrive and groups
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
Labels: mergequeue, tests

#4392 Revert sanity tests for Groups incrementals and restore
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests

#4340 some minor renames before the next change
  src/pkg/fault/fault.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
Labels: tech-debt

#4361 ensure account details on init/connect
  src/internal/m365/controller.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/repository.go
  src/pkg/services/m365/api/access.go
  src/pkg/services/m365/api/access_test.go
  src/pkg/services/m365/api/client.go
Labels: cli, tech-debt, msgraph

#4355 connect to data provider during init/connect
  src/cli/backup/helpers_test.go
  src/cli/repo/filesystem.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/utils/utils.go
  src/cmd/longevity_test/longevity.go
  src/internal/m365/controller.go
  src/pkg/path/service_type.go
  src/pkg/repository/backups.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/exports.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/restores.go
  src/pkg/services/m365/api/access.go
  src/pkg/services/m365/api/access_test.go
  src/pkg/services/m365/api/client.go
Labels: cli, tech-debt

#4398 Add recommendations on when to run maintenance
  website/docs/setup/maintenance.md
Labels: documentation, mergequeue

#4389 show connect and init errors
  src/cli/repo/filesystem.go
  src/cli/repo/s3.go
  src/internal/kopia/conn.go
  src/pkg/repository/repository.go
  src/pkg/storage/common_test.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage_test.go
Labels: bug, cli

#4388 use concrete types for store configs
  src/cli/backup/helpers_test.go
  src/cli/config/config_test.go
  src/cli/repo/filesystem.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cmd/s3checker/s3checker.go
  src/internal/kopia/conn.go
  src/internal/kopia/filesystem.go
  src/internal/kopia/s3.go
  src/pkg/repository/repository.go
  src/pkg/storage/common_test.go
  src/pkg/storage/filesystem.go
  src/pkg/storage/s3.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage_test.go
Labels: tech-debt

#4316 move drive pagers to pager pattern
  src/cmd/purge/scripts/onedrivePurge.ps1
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/fault/fault.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/delta.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue, onedrive, tech-debt, msgraph

#4396 add GroupByID to services
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/groups/enabled.go
  src/internal/m365/service/groups/enabled_test.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/groups_test.go
Labels: mergequeue-priority, msgraph, sdk, teams & groups

#4391 correctly attach store/provider flags
  src/cli/backup/backup.go
  src/cli/backup/exchange_test.go
  src/cli/backup/groups_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/export/export.go
  src/cli/export/groups_test.go
  src/cli/export/onedrive_test.go
  src/cli/export/sharepoint_test.go
  src/cli/flags/testdata/flags.go
  src/cli/restore/exchange_test.go
  src/cli/restore/groups_test.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/restore.go
  src/cli/restore/sharepoint_test.go
  src/cli/testdata/cli.go
Labels: bug, mergequeue, cli

#4370 sanity test refactor
  .github/actions/backup-restore-test/action.yml
  .github/actions/slack-message/action.yml
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/common/common.go
  src/cmd/sanity_test/common/filepath.go
  src/cmd/sanity_test/common/sanitree.go
  src/cmd/sanity_test/common/utils.go
  src/cmd/sanity_test/export/groups.go
  src/cmd/sanity_test/export/onedrive.go
  src/cmd/sanity_test/export/sharepoint.go
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/restore/groups.go
  src/cmd/sanity_test/restore/onedrive.go
  src/cmd/sanity_test/restore/sharepoint.go
  src/cmd/sanity_test/sanity_tests.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/mail.go
Labels: mergequeue, tests

#4387 assert correct error on s3 conn bad configs e2e
  src/cli/backup/helpers_test.go
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/repo/filesystem.go
  src/cli/repo/filesystem_e2e_test.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cmd/s3checker/s3checker.go
  src/internal/kopia/conn.go
  src/internal/kopia/filesystem.go
  src/internal/kopia/s3.go
  src/pkg/repository/repository.go
  src/pkg/storage/common_test.go
  src/pkg/storage/filesystem.go
  src/pkg/storage/s3.go
  src/pkg/storage/s3_test.go
  src/pkg/storage/storage.go
  src/pkg/storage/storage_test.go
Labels: bug, mergequeue, tests

#4401 Lock updating info in lazyItem
  src/internal/data/item.go
Labels: mergequeue, backup

#4365 Create generic items without Info()
  src/internal/data/item.go
  src/internal/data/item_test.go
Labels: mergequeue, backup, supportability, tech-debt
