Repository alcionai/corso, pull requests merged in 2023-11, with the labels that each got.

#4588 Update log statements for base finder
  src/internal/kopia/base_finder.go
Labels: mergequeue, backup, supportability, kopia

#4591 Helper function to get backup type
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
Labels: mergequeue, supportability

#4592 Minor refactor for checking backup type when finding bases
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
Labels: mergequeue, backup, kopia

#4596 Update link for v0.15.0 diff in changelog
  CHANGELOG.md
Labels: mergequeue

#4491 Create service specific handlers that know how to run an export
  src/internal/m365/controller.go
  src/internal/m365/export.go
  src/internal/m365/mock/connector.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
  src/internal/operations/export.go
  src/internal/operations/export_test.go
  src/internal/operations/inject/inject.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/exports.go
Labels: mergequeue, supportability, export

#4593 Exclude preview backups when looking for bases
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/model/model.go
Labels: mergequeue, backup, kopia

#4595 Create and tag preview backups
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/control/options.go
Labels: mergequeue, backup

#4570 boilerplate introduction of the conversations api
  src/internal/operations/test/helper_test.go
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/conversations.go
  src/pkg/services/m365/api/conversations_pager.go
  src/pkg/services/m365/api/conversations_pager_test.go
  src/pkg/services/m365/api/conversations_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: mergequeue, backup, teams & groups

#4582 update graph interfaces
  src/internal/m365/graph/cache_container.go
  src/internal/m365/graph/interfaces.go
  src/pkg/services/m365/api/pagers/pagers.go
Labels: backup, teams & groups

#4615 also handle delete -> create -> delete
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
Labels: bug, backup, onedrive

#4612 Handle folder being deleted and recreated in between a backup
  CHANGELOG.md
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
Labels: mergequeue-priority

#4605 Share count bus between graph clients and backup/restore operations
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/graph/service.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/maintenance_test.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/restore_helper_test.go
  src/internal/operations/test/sharepoint_test.go
  src/pkg/repository/backups.go
  src/pkg/repository/data_providers.go
Labels: mergequeue, telemetry, msgraph

#4619 Add $top param for drive pagers
  src/pkg/services/m365/api/drive_pager.go
Labels: mergequeue, msgraph

#4578 add getPostIDs in conversations pager
  src/cli/utils/groups_test.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/handlers.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/graph/cache_container.go
  src/internal/m365/graph/interfaces.go
  src/internal/operations/test/exchange_test.go
  src/pkg/path/category_type.go
  src/pkg/path/category_type_test.go
  src/pkg/path/categorytype_string.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/conversations_pager.go
  src/pkg/services/m365/api/conversations_pager_test.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/interfaces.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/pagers/pagers.go
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, backup, teams & groups

#4621 Update gci cli args in Makefile
  src/Makefile
Labels: mergequeue

#4631 Ensure each drive gets a unique url cache instance
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
Labels: bug, mergequeue-priority, perf, sharepoint

#4618 Implement a sliding window rate limiter
  src/go.mod
  src/go.sum
  src/internal/common/limiters/limiter.go
  src/internal/common/limiters/sliding_window.go
  src/internal/common/limiters/sliding_window_test.go
Labels: mergequeue, perf, msgraph

#4616 Cleanup and consolidate test code for pagers
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, tests

#4628 Don't allow merge bases for preview backups
  src/internal/operations/backup.go
Labels: mergequeue, backup

#4622 Consolidate pager tests while adding more coverage
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, tests

#4630 verify previous path state before backup
  CHANGELOG.md
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/debug.go
  src/internal/operations/inject/inject.go
  src/internal/operations/manifests.go
  src/pkg/fault/alert.go
  src/pkg/fault/fault.go
Labels: bug, backup, onedrive, sharepoint

#4624 Check if delta link is populated in tests
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, tests

#4648 clean up variable naming and usage in collections test
  src/.golangci.yml
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/url_cache_test.go
Labels: backup, onedrive, tests

#4629 support debug reading out delta files
  CHANGELOG.md
  src/.golangci.yml
  src/cli/cli.go
  src/cli/debug/debug.go
  src/cli/debug/exchange.go
  src/cli/debug/groups.go
  src/cli/debug/onedrive.go
  src/cli/debug/sharepoint.go
  src/cli/print/print.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/wrapper.go
  src/internal/m365/backup.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/debug.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/exchange/debug.go
  src/internal/m365/collection/groups/debug.go
  src/internal/m365/debug.go
  src/internal/m365/mock/connector.go
  src/internal/operations/inject/inject.go
  src/internal/operations/inject/mock/inject.go
  src/internal/operations/manifests.go
  src/pkg/fault/alert.go
  src/pkg/fault/fault.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/debug.go
  src/pkg/repository/repository.go
  src/pkg/store/metadata.go
Labels: enhancement, mergequeue, cli, supportability

#4617 some minor logging touchups
  src/internal/kopia/upload.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/groups/backup.go
  src/internal/observe/observe.go
  src/pkg/services/m365/api/pagers/pagers.go
Labels: mergequeue, supportability

#4635 check path equivalency
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/storage/filesystem.go
  src/pkg/storage/s3.go
  src/pkg/storage/storage.go
  src/pkg/storage/storage_test.go
Labels: mergequeue, bug-fix, repo

#4625 Allow limiting or cancelling pager enumeration
  src/internal/m365/collection/drive/url_cache_test.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/conversations_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/pagers/pagers.go
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, msgraph

#4637 abstract kopia setup code
  src/pkg/repository/repository.go
  src/pkg/services/m365/sites_test.go
Labels: mergequeue, kopia, refactor

#4623 ensure invalid deltas result in new state collections
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
Labels: bug, mergequeue-priority, backup, onedrive

#4654 Upgrade to Docusaurus v3.0.0
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: mergequeue

#4655 Getlicenseinfo
  src/internal/m365/onedrive_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/tester/tconfig/protected_resources.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/users.go
  src/pkg/services/m365/users_test.go
Labels: enhancement, mergequeue, msgraph

#4658 Fix test flake
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: bug, mergequeue, tests

#4659 Move groups version bump tests to nightly
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: mergequeue, tests

#4638 set repository config location w.r.t corso config location
  src/cli/config/config.go
  src/cli/config/storage.go
Labels: mergequeue, repo, config

#4639 generate repository config name based on provider specific hash
  src/internal/common/str/str.go
  src/internal/common/str/str_test.go
  src/internal/common/str/testdata/str.go
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/maintenance_test.go
  src/internal/operations/restore_test.go
  src/internal/operations/retention_config_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/restore_helper_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/account/account.go
  src/pkg/account/account_test.go
  src/pkg/account/m365.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/storage/filesystem.go
  src/pkg/storage/s3.go
  src/pkg/storage/storage.go
  src/pkg/storage/storage_test.go
Labels: mergequeue, repo, config

#4666 add a resource getter setter to newServiceHandler
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/export.go
  src/internal/operations/test/helper_test.go
Labels: mergequeue

#4667 Pin tw-elements version to prevent change from MIT to AGPL
  website/package-lock.json
  website/package.json
Labels: mergequeue

#4602 Helper functions to test generic backup flags
  src/cli/backup/exchange_test.go
  src/cli/backup/groups_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/flags/testdata/repo.go
Labels: mergequeue, backup, cli, tests

#4571 Rename service handlers
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/sharepoint/export.go
Labels: mergequeue, supportability

#4572 Consolidate groups version bump tests
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: mergequeue, backup, tests

#4656 Test error return values from pagers
  src/pkg/services/m365/api/pagers/pagers.go
  src/pkg/services/m365/api/pagers/pagers_test.go
Labels: mergequeue, tests

#4672 Add progress logging to uploader
  src/internal/kopia/upload.go
Labels: mergequeue

#4607 Create a ContainerResolver that returns items in priority order
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/container_resolver.go
  src/internal/m365/collection/exchange/container_resolver_test.go
  src/pkg/services/m365/api/graph/cache_container.go
Labels: mergequeue, backup, exchange

#4674 Add limiter reset functionality
  src/internal/common/limiters/limiter.go
  src/internal/common/limiters/sliding_window.go
  src/internal/common/limiters/sliding_window_test.go
Labels: mergequeue, perf, exchange

#4682 bump clues to latest
  src/go.mod
  src/go.sum
Labels: mergequeue, supportability

#4530 minor test enhancement
  src/pkg/services/m365/api/graph/consts.go
  src/pkg/services/m365/api/groups_test.go
Labels: mergequeue, tests, tech-debt

#4675 Add WaitN support to limiter
  src/internal/common/limiters/limiter.go
  src/internal/common/limiters/sliding_window.go
  src/internal/common/limiters/sliding_window_test.go
Labels: mergequeue, perf, exchange

#4676 Add a control option to disable sliding window limiter
  src/cli/backup/exchange.go
  src/cli/backup/exchange_test.go
  src/cli/flags/options.go
  src/cli/utils/options.go
  src/cli/utils/options_test.go
  src/pkg/control/options.go
Labels: mergequeue, cli, exchange

#4657 Wire up config for pager result limit
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/handlers.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue

#4678 Move various limiter types behind a common interface
  src/internal/common/limiters/token_bucket.go
  src/pkg/services/m365/api/graph/concurrency_middleware.go
  src/pkg/services/m365/api/graph/middleware_test.go
Labels: mergequeue, tech-debt, msgraph

#4695 Use microsecond granularity for exchange tests
  src/internal/m365/controller_test.go
  src/internal/m365/onedrive_test.go
Labels: bug, mergequeue-priority, tests, ci

#4671 retry item downloads on invalid token error
  CHANGELOG.md
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/item.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/fault/fault.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
  src/pkg/services/m365/api/graph/service.go
  src/pkg/services/m365/api/graph/service_test.go
Labels: bug, mergequeue, backup, onedrive

#4692 add delta tree
  src/internal/m365/collection/drive/delta_tree.go
  src/internal/m365/collection/drive/delta_tree_test.go
Labels: mergequeue, backup, onedrive

#4687 Add functions used for restore to existing service-level handlers
  src/internal/m365/export.go
  src/internal/m365/resource/resource.go
  src/internal/m365/service/groups/export.go
  src/internal/m365/service/groups/export_test.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
Labels: mergequeue, tech-debt

#4679 Move rate limiter ctx binding to backup operation scope
  src/internal/m365/backup.go
  src/internal/m365/collection/drive/collection.go
  src/internal/operations/backup.go
Labels: mergequeue, tech-debt

#4640 Converter for msg to eml
  src/go.mod
  src/go.sum
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
  src/internal/converters/eml/testdata/email-with-attachments.json
Labels: enhancement, mergequeue, exchange, export

#4641 Add cli for exchange export
  src/cli/backup/exchange.go
  src/cli/export/exchange.go
  src/cli/export/exchange_test.go
  src/cli/export/export.go
  src/cli/export/groups.go
  src/cli/export/onedrive.go
  src/cli/export/sharepoint.go
  src/cli/flags/exchange.go
  src/cli/restore/exchange.go
  src/cli/utils/exchange.go
  src/cli/utils/export_config.go
  src/cli/utils/export_config_test.go
Labels: enhancement, mergequeue, exchange, export

#4642 Add support for email exports
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
  src/internal/converters/eml/testdata/testdata.go
  src/internal/m365/collection/exchange/export.go
  src/internal/m365/export.go
  src/internal/m365/service/exchange/export.go
  src/internal/m365/service/exchange/export_test.go
Labels: enhancement, mergequeue, exchange, export

#4643 Debug CLI for msg to eml conversion
  src/cmd/converter/converter.go
Labels: mergequeue, exchange, export

#4645 Add changelog entry for email exports
  CHANGELOG.md
Labels: enhancement, mergequeue, exchange, export

#4644 Improvements and tests for eml conversion
  CHANGELOG.md
  src/cmd/converter/converter.go
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
  src/internal/m365/collection/exchange/export.go
Labels: enhancement, mergequeue, exchange, export

#4651 Imrpove message -> eml conversion
  src/go.mod
  src/go.sum
  src/internal/converters/eml/eml.go
  src/internal/converters/eml/eml_test.go
  src/internal/converters/eml/testdata/email-with-attachments.json
Labels: mergequeue, export

#4680 Integrate sliding window limiter into exchange backup operation
  src/internal/m365/backup.go
  src/internal/m365/mock/connector.go
  src/internal/operations/backup.go
  src/internal/operations/inject/inject.go
  src/internal/operations/inject/mock/inject.go
  src/pkg/services/m365/api/graph/concurrency_middleware.go
  src/pkg/services/m365/api/graph/middleware_test.go
Labels: mergequeue, perf, exchange

#4525 Make the cli colorful and informational
  src/cli/backup/backup.go
  src/cli/cli.go
  src/cli/export/export.go
  src/cli/print/print.go
  src/go.mod
  src/go.sum
  src/internal/common/color/color.go
  src/internal/kopia/wrapper.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/export.go
  src/internal/operations/restore.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/repository.go
Labels: mergequeue, cli

#4526 Change printing of backup stats to single line
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/help/env.go
  src/cli/print/print.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/entry.go
  src/pkg/fault/alert.go
  src/pkg/fault/alert_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
  src/pkg/fault/skipped.go
  src/pkg/fault/skipped_test.go
Labels: mergequeue, cli

#4697 Update docs to include export commands
  website/sidebars.js
Labels: documentation, mergequeue

#4698 Minor cleanup for drive backup code
  src/internal/m365/collection/drive/collections.go
Labels: mergequeue, backup, onedrive

#4665 add counters to groups backups
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/service/groups/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/maintenance_test.go
  src/pkg/count/keys.go
  src/pkg/services/m365/api/graph/metadata_collection.go
  src/pkg/services/m365/api/graph/metadata_collection_test.go
Labels: supportability

#4664 use counter in drive backups
  src/internal/data/item.go
  src/internal/data/item_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/debug.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/debug.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/maintenance_test.go
  src/pkg/count/keys.go
  src/pkg/services/m365/api/graph/metadata_collection.go
  src/pkg/services/m365/api/graph/metadata_collection_test.go
Labels: supportability

#4703 some final cleanups
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/service/groups/backup.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/count/count.go
  src/pkg/count/count_test.go
  src/pkg/count/keys.go
Labels: supportability

#4702 add graph options to services client
  CHANGELOG.md
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: enhancement, msgraph, sdk

#4661 use counter in exchange backup enum
  src/internal/data/collection_test.go
  src/internal/data/implementations.go
  src/internal/data/item.go
  src/internal/data/item_test.go
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/debug.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/collection_test.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/debug.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/onedrive/backup_test.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/maintenance_test.go
  src/internal/operations/restore.go
  src/pkg/count/count.go
  src/pkg/count/count_test.go
  src/pkg/count/keys.go
  src/pkg/services/m365/api/graph/collections.go
  src/pkg/services/m365/api/graph/collections_test.go
  src/pkg/services/m365/api/graph/metadata_collection.go
  src/pkg/services/m365/api/graph/metadata_collection_test.go
Labels: mergequeue, supportability

#4683 clean up unused graph error sentinels
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/service/exchange/enabled_test.go
  src/internal/m365/service/groups/enabled_test.go
  src/internal/m365/service/onedrive/enabled_test.go
  src/internal/m365/service/sharepoint/enabled_test.go
  src/pkg/services/m365/api/conversations_test.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/graph/errors.go
  src/pkg/services/m365/api/graph/errors_test.go
  src/pkg/services/m365/api/graph/middleware_test.go
  src/pkg/services/m365/api/graph/service_test.go
  src/pkg/services/m365/api/graph/testdata/errors.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/pagers/pagers_test.go
  src/pkg/services/m365/api/users_test.go
Labels: mergequeue, tech-debt, msgraph

#4701 move service api to client methods
  CHANGELOG.md
  src/cli/backup/groups.go
  src/cli/backup/sharepoint.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/groups_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
  src/pkg/services/m365/sites.go
  src/pkg/services/m365/sites_test.go
  src/pkg/services/m365/users.go
  src/pkg/services/m365/users_test.go
Labels: enhancement, mergequeue, msgraph

#4660 Finish wiring up Exchange preview backups
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/contacts_backup.go
  src/internal/m365/collection/exchange/events_backup.go
  src/internal/m365/collection/exchange/handlers.go
  src/internal/m365/collection/exchange/mail_backup.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/control/options.go
Labels: mergequeue, backup, exchange

#4706 Add connection timeout retries to item retry handler
  CHANGELOG.md
  src/internal/common/readers/retry_handler.go
  src/internal/common/readers/retry_handler_test.go
Labels: mergequeue, onedrive

#4705 Improve logging/variable grouping for exchange preview backup
  src/internal/m365/collection/exchange/backup.go
Labels: mergequeue, backup, supportability, exchange

#4704 bump xsync to v3
  src/go.mod
  src/go.sum
  src/internal/common/syncd/map.go
  src/internal/m365/collection/drive/permission.go
  src/internal/m365/collection/drive/permission_test.go
  src/internal/m365/collection/drive/restore_caches.go
  src/internal/operations/test/onedrive_test.go
  src/pkg/count/count.go
Labels: mergequeue, dependencies, tech-debt

#4711 Cleaner way to disable merge bases during preview
  src/internal/operations/backup.go
Labels: mergequeue, backup, supportability

#4694 add toggle for using the delta tree via cli
  src/cli/backup/onedrive.go
  src/cli/flags/onedrive.go
  src/cli/utils/options.go
  src/pkg/control/options.go
Labels: mergequeue, backup, onedrive, cli

#4699 Preview backup for drive-backed services
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/control/options.go
  src/pkg/services/m365/api/pagers/pagers.go
Labels: mergequeue, backup, onedrive

#4708 Test default drive limits are applied when expected
  src/internal/m365/collection/drive/collections_test.go
Labels: mergequeue, backup, onedrive, tests

#4712 Return details from restore function
  src/internal/m365/restore.go
  src/internal/m365/service/exchange/restore.go
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/groups/restore_test.go
  src/internal/m365/service/onedrive/restore.go
  src/internal/m365/service/sharepoint/restore.go
Labels: restore, mergequeue, tech-debt

#4709 Standardize naming for preview default limits
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
Labels: mergequeue, backup, onedrive, supportability, exchange

#4710 Add logging like in exchange backup path
  src/internal/m365/collection/drive/collections.go
Labels: mergequeue, backup, onedrive, supportability

#4722 Move rate limiter reset to defer block
  src/internal/operations/backup.go
Labels: bug, mergequeue, perf

#4728 Fix small typo in ci config
  .github/actions/backup-restore-test/action.yml
Labels: mergequeue

#4620 Add regression tests for drive pagers
  src/pkg/services/m365/api/drive_pager_test.go
Labels: mergequeue, tests

#4589 completes basic backup support for conversations
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/conversation_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/service/groups/backup.go
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/groups.go
  src/pkg/path/elements.go
Labels: enhancement, backup, teams & groups

#4584 adds conversation handler and operations integration backup tests
  src/cli/backup/groups.go
  src/cli/backup/groups_e2e_test.go
  src/cli/backup/groups_test.go
  src/cli/flags/groups.go
  src/cli/flags/testdata/flags.go
  src/cli/flags/testdata/groups.go
  src/cli/flags/testdata/sharepoint.go
  src/cli/utils/groups.go
  src/cli/utils/groups_test.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/backup_test.go
  src/internal/m365/collection/groups/channel_handler.go
  src/internal/m365/collection/groups/conversation_handler.go
  src/internal/m365/collection/groups/handlers.go
  src/internal/m365/service/groups/backup.go
  src/internal/operations/test/group_test.go
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/groups.go
  src/pkg/path/elements.go
  src/pkg/selectors/testdata/groups.go
Labels: backup, teams & groups

#4714 Use service-handler for restore operations
  src/cmd/factory/impl/common.go
  src/internal/data/implementations.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/mock/connector.go
  src/internal/m365/restore.go
  src/internal/m365/service/exchange/export.go
  src/internal/m365/service/exchange/restore.go
  src/internal/m365/service/groups/restore.go
  src/internal/m365/service/groups/restore_test.go
  src/internal/m365/service/onedrive/restore.go
  src/internal/m365/service/sharepoint/restore.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/restore_helper_test.go
  src/pkg/repository/data_providers.go
  src/pkg/repository/restores.go
Labels: restore, mergequeue, tech-debt

#4744 allow sdk users to set graph client timeouts
  src/pkg/services/m365/api/graph/http_wrapper.go
  src/pkg/services/m365/api/graph/service.go
Labels: mergequeue, msgraph

#4717 move limiter code to its own file
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
Labels: backup, onedrive

#4743 generic package update
  src/go.mod
  src/go.sum
Labels: mergequeue, dependencies

#4742 bump changelog with v16 release
  CHANGELOG.md
Labels: documentation, mergequeue

#4716 add boilerplate for drive tree processing
  src/internal/data/implementations.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/limiter.go
  src/internal/m365/collection/drive/limiter_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/count/testdata/count.go
Labels: mergequeue, backup, onedrive

#4466 Rewrite Corso's kopia snapshot tie-ins to use directory iterators
  src/go.mod
  src/go.sum
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
Labels: mergequeue, backup, supportability, tech-debt, kopia

#4730 Fix export sanity tests
  .github/actions/backup-restore-test/action.yml
Labels: mergequeue

#4740 Fix sanity tests for SharePoint and Groups
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/export/groups.go
  src/cmd/sanity_test/export/sharepoint.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
Labels: mergequeue, tests

#4741 Sanity tests for email exports
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/common/filepath.go
  src/cmd/sanity_test/export/exchange.go
  src/cmd/sanity_test/restore/exchange.go
  src/cmd/sanity_test/sanity_tests.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue, tests, exchange, export

#4752 Minor retry handler test refactor
  src/pkg/services/m365/api/graph/middleware_test.go
Labels: mergequeue, tests

#4750 Add configurable retries for 503 and 504 errors
  src/pkg/services/m365/api/graph/http_wrapper.go
  src/pkg/services/m365/api/graph/middleware_test.go
  src/pkg/services/m365/api/graph/service.go
Labels: mergequeue, msgraph

#4601 [Snyk] Security upgrade ubuntu from 23.04 to mantic-20231011
  website/Dockerfile
Labels: mergequeue

#4757 Switch to new secret name for teams webhook
  .github/workflows/sanity-test.yaml
Labels: mergequeue, ci, bug-fix

#4721 populate tree with folder enumeration
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/collections_tree.go
  src/internal/m365/collection/drive/collections_tree_test.go
  src/internal/m365/collection/drive/delta_tree_test.go
  src/internal/m365/collection/drive/limiter_test.go
  src/pkg/count/keys.go
Labels: backup, onedrive
