Repository alcionai/corso, pull requests merged in 2023-02, with the labels that each got.

#2338 Bump up max page size preference for exchange delta requests
  CHANGELOG.md
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/api/shared.go
Labels: mergequeue

#2340 Run gofmt on beta package
  src/internal/connector/graph/betasdk/models/horizontal_section_layout_type.go
  src/internal/connector/graph/betasdk/models/meta_data_key_string_pair.go
  src/internal/connector/graph/betasdk/models/meta_data_key_string_pairable.go
  src/internal/connector/graph/betasdk/models/page_layout_type.go
  src/internal/connector/graph/betasdk/models/page_promotion_type.go
  src/internal/connector/graph/betasdk/models/publication_facet.go
  src/internal/connector/graph/betasdk/models/publication_facetable.go
  src/internal/connector/graph/betasdk/models/reactions_facet.go
  src/internal/connector/graph/betasdk/models/reactions_facetable.go
  src/internal/connector/graph/betasdk/models/section_emphasis_type.go
  src/internal/connector/graph/betasdk/models/site_access_type.go
  src/internal/connector/graph/betasdk/models/site_security_level.go
  src/internal/connector/graph/betasdk/models/site_settings.go
  src/internal/connector/graph/betasdk/models/site_settingsable.go
  src/internal/connector/graph/betasdk/models/standard_web_part.go
  src/internal/connector/graph/betasdk/models/standard_web_partable.go
  src/internal/connector/graph/betasdk/models/text_web_part.go
  src/internal/connector/graph/betasdk/models/text_web_partable.go
  src/internal/connector/graph/betasdk/models/title_area_layout_type.go
  src/internal/connector/graph/betasdk/models/title_area_text_alignment_type.go
  src/internal/connector/graph/betasdk/models/web_part_position.go
  src/internal/connector/graph/betasdk/models/web_part_positionable.go
Labels: mergequeue

#2343 print location of log file
  src/pkg/logger/logger.go
Labels: mergequeue, cli, supportability, tech-debt

#2339 log end-of-observe even when hidden
  src/internal/observe/observe.go
Labels: mergequeue, supportability, tech-debt

#2345 Add progress logging to delta queries
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
Labels: mergequeue

#2346 Log collection updates
  src/internal/observe/observe.go
Labels: mergequeue

#2347 Improve log file docs
  website/docs/setup/configuration.md
Labels: mergequeue

#2322 OneDrive Items API for mocking
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue, onedrive, tests, supportability

#2341 Patch and test some edge cases for deserializing OneDrive metadata
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: bug, mergequeue, tests

#2358 GC: Backup: ItemAttachment Complete
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
Labels: mergequeue-priority, backup

#2342 OneDrive tests for Get()
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue, backup, onedrive, tests

#2359 GC: Restore: Disable Item.Attachment Restore
  CHANGELOG.md
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/mockconnector/mock_data_message.go
Labels: mergequeue-priority

#2363 [chore] Remove redundant module use
  src/go.mod
  src/go.sum
  src/internal/connector/support/status.go
Labels: mergequeue

#2344 Issue 2329 logfile 1
  .gitignore
  src/cli/cli.go
  src/pkg/logger/logger.go
Labels: mergequeue, tech-debt

#2362 new blog post on storage options for corso
  website/blog/2023-2-4-where-to-store-corso.md
  website/blog/images/boxes_web.jpeg
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#2383 extra panic protection in operations
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
Labels: mergequeue, tech-debt

#2148 Metadata backup for OneDrive
  CHANGELOG.md
  src/cli/backup/onedrive.go
  src/cli/options/options.go
  src/cli/restore/onedrive.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/status.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
  src/pkg/control/options.go
Labels: mergequeue

#2324 Backup versioning
  CHANGELOG.md
  src/cmd/factory/impl/common.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
  src/pkg/backup/backup.go
Labels: mergequeue

#2370 Fix some edge cases around OneDrive permissions backup
  CHANGELOG.md
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue

#2386 handle error from bu.backupCollections
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: bug, mergequeue

#2374 Disable OneDrive permissions backup by default
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/options/options.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/control/options.go
Labels: mergequeue

#2368 Run gci on beta package
  src/internal/connector/discovery/api/beta_service.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/betasdk/beta_client.go
  src/internal/connector/graph/betasdk/models/site_page_collection_response.go
  src/internal/connector/graph/betasdk/sites/item_pages_item_web_parts_item_get_position_of_web_part_request_builder.go
  src/internal/connector/graph/betasdk/sites/item_pages_item_web_parts_request_builder.go
  src/internal/connector/graph/betasdk/sites/item_pages_item_web_parts_web_part_item_request_builder.go
  src/internal/connector/graph/betasdk/sites/item_pages_request_builder.go
  src/pkg/logger/logger.go
Labels: mergequeue

#2178 GC: SharePoint: BackUp: Pages
  src/internal/connector/discovery/api/beta_service.go
  src/internal/connector/sharepoint/api/api.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/connector/sharepoint/list_test.go
Labels: enhancement, mergequeue, backup

#2355 GC: Restore: `event.item` attachment support
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/mockconnector/mock_data_message.go
  src/internal/connector/support/m365Transform.go
Labels: bug, enhancement, mergequeue, exchange

#2397 Alternative way to handle 2-level calendars hierarchy
  CHANGELOG.md
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_vars.go
  src/internal/connector/exchange/service_restore.go
Labels: bug, mergequeue-priority, mergequeue, backup, exchange

#2391 clean up operation run-do funcs
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue

#2387 Adds more retries to OneDrive API calls
  CHANGELOG.md
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
Labels: mergequeue

#2393 Upgrade Docusaurus to v2.3.1
  website/package-lock.json
  website/package.json
Labels: mergequeue

#2399 fix user query filtering on null userType
  CHANGELOG.md
  src/internal/connector/discovery/api/users.go
Labels: bug, mergequeue

#2396 Blog corso storage
  website/blog/2023-2-4-where-to-store-corso.md
Labels: mergequeue

#2226 GC: Testing: SharePoint: Mock Data
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/mockconnector/mock_data_page.go
Labels: supportability

#2224 GC: Restore: SharePoint: Serialization Support
  .github/workflows/ci.yml
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/mockconnector/mock_data_page.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
Labels: enhancement, restore, mergequeue

#2356 Fix test failures when run without env vars
  src/internal/connector/discovery/api/beta_service_test.go
  src/internal/connector/graph/betasdk/beta_client_test.go
Labels: bug, mergequeue, tests

#2371 Pass in prev delta to collectItems
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue

#2225 GC: Restore: SharePoint: Page Logic
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
Labels: enhancement, restore, mergequeue

#2227 GC: Restore: SharePoint: Collection logic
  src/internal/connector/graph_connector.go
  src/internal/connector/sharepoint/restore.go
Labels: restore, mergequeue

#2320 add clues, fault to op/restore.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/fault/mock/mock.go
Labels: mergequeue, supportability, tech-debt

#2379 Wire up most of exclude list for OneDrive
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue, backup

#2323 refactor structured errors/logs in pkg
  src/pkg/account/m365.go
  src/pkg/credentials/aws.go
  src/pkg/credentials/corso.go
  src/pkg/credentials/m365.go
  src/pkg/path/onedrive.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/repository/repository.go
  src/pkg/services/m365/m365.go
  src/pkg/storage/common.go
  src/pkg/storage/s3.go
Labels: mergequeue, supportability, tech-debt

#2335 add clues, fault to selectors
  src/cli/backup/exchange.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/go.mod
  src/go.sum
  src/internal/operations/restore.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, supportability, tech-debt

#2336 add clues, fault to small /internal pkgs
  src/internal/common/errors.go
  src/internal/common/slices.go
  src/internal/common/time.go
  src/internal/events/events.go
  src/internal/streamstore/streamstore.go
  src/pkg/backup/details/details.go
  src/pkg/path/onedrive.go
Labels: mergequeue, supportability, tech-debt

#2411 logging standards examples
  src/go.sum
  src/pkg/fault/example_fault_test.go
  src/pkg/logger/example_logger_test.go
  website/docs/developers/logging.md
Labels: documentation, mergequeue

#2400 Pass in prev delta to collectItems cont.
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2421 Update changelog for v0.3.0
  CHANGELOG.md
Labels: mergequeue

#2401 Set DoNotMerge on OneDrive collections if delta token expired
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/support/m365Support.go
Labels: mergequeue

#2417 Use case-insensitive comparison for emails in permission check
  src/internal/connector/graph_connector_helper_test.go
Labels: bug, mergequeue, tests

#2420 Update retry handling for permissions
  src/internal/connector/onedrive/collection.go
Labels: mergequeue

#2424 fix mod file
  src/go.mod
  src/go.sum
Labels: bug, mergequeue

#2414 Remove old code to count number of resource owners backed up
  src/internal/data/data_collection.go
  src/internal/data/data_collection_test.go
Labels: mergequeue, tech-debt

#2364 add fault to repository repository funcs
  src/cli/backup/exchange.go
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/restore/exchange_integration_test.go
  src/cli/utils/testdata/opts.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_load_test.go
Labels: mergequeue, supportability, tech-debt

#2415 Split collection interface
  src/cmd/factory/impl/common.go
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/restore.go
  src/internal/data/data_collection.go
  src/internal/kopia/data_collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, tech-debt

#2422 GC: Item mail attachment Handling
  CHANGELOG.md
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/mockconnector/mock_data_message.go
  src/internal/connector/support/m365Transform.go
  website/docs/support/known-issues.md
Labels: enhancement, restore, mergequeue, upstream, exchange, mail

#2438 Fixed twice display of "Logging to file" line
  src/pkg/logger/logger.go
Labels: mergequeue

#2187 GC: SharePoint: Backup: Abstract / Serialize
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/helper_test.go
Labels: mergequeue, backup

#2439 [Snyk] Security upgrade alpine from 3.16 to 3.17
  build/Dockerfile
Labels: mergequeue

#2365 add fault/clues to kopia, pt 1
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/common.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/restore.go
  src/internal/streamstore/streamstore.go
  src/internal/streamstore/streamstore_test.go
  src/pkg/repository/repository.go
Labels: mergequeue, supportability, tech-debt

#2395 add pathEquals to filter set
  CHANGELOG.md
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
  src/pkg/selectors/selectors.go
Labels: mergequeue, tests

#2434 Add Fetch() to RestoreCollection
  src/cmd/factory/impl/common.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/data/data_collection.go
  src/internal/kopia/data_collection.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/manifests_test.go
  src/internal/operations/restore_test.go
Labels: enhancement, restore, mergequeue

#2375 add fault/clues to the rest of internal/kopia
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store.go
  src/internal/kopia/s3.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/upload.go
  src/pkg/repository/repository.go
Labels: mergequeue, supportability, tech-debt

#2451 Re-enable repository tests
  src/Makefile
  src/pkg/repository/loadtest/repository_load_test.go
Labels: mergequeue

#2435 remove Other Calendars prefix folder
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_vars.go
  src/internal/connector/exchange/service_restore.go
Labels: bug

#2440 support both loc and id folders in reduce
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/kopia/upload.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: restore

#2441 include locationRef in details merger
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: enhancement

#2436 Add `make fmt` for src
  src/Makefile
  src/internal/connector/graph/betasdk/models/horizontal_section_layout_type.go
  src/internal/connector/graph/betasdk/models/page_layout_type.go
  src/internal/connector/graph/betasdk/models/page_promotion_type.go
  src/internal/connector/graph/betasdk/models/section_emphasis_type.go
  src/internal/connector/graph/betasdk/models/site_access_type.go
  src/internal/connector/graph/betasdk/models/site_security_level.go
  src/internal/connector/graph/betasdk/models/title_area_layout_type.go
  src/internal/connector/graph/betasdk/models/title_area_text_alignment_type.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/pkg/logger/example_logger_test.go
  src/pkg/selectors/scopes.go
Labels: mergequeue

#2220 GC: Backup: SharePoint: Pages Connect Pipeline
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/sharepoint/api/api.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/datacategory_string.go
  src/internal/connector/sharepoint/list.go
Labels: mergequeue, backup

#2455 Move stateOf to data
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/data/data_collection.go
  src/internal/data/data_collection_test.go
Labels: mergequeue

#2448 Make order insensitive permission compare
  src/internal/connector/graph_connector_helper_test.go
Labels: bug, mergequeue, tests

#2377 replace multierror with fault in setSites
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cmd/factory/impl/common.go
  src/cmd/getM365/getItem.go
  src/cmd/purge/purge.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/operation.go
  src/internal/operations/restore.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, supportability, tech-debt

#2467 ensure display folder matches location, if possible
  src/internal/kopia/upload.go
  src/internal/operations/backup_test.go
  src/pkg/backup/backup.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/path/path.go
Labels: bug

#2465 GC: Item attachment contact support
  src/internal/common/ptr/pointer.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/mockconnector/mock_data_message.go
  src/internal/connector/support/m365Transform.go
Labels: restore, mergequeue

#2457 Use ids for CollectionsMap for OneDrive
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue

#2475 Treat empty prev delta as invalid
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2476 Handle deletions of collections in delta query
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue

#2468 centralize folder creation and permission setting for OneDrive restore
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: restore, mergequeue, onedrive

#2477 GC: Use of Ptr extension
  src/internal/common/ptr/pointer.go
  src/internal/common/ptr/pointer_test.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/service_restore.go
Labels: good first issue, mergequeue, exchange

#2378 deprecate adder interface for only fault.Errors
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/mock/mock.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, supportability, tech-debt

#2380 adding fault/clues to non-service connector pkgs
  src/internal/connector/discovery/api/users.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/support/status.go
  src/internal/connector/uploadsession/uploadsession.go
  src/pkg/selectors/scopes_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue, supportability, tech-debt

#2381 add fault/clues to exchange data_collections
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup.go
Labels: mergequeue, supportability, tech-debt

#2228 CLI: Restore: SharePoint Pages
  src/cli/backup/sharepoint.go
  src/cli/restore/sharepoint.go
  src/cli/utils/sharepoint.go
  src/internal/connector/graph/betasdk/beta_client.go
Labels: restore, mergequeue, cli

#2469 new temp blog post for our Zune giveaway
  website/blog/2023-2-13-zune.md
  website/blog/images/brown_zune.jpeg
  website/blog/images/cyclical.gif
  website/blog/images/radio_zune.jpeg
  website/blog/images/zune.png
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#2483 hide fault param in Users call
  src/pkg/services/m365/m365.go
Labels: mergequeue

#2382 add fault/clues throughout exchange backup
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph_connector.go
  src/internal/operations/manifests.go
  src/pkg/fault/fault.go
Labels: mergequeue, supportability, tech-debt

#2473 Fix OneDrive permissions not getting backed up
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: mergequeue

#2410 Proof of concept wrapper for suite.Suite
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/tester/integration_runners.go
  src/internal/tester/suite.go
Labels: mergequeue, tests, supportability, tech-debt

#2491 add clues/fault to exchange restore
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/support/status.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
Labels: mergequeue, supportability, tech-debt

#2487 Consolidate/move OneDrive GraphConnector tests
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
Labels: mergequeue, tests

#2511 GC: Restore: Libraries Workflow
  src/cli/restore/sharepoint.go
  src/internal/connector/onedrive/drivesource_string.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue

#2492 add fault & clues to exchange api
  src/cmd/getM365/getItem.go
  src/internal/common/ptr/pointer.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/cache_container.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, supportability, tech-debt

#2501 Set proper state and paths for moves in OneDrive
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/pkg/path/path.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: mergequeue

#2523 centralize observe channel listener handling
  CHANGELOG.md
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
Labels: bug, mergequeue

#2478 Extra test for some recursive delete behavior
  src/internal/kopia/upload_test.go
Labels: mergequeue

#2527 Use suite wrapper in internal/common package
  src/internal/common/buckets_test.go
  src/internal/common/configs_test.go
  src/internal/common/errors_test.go
  src/internal/common/ptr/pointer_test.go
  src/internal/common/slices_test.go
  src/internal/common/time_test.go
Labels: mergequeue, tests, tech-debt

#2514 Update tests in kopia package
  src/internal/kopia/conn_test.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/path_encoder_test.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
Labels: mergequeue, tests, tech-debt

#2518 Deletion related fixes for OneDrive delta incrementals
  src/internal/connector/data_collections.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue

#2537 Check for err in repo connect
  src/pkg/repository/repository.go
Labels: mergequeue

#2541 Remove redundant err check
  src/pkg/repository/repository.go
Labels: mergequeue

#2542 Correctly add CA certificates
  build/Dockerfile
Labels: mergequeue

#2464 some fault err explanation cleanup
  src/pkg/fault/example_fault_test.go
Labels: mergequeue, tech-debt

#2493 update items to accept ctx, fault.Errors
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/graph/metadata_collection_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_collection.go
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/data/data_collection.go
  src/internal/kopia/data_collection.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/manifests_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, supportability, tech-debt

#2522 Disable kopia optimization that lets us reuse a base directory
  src/internal/kopia/upload.go
Labels: bug, mergequeue, backup

#2552 log and continue if kopia can't find expected base snapshot directory
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/tester/config.go
Labels: bug, mergequeue-priority, backup

#2555 Hook into error callback in kopia
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
Labels: bug, mergequeue, backup

#2543 Fix Corso panics in Docker images
  CHANGELOG.md
  build/Dockerfile
Labels: mergequeue

#2504 wrap up clues and fault additions to exchange
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/cache_container.go
  src/internal/connector/exchange/consts.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/graph/api/api.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, supportability, tech-debt

#2561 error logging around malformed urls
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/service.go
Labels: mergequeue

#2547 GC: Ptr clean-up and Invalid NextLink logging
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/graph/api/api.go
  src/internal/connector/graph/api/api_test.go
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2562 Pull in fix for concurrent map updates in clues
  src/go.mod
  src/go.sum
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/uploadsession/uploadsession.go
  src/internal/kopia/model_store.go
  src/internal/kopia/upload.go
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
  src/internal/operations/restore.go
  src/pkg/path/resource_path.go
  src/pkg/repository/repository.go
Labels: mergequeue-priority

#2505 add clues/fault to sharepoint restores
  src/internal/connector/data_collections.go
  src/internal/connector/sharepoint/listInfo.go
  src/internal/connector/sharepoint/pageInfo.go
  src/internal/connector/sharepoint/queries.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue, supportability, tech-debt

#2565 Fix how ErrrorData is marshaled
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
Labels: mergequeue-priority

#2551 Add log messages about metadata saved/used
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/onedrive/collections.go
Labels: mergequeue, backup

#2566 Move Corso to beta
  CHANGELOG.md
  README.md
  website/blog/2022-11-16-corso-announcement-free-backup-for-microsoft-365.md
Labels: mergequeue

#2545 More fine grained error messages for retries
  src/internal/connector/graph/retry_middleware.go
  src/internal/connector/graph/service.go
Labels: mergequeue

#2506 add clues/fault to sharepoint collections
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/list_test.go
Labels: mergequeue, supportability, tech-debt

#2507 add clues/fault to sharepoint api
  src/internal/connector/sharepoint/api/api.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/pageInfo.go
  src/internal/connector/sharepoint/pageInfo_test.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue, supportability, tech-debt

#2574 Update CHANGELOG.md
  CHANGELOG.md
Labels: mergequeue

#2544 Print api response in logs for 4xx errors
  src/internal/connector/graph/service.go
Labels: mergequeue

#2575 Add owner in json output for backup list
  CHANGELOG.md
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
Labels: mergequeue

#2508 Consolidate logic to see if Exchange/OneDrive user exists
  src/internal/connector/data_collections.go
  src/internal/connector/discovery/discovery.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
Labels: mergequeue, supportability, tech-debt

#2568 write test logs to stdout
  .github/workflows/ci.yml
  .github/workflows/load_test.yml
Labels: mergequeue, tests

#2580 CLI: SharePoint --data flag and wildcards
  src/cli/backup/sharepoint.go
Labels: enhancement, mergequeue

#2578 add awareness of missing folders
  CHANGELOG.md
  website/docs/support/known-issues.md
Labels: documentation, mergequeue

#2494 Begin storing OneDrive file names in metadata
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/item.go
Labels: enhancement, mergequeue, backup, onedrive

#2495 New restore path for items with name in metadata file
  src/internal/connector/onedrive/restore.go
Labels: enhancement, mergequeue, backup, onedrive

#2592 Mark v0.4.0 as beta
  CHANGELOG.md
Labels: mergequeue

#2503 Mark collections as Deleted if not available and invalid delta
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2560 Handle files moved multiple times within a delta query
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue

#2557 Add both data and meta file to exclude list
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue

#2533 OneDrive test framework
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
Labels: mergequeue, tests

#2593 Use tester suite wrapper in cli package
  src/cli/backup/exchange_integration_test.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive_integration_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint_integration_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/cli_test.go
  src/cli/config/config_test.go
  src/cli/help/env_test.go
  src/cli/print/print_test.go
  src/cli/repo/s3_integration_test.go
  src/cli/repo/s3_test.go
  src/cli/restore/exchange_integration_test.go
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/exchange_test.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/utils_test.go
Labels: mergequeue, tests, tech-debt

#2530 standardize panic recovery
  src/internal/common/crash/crash.go
  src/internal/common/crash/crash_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: mergequeue, tech-debt

#2596 GC: OneDrive/SharePoint WebURL Fix
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
Labels: bug, mergequeue, backup

#2605 add selector, shortref logging in operations
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue

#2510 add fault.tracker for error additions
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/restore.go
  src/internal/kopia/wrapper.go
  src/internal/operations/manifests.go
  src/internal/operations/restore.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
Labels: mergequeue, tech-debt

#2584 Extract Graph API error details for permissions
  src/internal/connector/onedrive/item.go
Labels: mergequeue, backup, onedrive, supportability

#2612 Update CI domain used for testing
  src/internal/connector/onedrive/drive_test.go
  src/internal/tester/config.go
Labels: mergequeue-priority

#2617 fix url logging
  CHANGELOG.md
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/graph/service.go
Labels: bug, mergequeue

#2509 adding clues & fault to onedrive restore
  src/internal/connector/data_collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue, supportability, tech-debt

#2606 don't handle meta files in details
  CHANGELOG.md
  src/cmd/factory/impl/common.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/version/backup.go
  src/pkg/backup/backup.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/repository/repository.go
Labels: bug, mergequeue

#2458 Update to PR template
  .github/pull_request_template.md
Labels: mergequeue

#2519 Onedrive clean up
  src/internal/connector/data_collections.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
Labels: mergequeue, tech-debt

#2611 GC: Event: Add additional sanitization for restore
  src/internal/connector/support/m365Transform.go
Labels: bug, mergequeue

#2613 Use tester suite wrapper in connector package
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/api/contacts_test.go
  src/internal/connector/exchange/api/events_test.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/api/api_test.go
  src/internal/connector/graph/betasdk/beta_client_test.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/graph/metadata_collection_test.go
  src/internal/connector/graph/service_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_collection_test.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/listInfo_test.go
  src/internal/connector/sharepoint/list_test.go
  src/internal/connector/support/errors_test.go
  src/internal/connector/support/m365Support_test.go
  src/internal/connector/support/m365Transform_test.go
  src/internal/connector/support/status_test.go
  src/internal/connector/uploadsession/uploadsession_test.go
Labels: mergequeue, tests, tech-debt

#2461 GC: Sharepoint: Pages info extended
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/pageInfo.go
  src/internal/connector/sharepoint/pageInfo_test.go
Labels: mergequeue, tech-debt

#2604 Store OneDrive directory metadata in directory
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/version/backup.go
Labels: restore, mergequeue, backup, onedrive

#2624 1970 11 tracker fails redo
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/graph/metadata_collection.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/sharepoint/collection.go
  src/internal/kopia/data_collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/pkg/fault/fault.go
Labels: bug, mergequeue

#2637 Reduce total number of OneDrive tests run
  src/internal/connector/graph_connector_onedrive_test.go
Labels: mergequeue-priority, onedrive, tests, supportability

#2634 CLI: Sharepoint: Set Libraries to default
  src/cli/backup/sharepoint.go
Labels: mergequeue, backup, cli, sharepoint

#2643 don't enable permissions for cli od e2e
  src/cli/backup/onedrive_integration_test.go
Labels: mergequeue, tests

#2641 Revert "⬆️ Bump tw-elements from 1.0.0-alpha13 to 1.0.0-beta1 in /website"
  website/package-lock.json
  website/package.json
Labels: mergequeue

#2512 add clues & fault to onedrive collections
  src/cmd/purge/purge.go
  src/internal/connector/data_collections.go
  src/internal/connector/graph/errors.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/pkg/logger/logger.go
Labels: mergequeue-priority, supportability, tech-debt
