Repository alcionai/corso, pull requests merged in 2023-03, with the labels that each got.

#2676 add flag to output all details
  src/cli/backup/exchange.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_test.go
  src/cli/options/options.go
  src/pkg/control/options.go
Labels: enhancement, mergequeue-priority, backup

#2534 add corso start event at start of cli command
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/cli.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
  src/internal/events/events.go
Labels: blocked, mergequeue

#2700 Log if file tagged as malware by graph
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/drive.go
Labels: mergequeue

#2688 Graph ResyncRequired error can also manifest as resyncRequired
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
Labels: mergequeue

#2690 Corso: Exchange: Details: add parentpath
  src/internal/connector/exchange/exchange_data_collection.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue

#2679 CLI: `SharePoint.Libraries` selector expansion
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/sharepoint.go
  src/cli/utils/utils.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: restore, mergequeue, backup, cli

#2681 CLI: Commands refactor --> List and Details
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
Labels: mergequeue, tech-debt

#2689 Corso: Exchange: Mail: Backup Details to include recipients --JSON ONLY
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/graph/shared.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: enhancement, mergequeue, backup

#2674 Switch to using ids for storing permissions
  CHANGELOG.md
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
Labels: mergequeue

#2717 Only set repo configuration on init
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
Labels: mergequeue

#2711 add fault.item serialization to backup
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
Labels: enhancement, backup

#2712 add item skips to fault
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
Labels: enhancement, backup

#2725 migrate streamstore details to own file
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/internal/streamstore/details.go
  src/internal/streamstore/details_test.go
  src/internal/streamstore/streamstore.go
  src/pkg/repository/repository.go
Labels: mergequeue, tech-debt

#2724 fix test running incorrect suite
  src/internal/operations/backup_test.go
  src/internal/operations/manifests_test.go
Labels: bug, mergequeue

#2726 fix file reference in panics
  src/internal/common/crash/crash.go
Labels: bug, mergequeue

#2589 remove wrap and append support
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/betasdk/beta_client_test.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/retry_middleware.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/queries.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/errors.go
  src/internal/connector/support/errors_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/backup/backup.go
Labels: mergequeue, tech-debt

#2727 Remove Graph call that could cause throttling issues
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue-priority, mergequeue

#2719 avoid events for version command
  src/cli/cli.go
Labels: mergequeue

#2723 refactor streamstore for generic use
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/common.go
  src/internal/operations/restore.go
  src/internal/streamstore/details.go
  src/internal/streamstore/details_test.go
  src/internal/streamstore/mock/details.go
  src/internal/streamstore/streamstore.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/repository/repository.go
Labels: mergequeue, backup, tech-debt

#2703 backup malware catch
  src/internal/connector/graph/errors.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
Labels: enhancement, mergequeue, backup

#2591 remove stats.Errs
  CHANGELOG.md
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/repository/loadtest/repository_load_test.go
Labels: mergequeue, supportability, tech-debt

#2736 selectors use mulit-value short-refs
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: restore, mergequeue, backup

#2705 Improve handling of permissions using sharing field
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
Labels: mergequeue

#2597 remove common errors
  src/internal/common/errors.go
  src/internal/common/errors_test.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue, supportability, tech-debt

#2734 quick refactor for item metadata extensibility
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
Labels: enhancement, backup

#2751 Don't publish docker image for commit to main
  .github/workflows/ci.yml
Labels: mergequeue

#2718 Augment paths for OneDrive restore
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/restore_test.go
  src/internal/operations/restore.go
  src/pkg/backup/details/details.go
  src/pkg/repository/repository.go
Labels: mergequeue

#2710 introduce fault items
  CHANGELOG.md
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/operations/backup.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
Labels: enhancement, mergequeue, backup

#2760 Scope excluded items by prefix
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: bug, mergequeue, backup, onedrive

#2733 GC: OneDrive: Efficient Drive Name Update
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/data_collections_test.go
Labels: mergequeue, backup, onedrive

#2599 add logger CtxErr() qol func
  src/cli/cli.go
  src/cmd/factory/impl/exchange.go
  src/internal/common/crash/crash.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collections.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/pkg/logger/example_logger_test.go
  src/pkg/logger/logger.go
Labels: mergequeue, supportability, tech-debt

#2761 Fix check in sanity test
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#2737 Factor out common code for running backups in CLI layer
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
Labels: mergequeue, backup, onedrive, exchange, sharepoint

#2763 add a QoL path.Build func
  src/cmd/factory/impl/common.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/exchange_data_collection_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph/metadata/metadata_test.go
  src/internal/connector/graph/metadata_collection_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/data/data_collection_test.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/pkg/backup/details/details_test.go
  src/pkg/path/onedrive_test.go
  src/pkg/path/path.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, tech-debt

#2758 Rename folder metadata files to just `.dirmeta`
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/permission.go
  src/internal/version/backup.go
Labels: restore, mergequeue, backup, onedrive

#2767 Post release changelog updates
  CHANGELOG.md
Labels: mergequeue

#2749 Fixup OneDrive selectors for different file names
  src/cli/utils/testdata/opts.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: restore, backup, onedrive, sharepoint

#2762 Data protection gumbo blog
  website/blog/2023-3-13-dataprotection-gumbo.md
  website/blog/authors.yml
  website/blog/images/data_protection_gumbo.png
  website/styles/Microsoft/Acronyms.yml
  website/styles/Vocab/Base/accept.txt
Labels: mergequeue

#2779 look up sp drive by name or ID
  src/internal/connector/onedrive/item.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement

#2780 Add Library flag to sharepoint CLI
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/utils.go
Labels: enhancement, restore, cli

#2784 Fixups for some Exchange CI bugs
  src/internal/connector/graph_connector_helper_test.go
Labels: bug, mergequeue-priority, tests

#2778 Add a helper function that returns site ID and site URL in a `Site` struct
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: mergequeue

#2774 rename libraries -> libraryFolder
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/cli/utils/utils.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: restore, mergequeue, sharepoint

#2771 Fix repo connect error when we don't have a config
  CHANGELOG.md
  src/cli/cli.go
  src/cli/cli_test.go
  src/cli/repo/s3.go
  src/cli/repo/s3_e2e_test.go
Labels: mergequeue

#2787 Make sharepoint cli public
  CHANGELOG.md
  src/cli/backup/sharepoint.go
  src/cli/restore/sharepoint.go
  src/internal/observe/display.go
Labels: mergequeue-priority, mergequeue, cli, sharepoint

#2773 Use ptr package where possible
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/pageInfo.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/attendee.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
  src/internal/connector/support/m365Transform.go
  src/internal/connector/support/m365Transform_test.go
Labels: mergequeue, supportability, tech-debt

#2744 store fault errors produced during backup
  src/internal/operations/backup.go
  src/pkg/backup/backup.go
Labels: enhancement, backup

#2796 ShortRef uniqueness fixup
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, backup, onedrive, sharepoint

#2748 expose listing errors and skipped items in the cli
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/pkg/fault/fault.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
Labels: enhancement, backup, cli

#2496 Change to storing files by ID instead of display name
  src/cli/utils/testdata/opts.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/kopia/upload.go
  src/internal/operations/backup.go
  src/internal/streamstore/details_test.go
  src/internal/version/backup.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: enhancement, mergequeue, backup, onedrive

#2804 Fix item re-download on unauthorized requests
  CHANGELOG.md
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
Labels: mergequeue

#2803 Do not query repo ID if metrics are disabled
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: mergequeue

#2798 Script to set retention for all mailboxes in a tenant
  src/cmd/purge/scripts/setRetention.ps1
Labels: mergequeue

#2811 Skip 404 cli
  CHANGELOG.md
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
Labels: backup, cli

#2805 Skip items returning 404
  CHANGELOG.md
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/kopia/upload.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/item.go
Labels: enhancement, mergequeue-priority, backup, onedrive, cli

#2776 fix sharepoint filter consts
  src/pkg/selectors/sharepoint.go
Labels: bug, restore, mergequeue

#2807 Integrate Exchange retention reset in CI
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#2830 Fix CI-Test-Cleanup workflow definition
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue-priority

#2806 Add option to specify user to run sanity tests with in GHA
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#2648 remove unused test scoping envs
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/config/config_test.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/discovery/discovery_test.go
  src/internal/connector/exchange/api/api_test.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/graph/betasdk/beta_client_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/api/drive_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/list_test.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/tester/suite.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, tests

#2809 add load tester suite
  src/internal/tester/suite.go
  src/internal/tester/suite_test.go
  src/pkg/repository/loadtest/repository_load_test.go
Labels: mergequeue, tests, tech-debt

#2731 add fault errors streamstore
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/utils/testdata/opts.go
  src/cmd/purge/purge.go
  src/go.mod
  src/go.sum
  src/internal/connector/discovery/discovery_test.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/common.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/collectables.go
  src/internal/streamstore/collectables_test.go
  src/internal/streamstore/details.go
  src/internal/streamstore/details_test.go
  src/internal/streamstore/mock/details.go
  src/internal/streamstore/mock/mock.go
  src/internal/streamstore/streamstore.go
  src/pkg/backup/backup.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
  src/pkg/fault/testdata/testdata.go
  src/pkg/path/path.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/store/backup.go
  src/pkg/store/backup_test.go
Labels: enhancement, mergequeue, backup

#2834 add outputs to script
  src/cmd/purge/scripts/foldersAndItems.ps1
  src/cmd/purge/scripts/setRetention.ps1
Labels: mergequeue

#2792 More rigorous email test with repeat folder names
  src/internal/connector/graph_connector_test.go
Labels: mergequeue, tests, tech-debt, exchange

#2833 Backup owner and empty permissions
  CHANGELOG.md
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
Labels: mergequeue

#2821 centralize details, restore flags
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/sharepoint.go
Labels: cli, sharepoint

#2838 --web-url to --site
  src/cli/backup/sharepoint.go
  src/cli/utils/flags.go
Labels: cli, sharepoint

#2852 add 10 day deadline to cli context
  CHANGELOG.md
  src/cli/cli.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
Labels: mergequeue-priority, cli

#2845 Add a test with duplicate item IDs for OneDrive
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue, backup, onedrive, tests

#2837 mark event instance loss as known
  CHANGELOG.md
  website/docs/support/known-issues.md
Labels: documentation, mergequeue-priority

#2642 Enable OneDrive incrementals, disable incrementals for permission backup
  CHANGELOG.md
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, backup, onedrive

#2866 Trying to fix a break in the action format
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue-priority

#2868 Once more cleanup action typo
  .github/actions/purge-m365-user-data/action.yml
Labels: mergequeue

#2848 fixes, logging improvements for fault.Errors
  src/internal/connector/onedrive/collections.go
  src/internal/operations/backup.go
  src/internal/operations/logging.go
  src/internal/operations/restore.go
  src/pkg/backup/backup.go
  src/pkg/fault/fault.go
  src/pkg/repository/repository_unexported_test.go
Labels: bug, mergequeue

#2864 Add option to control parallelism getting items
  src/internal/connector/exchange/exchange_data_collection.go
  src/pkg/control/options.go
Labels: enhancement, mergequeue, backup, exchange

#2870 Adding new OneDrive and Sharepoint CI cleanup
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/exchangePurge.ps1
  src/cmd/purge/scripts/exchangeRetention.ps1
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue

#2881 add supportability to type of change
  .github/pull_request_template.md
Labels: mergequeue

#2824 add labels to logged errors
  src/pkg/logger/logger.go
Labels: mergequeue, supportability, tech-debt

#2879 Add hidden flag to set fetch parallelism for Exchange from CLI
  CHANGELOG.md
  src/cli/backup/exchange.go
  src/cli/options/options.go
Labels: enhancement, mergequeue, backup, cli, exchange

#2886 observe resourceOwner once, at top
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/observe/display.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: enhancement, cli

#2872 Log user name when enumerating drive items
  CHANGELOG.md
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/observe/display.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue

#2888 Handle 503 retries where the `Retry-After` header exceeds what the Graph SDK will wait for
  src/internal/connector/graph/retry_middleware.go
  src/internal/connector/graph/service.go
Labels: mergequeue

#2885 Distinguish CI output between Exchange and OneDrive
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#2842 scopes typing rename, filter -> info
  src/cli/utils/exchange.go
  src/cli/utils/sharepoint.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue

#2874 handle endpoint flag to check http:// or https://
  src/cli/repo/s3.go
Labels: mergequeue

#2889 Add SharePoint CLI docs
  website/sidebars.js
Labels: mergequeue

#2890 Group CLI docs by service for better accessibility
  website/sidebars.js
Labels: mergequeue

#2865 cli: use withTimeout, not withDeadline
  src/cli/cli.go
Labels: mergequeue, tech-debt

#2822 update sharepoint cli examples
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/observe/observe.go
  src/internal/operations/restore_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue-priority, cli, sharepoint

#2901 log item path on restore
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
  src/internal/operations/restore.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, supportability

#2902 logs and log fixes around base manifests
  src/internal/connector/data_collections.go
  src/internal/kopia/snapshot_manager.go
  src/internal/model/model.go
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
Labels: backup, supportability

#2899 Add more logging to middleware and incremental backup operation logic
  src/internal/connector/data_collections.go
  src/internal/connector/graph/service.go
  src/internal/kopia/snapshot_manager.go
  src/internal/model/model.go
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
Labels: bug, mergequeue-priority, mergequeue, supportability

#2905 Update CHANGELOG.md
  CHANGELOG.md
Labels: mergequeue

#2875 Remove global 10 day timeout
  CHANGELOG.md
  src/cli/cli.go
  src/go.mod
  src/go.sum
  src/internal/connector/graph/service.go
  src/internal/connector/graph/service_test.go
Labels: mergequeue

#2904 remove the last use of multierrs
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
Labels: tech-debt

#2903 update backup cli output
  src/cli/backup/backup.go
  src/cli/print/print.go
  src/cli/print/print_test.go
  src/cmd/purge/purge.go
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/observe/observe.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue, tech-debt

#2916 additional logging when creating backup model
  src/internal/connector/exchange/service_iterators.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
Labels: mergequeue, backup, supportability

#2908 Fix permissions restore for version 6
  CHANGELOG.md
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/restore_test.go
Labels: mergequeue

#2912 continue if collection path is nil
  CHANGELOG.md
  src/go.sum
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: bug, mergequeue, backup, onedrive

#2907 Split some CI tests for OneDrive into nightly and regular CI
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/tester/suite.go
  src/internal/tester/suite_test.go
Labels: mergequeue, onedrive, tests, tech-debt

#2918 OneDrive invalid delta set difference
  CHANGELOG.md
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: bug, mergequeue, backup, onedrive

#2911 Assume that item has no attachments if there is no body
  CHANGELOG.md
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/api/api_test.go
Labels: mergequeue-priority, mergequeue

#2929 Always make empty collections for prefix directories
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph/collections.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/sharepoint/data_collections.go
Labels: bug, mergequeue-priority, backup

#2887 PoC for centralized throttling control
  src/cmd/sanity_test/sanity_tests.go
  src/go.mod
  src/go.sum
  src/internal/connector/discovery/api/api.go
  src/internal/connector/discovery/api/beta_service_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/graph/betasdk/beta_client_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/onedrive/api/drive_test.go
  src/internal/connector/onedrive/service_test.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/restore_test.go
Labels: mergequeue, supportability

#2921 introduce the resource owner name to op.backup
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/restore_test.go
  src/pkg/backup/backup.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, backup

#2930 log string, not func
  src/internal/kopia/wrapper.go
Labels: bug, mergequeue

#2706 Revert "force omission of meta files (#2662)"
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  website/docs/support/known-issues.md
Labels: mergequeue

#2670 Add test for check IsMeta flag in OneDrive
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/collection.go
Labels: mergequeue

#2942 Parametrize libraries
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue

#2937 bump clues to add some nil-pointer protection
  src/go.mod
  src/go.sum
Labels: bug, mergequeue-priority

#2816 Sanity test cleanups and additional info
  .github/workflows/load_test.yml
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/sanity_tests.go
  src/pkg/logger/example_logger_test.go
  src/pkg/logger/logger.go
Labels: mergequeue, tests

#2941 move getDrives to onedrive/api, add mock
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/api/drive_test.go
  src/internal/connector/onedrive/api/mock/drive.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/kopia/wrapper.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/tester/config.go
Labels: mergequeue-priority, tests, sharepoint

#2826 Update Exchange backup detail ParentPath when merging details
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, mergequeue, backup, exchange

#2952 Move lib names to envar
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#2954 Set default compressor to zstd-better-compression
  src/internal/kopia/conn.go
Labels: mergequeue, backup

#2935 Add basic RestoreAndBackup test for SharePoint
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
Labels: mergequeue, tests, tech-debt

#2953 Update to head of kopia for compression
  CHANGELOG.md
  src/go.mod
  src/go.sum
Labels: bug, mergequeue, backup

#2962 fix sharepoint library folder selection
  CHANGELOG.md
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/internal/operations/restore.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: bug, restore, mergequeue-priority, sharepoint

#2813 CI job to run unit tests without env vars
  .github/workflows/ci.yml
Labels: mergequeue, tests, supportability, tech-debt

#2956 File name compare
  src/internal/connector/graph_connector_helper_test.go
Labels: mergequeue, onedrive, tests, tech-debt, sharepoint

#2884 metrics PoC for github.com/armon/go-metrics
  src/cli/cli.go
  src/cmd/factory/impl/common.go
  src/go.mod
  src/go.sum
  src/internal/connector/graph/service.go
  src/internal/events/events.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/logger/logger.go
Labels: mergequeue, supportability

#2928 Re-enable import order linting
  src/.golangci.yml
  src/cmd/purge/purge.go
  src/internal/connector/graph/betasdk/beta_client_test.go
  src/internal/connector/graph/shared.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/api/mock/drive.go
  src/internal/streamstore/mock/mock.go
  src/internal/tester/suite_test.go
Labels: bug, mergequeue, supportability, tech-debt

#2972 avoid segfaults in metrics middleware
  src/internal/connector/graph/service.go
Labels: bug, mergequeue-priority

#2960 correct input aliasing
  src/internal/connector/data_collections.go
  src/internal/connector/discovery/api/beta_service.go
  src/internal/connector/discovery/api/users.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/service.go
  src/internal/connector/graph_connector.go
  src/internal/connector/mockconnector/mock_data_list.go
  src/internal/connector/mockconnector/mock_data_message.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/queries.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/m365Support.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/selectors/scopes.go
Labels: mergequeue, tech-debt

#2961 update clues to latest
  src/go.mod
  src/go.sum
Labels: mergequeue, dependencies

#2971 increase ci test timeout from 10 to 15 minutes
  .github/workflows/ci.yml
Labels: mergequeue, tests

#2963 Get the cleanup working again
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#2966 Remove usages of ::set-output in Github Actions
  .github/actions/go-setup-cache/action.yml
  .github/workflows/_filechange_checker.yml
  .github/workflows/ci.yml
Labels: mergequeue, supportability, github_actions

#2828 Populate location in Exchange container resolver
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/cache_container.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, backup, exchange

#2967 Re add --restore-permissions flag
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint_test.go
Labels: mergequeue

#2965 Integration test for permissions changes
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue

#2959 add linter for using clues to create and wrap errs
  src/.golangci.yml
  src/internal/connector/discovery/discovery.go
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/options.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/support/m365Transform.go
  src/pkg/fault/fault_test.go
  src/pkg/selectors/selectors.go
Labels: mergequeue, tech-debt

#2923 move graph connector creation to new op
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/operation.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository.go
Labels: restore, mergequeue, backup

#2978 Fix flags for Exchange and OneDrive
  CHANGELOG.md
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/cli.go
  src/cli/config/config.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/exchange.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/flags.go
Labels: bug, mergequeue, cli

#2974 Bump aws-actions/configure-aws-credentials
  .github/actions/publish-website/action.yml
Labels: mergequeue

#2986 Do not try to call syscall.Kill on Windows
  src/internal/events/events.go
  src/internal/events/events_signal_unix.go
  src/internal/events/events_signal_windows.go
Labels: mergequeue

#2990 cli naming readability and clarification
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/exchange.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/testdata/flags.go
  src/cli/utils/testdata/opts.go
Labels: mergequeue, tech-debt

#2992 CI Cleanup improvements
  .github/actions/purge-m365-user-data/action.yml
  .github/workflows/ci_test_cleanup.yml
  src/cmd/purge/scripts/exchangePurge.ps1
Labels: mergequeue

#2925 Skip large OneNote items that cannot be downloaded
  CHANGELOG.md
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/fault/item.go
Labels: mergequeue

#2933 fix circular ref from prior change
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_connector.go
  src/internal/data/metrics.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
Labels: bug

#2932 replace graphConnector with interface
  src/cmd/factory/impl/common.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mockconnector/mock_data_connector.go
  src/internal/data/metrics.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/operation.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup

#2997 remove model.StableID from repository iface
  src/cli/backup/backup.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/utils/testdata/opts.go
  src/pkg/repository/repository.go
Labels: enhancement, restore, mergequeue, backup

#2993 add clues.Hide to replace observe.PII
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: mergequeue, supportability, tech-debt

#2969 restrict sharepoint test backups to test folders
  src/cli/backup/sharepoint_e2e_test.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/selectors/testdata/sharepoint.go
Labels: mergequeue, tests, sharepoint
