Repository alcionai/corso, pull requests merged in 2023-08, with the labels that each got.

#3928 Sanity tests for SharePoint export
  .github/actions/backup-restore-test/action.yml
  src/cmd/sanity_test/export/sharepoint.go
  src/cmd/sanity_test/sanity_tests.go
Labels: mergequeue, tests

#3939 fix loop in restore config conceal
  src/pkg/control/restore.go
  src/pkg/control/restore_test.go
Labels: bug, mergequeue

#3904 introduce backupProducerConfig
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/backup.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/graph/service.go
  src/internal/m365/mock/connector.go
  src/internal/m365/onedrive/backup.go
  src/internal/m365/onedrive/backup_test.go
  src/internal/m365/sharepoint/backup.go
  src/internal/m365/sharepoint/backup_test.go
  src/internal/operations/backup.go
  src/internal/operations/inject/containers.go
  src/internal/operations/inject/inject.go
Labels: mergequeue, tech-debt

#3919 Export data from OD/SP in logevity tests
  .github/workflows/longevity_test.yml
Labels: mergequeue, tests, export

#3923 Create S3 retention checker
  src/cmd/s3checker/pkg/s3/s3.go
  src/cmd/s3checker/s3checker.go
Labels: mergequeue, tests, kopia

#3952 Switch to shorter-lived assume-role credentials
  .github/workflows/longevity_test.yml
Labels: ci

#3944 Switch bucket the test runs in
  .github/workflows/longevity_test.yml
Labels: mergequeue, ci

#3958 Use updated version of kopia that has proper in-memory caching
  src/go.mod
  src/go.sum
  src/internal/kopia/wrapper_test.go
Labels: bug, mergequeue, kopia

#3884 centralize graph api panic and conn retry
  src/internal/common/crash/crash.go
  src/internal/m365/graph/betasdk/beta_client.go
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/graph/http_wrapper_test.go
  src/internal/m365/graph/service.go
  src/internal/m365/graph/service_test.go
  src/internal/m365/sharepoint/api/beta_service.go
Labels: enhancement, mergequeue, msgraph

#3880 sweeping package update
  src/cli/cli.go
  src/cli/print/print.go
  src/cli/print/print_test.go
  src/go.mod
  src/go.sum
  src/internal/kopia/merge_collection.go
  src/internal/kopia/upload.go
  src/internal/m365/exchange/collection.go
  src/internal/m365/onedrive/collections.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/sharepoint/backup.go
  src/internal/m365/sharepoint/collection.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/export.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: mergequeue, tech-debt

#3945 Adjust longevity test backup retention
  .github/workflows/longevity_test.yml
Labels: mergequeue, ci

#3964 Fix sending slack message on failure
  .github/workflows/longevity_test.yml
Labels: bug, mergequeue, ci

#3965 Add some tests for extending object lock duration
  src/internal/kopia/wrapper_test.go
Labels: mergequeue, tests, kopia

#3961 Move advanced restore tests to nightly
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/onedrive_test.go
  src/internal/operations/test/sharepoint_test.go
Labels: mergequeue, tests, ci

#3932 Add hidden flags for setting retention during repo init
  src/cli/flags/retention.go
  src/cli/repo/s3.go
  src/cli/utils/retention.go
  src/cli/utils/retention_test.go
  src/pkg/control/repository/repo.go
  src/pkg/control/repository/retentionmode_string.go
Labels: mergequeue, cli, tests

#3941 threadsafe maps in restore caches
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/permission.go
  src/internal/m365/onedrive/permission_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_caches.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/operations/test/onedrive_test.go
Labels: bug, mergequeue

#3967 comment out sharepoint and onedrive export longevity
  .github/workflows/longevity_test.yml
Labels: mergequeue, tests

#3969 Check for backups using PITR in corso
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, ci

#3968 Add S3 retention checker to longevity test
  .github/workflows/longevity_test.yml
Labels: mergequeue, ci

#3972 split details into multiple files
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/entry.go
  src/pkg/backup/details/exchange.go
  src/pkg/backup/details/folder.go
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/backup/details/onedrive.go
  src/pkg/backup/details/sharepoint.go
Labels: tech-debt

#3977 Remove redundant S3 bucket cleanup
  .github/workflows/weekly_cleanup.yml
Labels: mergequeue, ci

#3971 add basic groups boilerplate
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/groups/backup.go
  src/internal/m365/groups/restore.go
  src/internal/m365/sharepoint/backup.go
  src/internal/m365/sharepoint/backup_test.go
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/entry.go
  src/pkg/backup/details/exchange.go
  src/pkg/backup/details/folder.go
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/backup/details/model.go
  src/pkg/backup/details/onedrive.go
  src/pkg/backup/details/sharepoint.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/service_string.go
Labels: enhancement, mergequeue

#3985 Common structs/mocks/consts for assist backups
  src/internal/kopia/backup_bases.go
  src/internal/kopia/mock_backup_base.go
  src/internal/model/model.go
Labels: mergequeue, backup

#3947 Plug connection reset wrapper into OneDrive code
  src/internal/common/readers/retry_handler.go
  src/internal/common/readers/retry_handler_test.go
  src/internal/m365/onedrive/item.go
  src/internal/m365/onedrive/item_test.go
Labels: bug, mergequeue, backup, onedrive

#3995 Remove unused code and tests
  src/internal/m365/onedrive/item_collector.go
  src/internal/m365/onedrive/item_collector_test.go
Labels: bug, mergequeue-priority, onedrive, tests

#3979 Backup list filtering
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, ux

#3962 Use modTime in details merging
  src/internal/kopia/merge_details.go
  src/internal/kopia/merge_details_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
Labels: mergequeue, backup

#3983 SDK option and logic to drop assist bases
  src/internal/operations/backup.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/pkg/control/options.go
Labels: mergequeue, backup

#3907 Return assist backup models during base selection process
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/operations/manifests.go
Labels: mergequeue, backup

#3994 test http2 stream errors, update client options
  src/go.sum
  src/internal/m365/graph/http_wrapper.go
  src/internal/m365/graph/http_wrapper_test.go
  src/internal/m365/graph/mock/service.go
  src/internal/m365/graph/service.go
  src/internal/m365/graph/service_test.go
Labels: mergequeue, tests

#3996 move kopia.Reasoner to new package
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/backup/identity/identity.go
Labels: mergequeue, tech-debt

#3997 selectors cleanup
  src/cli/backup/sharepoint_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/selectors_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, tech-debt

#3963 Update backup details merge logic
  src/internal/data/data_collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/test/onedrive_test.go
Labels: mergequeue, backup

#3905 Persist backup models for assist backups
  src/internal/operations/backup.go
  src/internal/operations/helpers.go
  src/pkg/backup/backup.go
  src/pkg/backup/details/builder.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, backup

#3987 Integration tests for assist backups
  src/internal/kopia/wrapper_test.go
  src/internal/m365/mock/collection.go
  src/internal/m365/onedrive/mock/item.go
  src/internal/operations/backup_test.go
Labels: mergequeue, backup, tests

#4001 Skip item if metadata fetch fails with 404
  src/internal/m365/onedrive/collection.go
  src/pkg/services/m365/api/drive.go
Labels: mergequeue, msgraph

#4014 Fix circular dependency for store interface
  src/internal/kopia/base_finder.go
  src/internal/kopia/model_store.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/common.go
  src/internal/operations/export.go
  src/internal/operations/export_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/operation.go
  src/internal/operations/operation_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/restore_helper_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/store/backup.go
  src/pkg/store/backup_test.go
  src/pkg/store/store.go
Labels: mergequeue, supportability, tech-debt

#4004 Remove updated field from details
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/service/exchange/restore.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/backup/details/builder.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/entry.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, supportability, tech-debt

#3966 rename data pkg Stream to Item
  src/internal/data/collection.go
  src/internal/data/collection_test.go
  src/internal/data/implementations.go
  src/internal/data/mock/collection.go
  src/internal/kopia/data_collection.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/merge_collection.go
  src/internal/kopia/merge_collection_test.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/collection.go
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/metadata/metadata.go
  src/internal/m365/collection/drive/restore.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/restore.go
  src/internal/m365/graph/collections.go
  src/internal/m365/graph/metadata_collection.go
  src/internal/m365/graph/metadata_collection_test.go
  src/internal/m365/helper_test.go
  src/internal/m365/mock/collection.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/exchange/backup_test.go
  src/internal/m365/service/exchange/collection.go
  src/internal/m365/service/exchange/collection_test.go
  src/internal/m365/service/exchange/mock/collections.go
  src/internal/m365/service/exchange/mock/mock_test.go
  src/internal/m365/service/exchange/restore.go
  src/internal/m365/service/onedrive/export.go
  src/internal/m365/service/onedrive/export_test.go
  src/internal/m365/service/onedrive/mock/item.go
  src/internal/m365/service/onedrive/stub/stub.go
  src/internal/m365/service/sharepoint/api/pages.go
  src/internal/m365/service/sharepoint/mock/list.go
  src/internal/m365/stub/stub.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests_test.go
  src/internal/operations/test/helper_test.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, tech-debt

#4006 move selectorsToReason into selectors
  src/internal/operations/backup.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/reasons.go
  src/pkg/selectors/reasons_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
Labels: mergequeue, tech-debt

#4007 small paths code rearrangement
  src/internal/kopia/base_finder.go
  src/internal/kopia/upload_test.go
  src/internal/m365/graph/collections.go
  src/internal/m365/graph/collections_test.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/test/exchange_test.go
  src/internal/operations/test/onedrive_test.go
  src/pkg/path/builder.go
  src/pkg/path/builder_test.go
  src/pkg/path/category_type.go
  src/pkg/path/drive.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/path/resource_path.go
  src/pkg/path/service_type.go
  src/pkg/selectors/reasons.go
Labels: mergequeue, tech-debt

#4011 Split exchange collection from service
  src/internal/m365/collection/exchange/attachment.go
  src/internal/m365/collection/exchange/attendees.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/exchange/cache_container.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/exchange/collection_test.go
  src/internal/m365/collection/exchange/consts.go
  src/internal/m365/collection/exchange/contacts_backup.go
  src/internal/m365/collection/exchange/contacts_container_cache.go
  src/internal/m365/collection/exchange/contacts_restore.go
  src/internal/m365/collection/exchange/contacts_restore_test.go
  src/internal/m365/collection/exchange/container_resolver.go
  src/internal/m365/collection/exchange/container_resolver_test.go
  src/internal/m365/collection/exchange/events_backup.go
  src/internal/m365/collection/exchange/events_container_cache.go
  src/internal/m365/collection/exchange/events_instance_restore.go
  src/internal/m365/collection/exchange/events_restore.go
  src/internal/m365/collection/exchange/events_restore_test.go
  src/internal/m365/collection/exchange/handlers.go
  src/internal/m365/collection/exchange/helper_test.go
  src/internal/m365/collection/exchange/mail_backup.go
  src/internal/m365/collection/exchange/mail_container_cache.go
  src/internal/m365/collection/exchange/mail_container_cache_test.go
  src/internal/m365/collection/exchange/mail_restore.go
  src/internal/m365/collection/exchange/mail_restore_test.go
  src/internal/m365/collection/exchange/metadata.go
  src/internal/m365/collection/exchange/restore.go
  src/internal/m365/collection/exchange/restore_test.go
  src/internal/m365/collection/exchange/transform.go
  src/internal/m365/collection/exchange/transform_test.go
  src/internal/m365/service/exchange/backup.go
  src/internal/m365/service/exchange/restore.go
  src/internal/m365/service/exchange/testdata/handlers.go
  src/internal/operations/test/exchange_test.go
Labels: mergequeue

#4021 Allow deleting batches of models/manifests
  src/internal/kopia/model_store.go
  src/internal/kopia/model_store_test.go
  src/pkg/store/backup.go
  src/pkg/store/mock/model_store.go
Labels: mergequeue, perf, tech-debt, deletion

#4023 Batch deletion of individual backup components
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/streamstore/streamstore.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
  src/pkg/store/backup.go
  src/pkg/store/mock/wrapper.go
Labels: mergequeue, perf, tech-debt, deletion

#4026 SDK support for multi-backup deletion
  src/cli/backup/backup.go
  src/cmd/longevity_test/longevity.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, perf, tech-debt, deletion

#4032 Print the point in time being used
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, tests, supportability, ci

#4038 Don't fail deletion on missing backups
  src/cli/backup/backup.go
  src/cmd/longevity_test/longevity.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
  src/pkg/repository/repository_unexported_test.go
Labels: mergequeue, perf, deletion

#4037 Retry unexpected EOF errors
  src/internal/common/readers/retry_handler.go
  src/internal/common/readers/retry_handler_test.go
Labels: mergequeue, msgraph

#3850 teams discovery API
  src/internal/operations/opstatus_string.go
  src/internal/tester/tconfig/config.go
  src/internal/tester/tconfig/protected_resources.go
  src/pkg/path/service_type.go
  src/pkg/path/servicetype_string.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/helper_test.go
Labels: mergequeue

#4042 Increase nightly test timeout from 15m to 1h
  .github/workflows/nightly_test.yml
Labels: mergequeue, ci

#4009 Don't munge drive-based ShortRefs
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: mergequeue, backup, onedrive, tech-debt, sharepoint

#4013 remove fetchbynamer from nofetch collection
  src/internal/data/implementations.go
Labels: mergequeue, tech-debt

#4067 Remove call to PITR backup check
  src/cmd/longevity_test/longevity.go
Labels: bug, mergequeue, tests, upstream, ci

#4057 add groups and teams flags boilerplate
  src/cli/backup/groups.go
  src/cli/backup/teams.go
  src/cli/flags/groups.go
  src/cli/flags/teams.go
Labels: cli, teams, groups

#4056 add teams and groups restore and utils
  src/cli/backup/groups.go
  src/cli/backup/teams.go
  src/cli/flags/groups.go
  src/cli/flags/teams.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/restore/teams.go
  src/cli/restore/teams_test.go
  src/cli/utils/groups.go
  src/cli/utils/teams.go
Labels: cli, teams, groups

#4053 add the groups resources service addition
  src/internal/tester/tconfig/protected_resources.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/groups.go
  src/pkg/services/m365/groups_test.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: enhancement, mergequeue

#4054 Updated teams cli addition
  src/cli/backup/backup.go
  src/cli/backup/groups.go
  src/cli/backup/groups_test.go
  src/cli/backup/teams.go
  src/cli/backup/teams_test.go
  src/cli/flags/groups.go
  src/cli/flags/teams.go
  src/cli/restore/groups.go
  src/cli/restore/groups_test.go
  src/cli/restore/teams.go
  src/cli/restore/teams_test.go
  src/cli/utils/groups.go
  src/cli/utils/teams.go
  src/cli/utils/utils.go
  src/pkg/path/service_type.go
Labels: mergequeue, cli, teams

#4046 remove all uses of iota
  src/internal/data/implementations.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/metadata/permissions.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/collection/site/backup_test.go
  src/internal/m365/collection/site/collection.go
  src/internal/m365/collection/site/collection_test.go
  src/internal/m365/collection/site/datacategory_string.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/m365/support/status.go
  src/internal/model/model.go
  src/internal/operations/operation.go
  src/pkg/account/account.go
  src/pkg/backup/details/iteminfo.go
  src/pkg/control/repository/repo.go
  src/pkg/path/category_type.go
  src/pkg/path/service_type.go
  src/pkg/path/servicetype_string.go
  src/pkg/selectors/selectors.go
  src/pkg/storage/storage.go
Labels: mergequeue, tech-debt

#4076 Fix log output and don't fail fast
  .github/workflows/nightly_test.yml
Labels: mergequeue, ci

#4069 Teams groups export cli
  src/cli/backup/groups.go
  src/cli/backup/teams.go
  src/cli/export/export.go
  src/cli/export/groups.go
  src/cli/export/groups_test.go
  src/cli/export/onedrive.go
  src/cli/export/sharepoint.go
  src/cli/export/teams.go
  src/cli/export/teams_test.go
  src/cli/restore/groups.go
  src/cli/restore/teams.go
Labels: mergequeue, cli, teams, groups

#4071 add groups selectors for channels and messages
  src/pkg/path/category_type.go
  src/pkg/path/categorytype_string.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
Labels: enhancement, mergequeue, groups

#4051 Basic code for backup cleanup
  src/internal/kopia/base_finder.go
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/cleanup_backups_test.go
  src/internal/kopia/conn.go
Labels: enhancement, mergequeue, kopia, maintenance

#4065 Add and populate mod time for BaseModel
  src/internal/kopia/model_store.go
  src/internal/kopia/model_store_test.go
  src/internal/model/model.go
Labels: mergequeue, kopia

#4066 Exclude recently created models from garbage collection
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/cleanup_backups_test.go
Labels: mergequeue, kopia, maintenance

#4074 Reduce $select parameters for URL cache delta queries
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/pkg/services/m365/api/config.go
Labels: mergequeue, perf, msgraph

#4030 Create backup collections for Group's default SharePoint site
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/controller.go
  src/internal/m365/resource/resource.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/tester/tconfig/config.go
  src/pkg/path/builder.go
  src/pkg/path/category_type.go
  src/pkg/path/elements.go
  src/pkg/path/resource_path_test.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/selectors.go
  src/pkg/services/m365/api/groups.go
  src/pkg/services/m365/api/groups_test.go
Labels: enhancement, mergequeue, backup, teams

#4080 Refactor backup cleanup test code slightly
  src/internal/kopia/cleanup_backups_test.go
Labels: mergequeue, tests, supportability

#4050 add handlers for channels
  src/internal/m365/collection/groups/handler.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager.go
Labels: mergequeue

#4082 add boilerplate groups backup collection
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/collection.go
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/collection.go
  src/internal/m365/collection/groups/handler.go
  src/internal/m365/collection/groups/handlers.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/item_pager.go
Labels: mergequeue, backup, groups

#4089 Update kopia version
  src/go.mod
  src/go.sum
Labels: mergequeue, kopia

#4092 add channel message item info to details
  src/pkg/backup/details/groups.go
  src/pkg/backup/details/iteminfo.go
Labels: mergequeue, teams, groups

#4090 Reenable point-in-time longevity test
  src/cmd/longevity_test/longevity.go
Labels: mergequeue, tests, ci

#4087 Shuffle around logic for details merging
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/entry.go
Labels: bug, mergequeue, backup, supportability

#4102 add groups operations v0 backup test
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/pkg/selectors/testdata/groups.go
Labels: mergequeue, backup, tests, groups

#4099 add sanity test boilerplate for groups
  .github/actions/backup-restore-test/action.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests, teams, groups

#4104 fix conditional check on restore-args
  .github/actions/backup-restore-test/action.yml
Labels: bug, mergequeue-priority, ci

#4100 cleanup backup e2e in prep for groups
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/help_e2e_test.go
  src/cli/backup/helpers_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
Labels: mergequeue, cli, tests, tech-debt

#4106 check for zero len string with 0
  .github/actions/backup-restore-test/action.yml
Labels: bug, mergequeue

#4068 channels and messages API
  src/internal/m365/collection/groups/handlers.go
  src/pkg/services/m365/api/channels.go
  src/pkg/services/m365/api/channels_pager_test.go
Labels: mergequeue

#4114 Use interface for test helper functions
  src/internal/kopia/conn_test.go
  src/internal/tester/context.go
  src/internal/tester/tester.go
  src/pkg/repository/repository_test.go
  src/pkg/storage/testdata/storage.go
Labels: mergequeue, tests, supportability

#4093 add channels info filters to selectors
  src/pkg/backup/details/groups.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/groups.go
  src/pkg/selectors/groups_test.go
Labels: mergequeue, teams, groups

#4113 Minor log fixups for snapshots
  src/internal/kopia/upload.go
  src/internal/operations/backup.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, supportability

#4081 Cleanup old assist bases
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/cleanup_backups_test.go
Labels: mergequeue, kopia, maintenance

#4118 remove non-generic api duplicates
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: tech-debt, msgraph

#4128 hide groups/teams cli behind env
  .github/workflows/ci.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  src/cli/backup/backup.go
  src/cli/export/export.go
  src/cli/restore/restore.go
Labels: mergequeue-priority, mergequeue, cli

#4088 unify api pager interfaces
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/restore_test.go
  src/internal/m365/collection/drive/url_cache.go
  src/internal/m365/collection/drive/url_cache_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/mock/drive_pager.go
  src/pkg/services/m365/api/mock/pager.go
Labels: mergequeue, tech-debt, msgraph

#4138 v0.12.0 Changelog
  CHANGELOG.md
Labels: mergequeue-priority

#4137 Tighten checks for assist base garbage collection
  src/internal/kopia/cleanup_backups.go
  src/internal/kopia/cleanup_backups_test.go
Labels: mergequeue, kopia, maintenance

#4144 Fix data clobbering issue when getting Quota Exceeded status
  CHANGELOG.md
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
Labels: bug, mergequeue, backup, exchange

#4147 Update docker builder to go 1.20
  build/Dockerfile
Labels: mergequeue-priority

#4149 Update CHANGELOG.md for v0.12.0
  CHANGELOG.md
Labels: mergequeue

#4135 add channel and messages enumerators
  src/internal/m365/collection/groups/backup.go
  src/internal/m365/collection/groups/handlers.go
  src/pkg/services/m365/api/channels_pager.go
  src/pkg/services/m365/api/channels_pager_test.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/contacts_test.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/groups_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/lists_test.go
  src/pkg/services/m365/api/mail_pager_test.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/users_test.go
Labels: mergequeue, msgraph, teams

#4159 Longevity test updates
  .github/workflows/longevity_test.yml
Labels: mergequeue, ci

#4153 Use Libraries prefix when exporting SharePoint files
  CHANGELOG.md
  src/internal/m365/service/sharepoint/export.go
  src/internal/m365/service/sharepoint/export_test.go
Labels: mergequeue, sharepoint, export

#4155 Use path prefixes for backup paths
  src/internal/m365/collection/drive/collection_test.go
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_collector_test.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/item_handler_test.go
  src/internal/m365/collection/drive/item_test.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/drive/library_handler_test.go
  src/internal/m365/service/groups/backup.go
  src/internal/m365/service/onedrive/backup.go
  src/internal/m365/service/onedrive/consts/consts.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/m365/service/sharepoint/backup.go
  src/internal/m365/service/sharepoint/backup_test.go
  src/pkg/path/builder.go
  src/pkg/path/builder_test.go
Labels: mergequeue, backup

#4124 Do not print completed header if no backups
  src/cli/backup/backup.go
Labels: mergequeue

#4156 Metadata related path changes
  src/internal/m365/collection/drive/collections.go
  src/internal/m365/collection/drive/collections_test.go
  src/internal/m365/collection/drive/group_handler.go
  src/internal/m365/collection/drive/handlers.go
  src/internal/m365/collection/drive/item_handler.go
  src/internal/m365/collection/drive/library_handler.go
  src/internal/m365/collection/exchange/backup.go
  src/internal/m365/collection/exchange/backup_test.go
  src/internal/m365/collection/site/backup.go
  src/internal/m365/graph/metadata_collection.go
  src/internal/m365/graph/metadata_collection_test.go
  src/internal/m365/service/onedrive/mock/handlers.go
  src/internal/operations/backup_test.go
Labels: mergequeue, backup

#4126 Update test helpers for groups backup
  src/internal/operations/test/group_test.go
  src/internal/operations/test/helper_test.go
  src/internal/operations/test/restore_helper_test.go
Labels: mergequeue, backup, tests, groups

#4115 Use a larger data chunk to test compression
  src/internal/kopia/wrapper_test.go
Labels: mergequeue, tests, tech-debt, kopia

#4170 bump golang to v1.21
  CHANGELOG.md
  build/Dockerfile
  src/go.mod
  src/go.sum
Labels: mergequeue, go
