Repository alcionai/corso, pull requests merged in 2023-06, with the labels that each got.

#3544 remove the golang purge script
  src/cmd/purge/purge.go
Labels: mergequeue, tech-debt

#3549 updating gitignore to catch log files
  .gitignore
  src/.gitignore
Labels: mergequeue

#3546 minor logging updates
  src/internal/connector/graph/middleware.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
Labels: mergequeue, supportability

#3551 Exchange cleanup improvements
  src/cmd/purge/scripts/exchangePurge.ps1
Labels: mergequeue

#3556 Ensure calling `Details()` twice does not duplicate folder names
  CHANGELOG.md
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, mergequeue, backup

#3456 refactor exchange restore to use interfaces
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/contacts_backup.go
  src/internal/connector/exchange/contacts_restore.go
  src/internal/connector/exchange/contacts_restore_test.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/events_backup.go
  src/internal/connector/exchange/events_restore.go
  src/internal/connector/exchange/events_restore_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/handlers.go
  src/internal/connector/exchange/mail_backup.go
  src/internal/connector/exchange/mail_restore.go
  src/internal/connector/exchange/mail_restore_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/exchange/testdata/handlers.go
  src/internal/connector/exchange/transform.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/service.go
  src/internal/operations/backup_integration_test.go
  src/pkg/path/path.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
Labels: restore, mergequeue, tech-debt, exchange

#3492 Parallelize restores within a collection for OneDrive
  CHANGELOG.md
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/concurrency_middleware.go
  src/internal/connector/graph/consts.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/restore.go
  src/internal/observe/observe.go
  src/internal/observe/observe_test.go
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/pkg/repository/repository.go
Labels: restore, mergequeue, onedrive, perf, sharepoint

#3534 Refactor downloadItem
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue, onedrive, msgraph

#3567 Update changelog for v0.9.0
  CHANGELOG.md
Labels: mergequeue

#3573 Add structured data for the Corso website
  website/src/pages/index.js
Labels: mergequeue

#3572 Fix broken blog link
  website/blog/2023-05-12-incrementals-pt1.md
Labels: mergequeue

#3592 Don't dump response body while checking for malware
  src/internal/connector/graph/errors.go
Labels: bug, mergequeue

#3577 Fix time format for M365DateTimeTimeZone
  src/internal/common/dttm/dttm.go
Labels: bug, mergequeue, msgraph

#3560 Retry on econnreset regardless of http response
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/middleware_test.go
Labels: bug, mergequeue, msgraph

#3594 Use mergequeue for dependabot auto merges
  .github/workflows/auto-merge.yml
Labels: mergequeue

#3563 cetnralize restoreConfig
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cmd/factory/impl/common.go
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/contacts_restore_test.go
  src/internal/connector/exchange/events_restore_test.go
  src/internal/connector/exchange/mail_restore_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test_helper.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/graph_connector_test_helper.go
  src/internal/connector/mock/connector.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/url_cache_test.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/tester/restore_destination.go
  src/pkg/control/collisionpolicy_string.go
  src/pkg/control/options.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: restore, mergequeue

#3595 Add struct functions for backup bases
  src/internal/kopia/backup_bases.go
  src/internal/kopia/backup_bases_test.go
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/mock_backup_base.go
Labels: mergequeue, backup, tech-debt

#3601 ensure backup/restore naming standards in m365
  src/internal/m365/backup.go
  src/internal/m365/backup_test.go
  src/internal/m365/exchange/backup.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/exchange/collection.go
  src/internal/m365/exchange/collection_test.go
  src/internal/m365/exchange/contact_container_cache.go
  src/internal/m365/exchange/contacts_backup.go
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/container_resolver_test.go
  src/internal/m365/exchange/data_collections.go
  src/internal/m365/exchange/data_collections_test.go
  src/internal/m365/exchange/event_container_cache.go
  src/internal/m365/exchange/events_backup.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/folder_resolver_test.go
  src/internal/m365/exchange/iterators_test.go
  src/internal/m365/exchange/mail_backup.go
  src/internal/m365/exchange/mail_container_cache.go
  src/internal/m365/exchange/mail_container_cache_test.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/onedrive/backup.go
  src/internal/m365/onedrive/backup_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/backup.go
  src/internal/m365/sharepoint/backup_test.go
  src/internal/m365/sharepoint/list_info.go
  src/internal/m365/sharepoint/list_info_test.go
  src/internal/m365/sharepoint/restore.go
Labels: tech-debt

#3597 bump clues to latest
  src/go.mod
  src/go.sum
Labels: mergequeue, dependencies

#3609 Update to go 1.20
  src/go.mod
  src/internal/m365/exchange/mock/collections.go
Labels: mergequeue

#3598 auto-log recoverable errors with stack
  src/internal/kopia/data_collection.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/m365/exchange/backup.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/exchange/collection.go
  src/internal/m365/exchange/container_resolver.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/graph/collections.go
  src/internal/m365/onedrive/backup.go
  src/internal/m365/onedrive/collection.go
  src/internal/m365/onedrive/collections.go
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/drive.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/sharepoint/api/pages.go
  src/internal/m365/sharepoint/backup.go
  src/internal/m365/sharepoint/collection.go
  src/internal/m365/sharepoint/list.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/helpers_test.go
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/streamstore/collectables_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/logger/logger.go
  src/pkg/repository/repository.go
  src/pkg/selectors/scopes.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, supportability

#3607 Skip any attachment fetches that fail with OLE conversion error
  CHANGELOG.md
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/mail.go
Labels: mergequeue

#3616 fix restore func misnaming in onedrive
  src/internal/m365/onedrive/restore.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/restore.go
Labels: mergequeue, tech-debt

#3612 final cleanup for renaming/movement
  src/cmd/factory/impl/common.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/contacts_container_cache.go
  src/internal/m365/exchange/events_container_cache.go
  src/internal/m365/graph_connector_disconnected_test.go
  src/internal/m365/helper_test.go
  src/internal/m365/mock/collection.go
  src/internal/m365/onedrive/item_collector.go
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive/stub/stub.go
  src/internal/m365/onedrive_test.go
  src/internal/m365/sharepoint/api/pages.go
  src/internal/m365/sharepoint/collection.go
  src/internal/m365/sharepoint/collection_test.go
  src/internal/m365/sharepoint/list_info.go
  src/internal/m365/sharepoint/list_info_test.go
  src/internal/m365/sharepoint/lists.go
  src/internal/m365/sharepoint/lists_test.go
  src/internal/m365/sharepoint/pages.go
  src/internal/m365/sharepoint/pages_test.go
  src/internal/m365/sharepoint/restore.go
  src/internal/m365/stub/stub.go
Labels: mergequeue, tech-debt

#3615 Rename some test helpers
  src/internal/kopia/base_finder_test.go
Labels: mergequeue, tests, tech-debt, kopia

#3617 Minor fixups for base finding
  src/internal/kopia/base_finder_test.go
Labels: bug, mergequeue, tests, kopia

#3618 Mark snapshots missing backup as assist bases
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
Labels: bug, mergequeue, backup, perf, kopia

#3578 fetch repoID from kopia is not found in config
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
  src/internal/events/events.go
  src/pkg/repository/repository.go
Labels: telemetry

#3593 Add more tests for url cache
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/url_cache.go
  src/internal/m365/onedrive/url_cache_test.go
Labels: mergequeue, tests

#3613 add default restore config normalizer
  src/cmd/factory/impl/common.go
  src/internal/m365/controller_test.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/exchange/restore_test.go
  src/internal/m365/onedrive/item_test.go
  src/internal/m365/onedrive/url_cache_test.go
  src/internal/m365/sharepoint/api/pages_test.go
  src/internal/m365/sharepoint/collection_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/pkg/control/options.go
  src/pkg/control/options_test.go
  src/pkg/control/testdata/testdata.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository_test.go
Labels: enhancement, mergequeue

#3624 quick logging fixes
  src/internal/m365/exchange/mock/mail.go
  src/internal/m365/exchange/restore.go
  src/pkg/services/m365/api/serialization.go
Labels: mergequeue, tech-debt

#3626 Add note about skipping attachment fetch errors
  src/pkg/services/m365/api/mail.go
Labels: mergequeue

#3623 cascade restoreCfg collision policy into onedrive
  src/internal/m365/exchange/mock/collections.go
  src/internal/m365/graph/errors.go
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/item_test.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/mock/item.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/onedrive/url_cache_test.go
  src/internal/m365/restore.go
  src/internal/m365/sharepoint/library_handler.go
  src/internal/m365/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_test.go
Labels: enhancement, mergequeue, onedrive, msgraph

#3627 separate pager and plain apis for exchange
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager.go
Labels: mergequeue, tech-debt, exchange, msgraph

#3631 Increase S3 TLS Handshake Timeout
  src/go.mod
  src/go.sum
  src/internal/kopia/s3.go
Labels: mergequeue

#3589 Handle event exceptions in caledar
  CHANGELOG.md
  src/cmd/factory/impl/exchange.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/mock/event.go
  src/internal/m365/exchange/restore_test.go
  src/internal/m365/exchange/transform.go
  src/internal/m365/exchange/transform_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/events.go
  website/docs/support/known-issues.md
Labels: mergequeue

#3542 Integrate URL cache into onedrive backup flows
  src/internal/m365/onedrive/collection.go
  src/internal/m365/onedrive/collection_test.go
  src/internal/m365/onedrive/collections.go
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/item.go
  src/internal/m365/onedrive/url_cache.go
  src/internal/m365/onedrive/url_cache_test.go
Labels: enhancement, mergequeue, onedrive

#3634 Fix uploading large attachments for exchange
  CHANGELOG.md
  src/internal/m365/exchange/attachment.go
  src/internal/m365/graph/uploadsession.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
Labels: bug, mergequeue

#3628 add generic item enumeratiton iface to api
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: enhancement, restore, mergequeue, exchange

#3649 Refresh URL cache using previous delta token
  src/internal/m365/onedrive/collections.go
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/url_cache.go
  src/internal/m365/onedrive/url_cache_test.go
Labels: mergequeue, onedrive, msgraph

#3629 add per-container item collision enumeration
  src/internal/m365/onedrive/mock/handlers.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mail_pager_test.go
Labels: restore, mergequeue, exchange, msgraph

#3630 increase page size for all exchange pagers
  src/internal/m365/exchange/backup_test.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/mail_pager.go
Labels: bug, mergequeue, exchange, msgraph

#3637 move default rate limit to per-second
  src/internal/m365/graph/concurrency_middleware.go
Labels: mergequeue, tech-debt, msgraph

#3660 exclude flaky integration test assertions
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests

#3635 handle restore collisions in exchange
  src/internal/m365/exchange/attachment.go
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/handlers.go
  src/internal/m365/exchange/helper_test.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
  src/internal/m365/exchange/restore.go
  src/internal/m365/exchange/restore_test.go
  src/pkg/services/m365/api/events.go
Labels: enhancement, restore, mergequeue, exchange

#3662 Allow getting kopia logs into the corso log
  src/pkg/logger/logger.go
Labels: enhancement, mergequeue, supportability, kopia

#3669 Fix up changelog merge issues
  CHANGELOG.md
Labels: mergequeue

#3676 Skip flaky test case for calendar exceptions
  src/internal/m365/exchange/restore_test.go
Labels: bug, mergequeue-priority, tests

#3667 Add more subtests to aid in debugging
  src/internal/operations/backup_integration_test.go
Labels: bug, mergequeue, tests, supportability

#3673 handle no sharepoint license err
  CHANGELOG.md
  src/internal/m365/discovery/discovery.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: bug, mergequeue-priority, onedrive, sharepoint, msgraph

#3665 combine cli utils, options; separate flags
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/cli.go
  src/cli/flags/exchange.go
  src/cli/flags/flags.go
  src/cli/flags/m365_common.go
  src/cli/flags/m365_resource.go
  src/cli/flags/maintenance.go
  src/cli/flags/onedrive.go
  src/cli/flags/options.go
  src/cli/flags/repo.go
  src/cli/flags/sharepoint.go
  src/cli/options/options_test.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_e2e_test.go
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/exchange.go
  src/cli/utils/exchange_test.go
  src/cli/utils/flags.go
  src/cli/utils/onedrive.go
  src/cli/utils/options.go
  src/cli/utils/options_test.go
  src/cli/utils/sharepoint.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/cli/utils/utils.go
Labels: mergequeue, cli, tech-debt

#3680 Update CHANGELOG.md for v0.10.0
  CHANGELOG.md
Labels: mergequeue

#3657 Allow opening S3 repo at a specific point-in-time
  src/internal/kopia/conn.go
  src/internal/kopia/s3.go
  src/pkg/control/repository/repo.go
Labels: enhancement, mergequeue, kopia

#3636 properly handle collision replace behavior
  src/internal/m365/exchange/contacts_restore.go
  src/internal/m365/exchange/contacts_restore_test.go
  src/internal/m365/exchange/events_restore.go
  src/internal/m365/exchange/events_restore_test.go
  src/internal/m365/exchange/handlers.go
  src/internal/m365/exchange/mail_restore.go
  src/internal/m365/exchange/mail_restore_test.go
Labels: enhancement, restore, mergequeue, exchange

#3674 improve filter func comments
  src/pkg/filters/filters.go
Labels: mergequeue, tech-debt

#3682 Fix changelog commits link
  CHANGELOG.md
Labels: mergequeue

#3638 minor refactoring before changes
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_collector.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/item_test.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/url_cache.go
  src/internal/m365/onedrive/url_cache_test.go
  src/internal/m365/sharepoint/library_handler.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_pager.go
  src/pkg/services/m365/api/mail_pager_test.go
Labels: mergequeue, onedrive, tech-debt, msgraph

#3661 adds test coverage for events in exchange incrementals
  src/internal/m365/exchange/mock/event.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tests, exchange

#3685 Add lint rule to use any instead of interface{}
  src/.golangci.yml
  src/internal/m365/graph/metadata/metadata_test.go
  src/internal/m365/onedrive/collections_test.go
  src/internal/m365/onedrive/item_test.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/sharepoint/mock/list.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail_test.go
Labels: mergequeue, supportability, tech-debt

#3689 make tests less sus
  src/internal/m365/graph/errors_test.go
Labels: mergequeue, tests

#3690 use errors.As to extract odataError
  src/internal/m365/graph/errors.go
Labels: bug, mergequeue

#3639 add the non-delta item pager to drives
  src/pkg/services/m365/api/contacts_pager_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_pager_test.go
  src/pkg/services/m365/api/events_pager_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_pager_test.go
Labels: enhancement, mergequeue, onedrive, msgraph

#3699 fix bad user info conditional on spo license
  src/internal/m365/backup.go
  src/internal/m365/discovery/discovery.go
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
Labels: bug, mergequeue, msgraph

#3686 Minor refactoring of graph error checking code
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/m365.go
Labels: mergequeue, tech-debt

#3705 return mail content size as restore size
  src/internal/m365/exchange/mail_restore.go
Labels: bug, restore, mergequeue, exchange

#3702 give ci tests 20 minutes before timeout
  .github/workflows/ci.yml
Labels: mergequeue, tests

#3590 add flags for azure and aws
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/cli.go
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
  src/cli/flags/m365_resource.go
  src/cli/flags/repo.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/exchange_test.go
  src/cli/restore/onedrive.go
  src/cli/restore/onedrive_test.go
  src/cli/restore/sharepoint.go
  src/cli/restore/sharepoint_test.go
  src/cli/utils/flags_test.go
  src/cli/utils/testdata/flags.go
  src/cli/utils/utils.go
  src/go.sum
  src/internal/kopia/s3.go
  src/internal/tester/storage.go
  src/pkg/credentials/aws.go
  src/pkg/credentials/corso.go
  src/pkg/credentials/m365.go
  src/pkg/storage/s3.go
  src/pkg/storage/s3_test.go
Labels: mergequeue

#3723 skip events in integration backup operations test
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/events_test.go
Labels: bug, tests, exchange

#3719 remove top query param in paged queries
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/contacts_pager.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events_pager.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/mail_pager.go
Labels: bug, mergequeue-priority, msgraph

#3724 Temporarily disable sharepoint permissions tests
  src/internal/m365/onedrive_test.go
Labels: mergequeue

#3698 Follow up to handling link shares
  CHANGELOG.md
  src/internal/m365/onedrive/item.go
  src/internal/m365/onedrive/metadata/permissions.go
  src/internal/m365/onedrive/metadata/permissions_test.go
  src/internal/m365/onedrive/permission.go
  src/internal/m365/onedrive/stub/stub.go
  src/internal/m365/onedrive_test.go
  website/docs/support/known-issues.md
Labels: onedrive, sharepoint

#3710 Correct default value for s3 endpoint
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/cli.go
  src/cli/config/storage.go
  src/cli/repo/repo.go
  src/cli/repo/s3.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
Labels: mergequeue

#3640 od: add per-container collision caching and checks
  src/internal/m365/onedrive/handlers.go
  src/internal/m365/onedrive/item_handler.go
  src/internal/m365/onedrive/mock/handlers.go
  src/internal/m365/onedrive/mock/item.go
  src/internal/m365/onedrive/restore.go
  src/internal/m365/onedrive/restore_test.go
  src/internal/m365/sharepoint/library_handler.go
Labels: enhancement, restore, mergequeue, onedrive

#3692 clues version bump
  src/go.mod
  src/go.sum
  src/pkg/services/m365/api/users.go
Labels: mergequeue, dependencies

#3726 don't match config in init repo
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
Labels: mergequeue

#3731 Revert "don't match config in init repo (#3726)"
  src/cli/config/account.go
  src/cli/config/config.go
  src/cli/config/config_test.go
  src/cli/config/storage.go
Labels: bug, mergequeue-priority

#3728 properly declare resourceNotFound for sites
  src/internal/m365/graph/errors.go
  src/internal/m365/graph/errors_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
Labels: bug, mergequeue, sharepoint, msgraph

#3721 add logging indicating full backups
  src/internal/m365/exchange/backup.go
  src/internal/m365/onedrive/collections.go
  src/internal/operations/backup.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, supportability

#3715 fix concurrency limiter init race
  src/cli/backup/backup.go
  src/cli/backup/exchange.go
  src/cli/backup/onedrive.go
  src/cli/backup/sharepoint.go
  src/cli/repo/repo.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/utils.go
  src/cmd/factory/impl/common.go
  src/cmd/factory/impl/exchange.go
  src/cmd/factory/impl/onedrive.go
  src/cmd/factory/impl/sharepoint.go
  src/internal/m365/backup_test.go
  src/internal/m365/controller.go
  src/internal/m365/controller_test.go
  src/internal/m365/discovery/discovery_test.go
  src/internal/m365/exchange/backup.go
  src/internal/m365/exchange/backup_test.go
  src/internal/m365/graph/betasdk/beta_client_test.go
  src/internal/m365/graph/concurrency_middleware.go
  src/internal/m365/graph/concurrency_middleware_test.go
  src/internal/m365/graph/service.go
  src/internal/m365/helper_test.go
  src/internal/m365/onedrive/item_collector_test.go
  src/internal/m365/onedrive_test.go
  src/internal/m365/sharepoint/api/pages_test.go
  src/internal/m365/sharepoint/backup_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/help_test.go
  src/internal/operations/restore_test.go
  src/pkg/repository/repository.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/helper_test.go
  src/pkg/services/m365/m365_test.go
Labels: bug, mergequeue-priority, cli, msgraph
