Repository alcionai/corso, pull requests merged in 2023-05, with the labels that each got.

#3270 Fallback to RepoRef is LocationRef is empty
  CHANGELOG.md
  src/pkg/selectors/exchange.go
Labels: bug, restore, mergequeue, exchange

#3265 rename DetailsEntry to Entry to avoid stuttering
  src/cli/utils/testdata/opts.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/selectors/example_selectors_test.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/scopes.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, tech-debt

#3274 Remove Unit-Test dependency in release job
  .github/workflows/ci.yml
Labels: mergequeue

#3275 retry on read IO error message
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/http_wrapper.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/service.go
Labels: msgraph

#3224 Create wrapper around kopia maintenance
  src/go.mod
  src/go.sum
  src/internal/kopia/conn.go
  src/internal/kopia/conn_test.go
  src/internal/kopia/model_store_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/streamstore/collectables_test.go
  src/pkg/control/options.go
  src/pkg/control/repository/maintenancesafety_string.go
  src/pkg/control/repository/maintenancetype_string.go
  src/pkg/control/repository/repo.go
  src/pkg/repository/repository_unexported_test.go
Labels: enhancement, mergequeue, supportability, kopia

#3279 Update CHANGELOG.md for new release v0.7.0
  CHANGELOG.md
Labels: mergequeue

#3204 add sharepoint to sanity tests
  .github/workflows/sanity-test.yaml
  src/cmd/sanity_test/sanity_tests.go
  src/internal/tester/resource_owners.go
Labels: restore, mergequeue, backup, sharepoint

#3271 retry on gateway timeout
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/http_wrapper.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/middleware_test.go
  src/internal/connector/graph/service.go
Labels: mergequeue, msgraph

#3225 Create basic maintenance operation
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/maintenance.go
  src/internal/operations/maintenance_test.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: enhancement, mergequeue, supportability, kopia

#3215 move and rename common/time.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/cli/utils/exchange_test.go
  src/cli/utils/flags.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/cmd/factory/impl/common.go
  src/cmd/purge/purge.go
  src/cmd/sanity_test/sanity_tests.go
  src/internal/common/dttm/dttm.go
  src/internal/common/dttm/dttm_test.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/events_test.go
  src/internal/connector/exchange/mock/event.go
  src/internal/connector/exchange/mock/mail.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
  src/internal/tester/cli.go
  src/internal/tester/restore_destination.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
  src/pkg/control/options.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/selectors_reduce_test.go
  src/pkg/selectors/sharepoint.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, tech-debt

#3282 Add periodic log message for loading items during restore
  src/internal/kopia/wrapper.go
Labels: mergequeue, supportability, kopia

#3290 Small typo fix in a log message
  src/internal/connector/onedrive/item.go
Labels: mergequeue

#3292 protect retryRequset from segfaults
  src/internal/connector/graph/middleware.go
Labels: bug, mergequeue-priority, msgraph

#3216 move permissions into metadata
  src/cmd/factory/impl/common.go
  src/internal/connector/graph/metadata/metadata.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/metadata/metadata.go
  src/internal/connector/onedrive/metadata/permissions.go
  src/internal/connector/onedrive/metadata/permissions_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/permission_test.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, tech-debt, sharepoint

#3235 move onedrive.MetadataItem to metadata.Item
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/metadata/metadata.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/permission_test.go
  src/internal/connector/onedrive/restore.go
  src/pkg/backup/details/details.go
  src/pkg/path/drive.go
  src/pkg/path/drive_test.go
Labels: mergequeue, onedrive, tech-debt, sharepoint

#3296 additional middleware segfault protection
  src/internal/connector/graph/middleware.go
Labels: bug, mergequeue-priority, msgraph

#3300 Temporary solution to duplicate Exchange folders
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
Labels: bug, mergequeue, backup, exchange

#3245 Add workflow to manually publish image via CI
  .github/actions/publish-binary/action.yml
  .github/workflows/binary-publish.yml
  .github/workflows/ci.yml
Labels: mergequeue

#3309 Correct help for exchange backup details
  src/cli/backup/exchange.go
Labels: mergequeue

#3307 Fix NPE in SharePoint incremental backup
  CHANGELOG.md
  src/pkg/backup/details/details.go
  src/pkg/backup/details/details_test.go
Labels: bug, mergequeue, backup, sharepoint

#3280 reset body reader on corso retry handling
  CHANGELOG.md
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/middleware_test.go
Labels: bug, mergequeue-priority, msgraph

#3258 consolidate aggregation of parent-item exclude map
  src/internal/common/prefixmatcher/mock/mock.go
  src/internal/common/prefixmatcher/prefix_matcher.go
  src/internal/common/prefixmatcher/prefix_matcher_test.go
  src/internal/common/prefixmatcher/string_set_matcher.go
  src/internal/common/prefixmatcher/string_set_matcher_test.go
  src/internal/connector/data_collections.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/mock/connector.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/kopia/merge_details.go
  src/internal/kopia/upload.go
  src/internal/kopia/upload_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue, backup, onedrive, tech-debt, sharepoint

#3294 Smarter item load ordering during ProduceRestoreCollections
  CHANGELOG.md
  src/internal/kopia/data_collection.go
  src/internal/kopia/data_collection_test.go
  src/internal/kopia/wrapper.go
Labels: restore, mergequeue, perf, kopia

#3288 common job to choose m365 account
  .github/workflows/accSelector.yaml
Labels: mergequeue

#3287 Choose test Account using round robin
  .github/workflows/accSelector.yaml
  .github/workflows/ci.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3329 Explicitly mention it is id of email and not email id for --email
  src/cli/utils/exchange.go
  website/docs/quickstart.md
Labels: mergequeue

#3318 Fetch calendar by name on 409 ErrorFolderExist
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/errors.go
  src/internal/connector/graph/errors_test.go
Labels: bug, mergequeue-priority, mergequeue, msgraph

#3316 remove cli support for exchange item msoft id lookup
  CHANGELOG.md
  src/cli/utils/testdata/opts.go
  src/pkg/selectors/exchange.go
  src/pkg/selectors/exchange_test.go
Labels: mergequeue, cli, tech-debt, exchange

#3308 Return map instead of using in-out param
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
Labels: mergequeue, backup, tech-debt, exchange

#3339 disguise user's default drive as enum
  CHANGELOG.md
  src/internal/connector/onedrive/api/drive.go
Labels: bug, mergequeue-priority, backup, onedrive

#3361 Handle special case OD site name after recreating user
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue

#3350 handle large item client redirects
  CHANGELOG.md
  src/internal/connector/graph/http_wrapper.go
  src/internal/connector/graph/http_wrapper_test.go
  src/internal/connector/graph/service.go
Labels: bug, mergequeue-priority, msgraph

#3367 run cli e2e on the nightly schedule, not CI
  .github/workflows/load_test.yml
  .github/workflows/nightly_test.yml
  src/cli/backup/exchange_e2e_test.go
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
  src/cli/repo/s3_e2e_test.go
  src/cli/restore/exchange_e2e_test.go
Labels: mergequeue-priority, tests

#3284 Allow specifying a role to assume when initializing a storage provider
  src/go.mod
  src/go.sum
  src/internal/kopia/s3.go
  src/internal/tester/config.go
  src/pkg/repository/repository_test.go
  src/pkg/storage/storage.go
Labels: mergequeue

#3357 introduce per-service rate limiter configurations
  src/internal/connector/data_collections.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/middleware_test.go
Labels: enhancement, mergequeue, msgraph

#3359 Lint GitHub actions changes
  .github/workflows/_filechange_checker.yml
  .github/workflows/actions-lint.yml
  .github/workflows/nightly_test.yml
  .github/workflows/website-publish.yml
Labels: mergequeue, workflows, supportability

#3337 Update kopia restore logic to take a (RepoRef, Collection Restore Path) pair
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/restore_test.go
  src/internal/kopia/merge_collection.go
  src/internal/kopia/merge_collection_test.go
  src/internal/kopia/wrapper.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/operations/inject/inject.go
  src/internal/operations/manifests.go
  src/internal/operations/restore.go
  src/internal/streamstore/streamstore.go
  src/pkg/path/path.go
Labels: enhancement, restore, mergequeue

#3366 Add option to manually trigger CI cleanup workflow
  .github/workflows/ci_test_cleanup.yml
Labels: mergequeue

#3291 Item size- sum of attachment and email body
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/mail_test.go
  src/internal/connector/exchange/exchange_data_collection.go
  src/internal/connector/exchange/service_restore.go
Labels: mergequeue, exchange, msgraph

#3376 fix the unbounded var sanity test site flags
  .github/workflows/sanity-test.yaml
Labels: mergequeue-priority, tests

#3377 Fix incorrect jq parsing for sanity tests for SharePoint
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3312 add indeets to drive-based tests
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/operations/backup_integration_test.go
  src/pkg/backup/details/testdata/in_deets.go
  src/pkg/backup/details/testdata/in_deets_test.go
Labels: onedrive, tests, sharepoint

#3314 build golden references for expectedDeets
  src/internal/operations/backup_integration_test.go
Labels: onedrive, tests, exchange, sharepoint

#3363 normalize folders restored in testing
  .github/workflows/sanity-test.yaml
  src/cli/backup/onedrive_e2e_test.go
  src/internal/connector/data_collections_test.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/graph_connector_disconnected_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/internal/tester/restore_destination.go
  src/pkg/repository/loadtest/repository_load_test.go
  src/pkg/repository/repository_test.go
  src/pkg/selectors/testdata/onedrive.go
Labels: mergequeue-priority, mergequeue, tests

#3378 fix up per-service token constraints
  src/internal/connector/graph/http_wrapper_test.go
  src/internal/connector/graph/middleware.go
  src/internal/events/events.go
Labels: bug, mergequeue-priority, msgraph

#3348 some quick logging and error naming updates
  src/cli/backup/backup.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/service.go
  src/internal/operations/backup.go
Labels: mergequeue, tech-debt, msgraph

#3295 add indeets test helper, implement in exchange op
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/operations/backup_integration_test.go
  src/pkg/backup/details/testdata/in_deets.go
  src/pkg/backup/details/testdata/in_deets_test.go
  src/pkg/path/path.go
Labels: mergequeue, backup, tests

#3362 Add restore path generation code
  src/internal/operations/pathtransformer/restore_path_transformer.go
  src/internal/operations/pathtransformer/restore_path_transformer_test.go
  src/internal/operations/restore.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/drive.go
  src/pkg/path/drive_test.go
  src/pkg/selectors/selectors_reduce_test.go
Labels: bug, enhancement, restore, mergequeue, exchange

#3381 add drive-level tombstone for deleted drives
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/pkg/path/drive_test.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/sharepoint_test.go
Labels: bug, mergequeue, backup, onedrive, sharepoint

#3375 Combine collection structs
  src/internal/connector/graph/collections.go
Labels: mergequeue, backup, tech-debt

#3369 release the sensitive-info flag
  CHANGELOG.md
  src/pkg/logger/logger.go
  src/pkg/logger/logger_test.go
  website/docs/setup/configuration.md
  website/styles/Vocab/Base/accept.txt
Labels: documentation, mergequeue, cli, supportability

#3328 treat / as root for restore of onedrive and sharepoint
  src/cli/utils/flags.go
  src/cli/utils/onedrive_test.go
  src/cli/utils/sharepoint_test.go
  src/cli/utils/testdata/opts.go
Labels: bug, mergequeue, cli

#3393 add nil pointer guard to resp.Headers in middleware
  src/internal/connector/graph/middleware.go
Labels: bug, mergequeue-priority, msgraph

#3380 More workflow linting changes
  .github/workflows/_filechange_checker.yml
  .github/workflows/actions-lint.yml
Labels: bug, mergequeue, workflows, supportability

#3358 refine rate limiter: per-query token consumption
  CHANGELOG.md
  src/internal/connector/graph/concurrency_limiter.go
  src/internal/connector/graph/concurrency_middleware.go
  src/internal/connector/graph/concurrency_middleware_test.go
  src/internal/connector/graph/http_wrapper.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/graph/middleware_test.go
  src/internal/connector/graph/service.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/sharepoint/restore.go
Labels: enhancement, mergequeue, msgraph

#3391 Re-add GitHub Actions linting
  .github/workflows/ci.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue-priority, mergequeue, workflows, supportability

#3394 make the linter happy
  src/internal/operations/pathtransformer/restore_path_transformer.go
Labels: mergequeue, tech-debt

#3385 consts for drives, root:
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/consts/consts.go
  src/internal/connector/onedrive/drive.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/pkg/backup/details/details_test.go
  src/pkg/path/drive_test.go
  src/pkg/selectors/onedrive_test.go
  src/pkg/selectors/sharepoint_test.go
Labels: mergequeue, onedrive, tech-debt

#3373 Switch to folder IDs in Exchange
  CHANGELOG.md
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/operations/backup_integration_test.go
Labels: mergequeue, backup, exchange

#3384 minor updates to the path.Path interface
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/restore.go
  src/internal/kopia/upload.go
  src/internal/kopia/wrapper_test.go
  src/internal/operations/manifests_test.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/path/elements.go
  src/pkg/path/path.go
  src/pkg/path/path_test.go
  src/pkg/path/resource_path.go
  src/pkg/path/resource_path_test.go
Labels: mergequeue, tech-debt

#3390 add known issue about deleted library restore
  CHANGELOG.md
  website/docs/support/known-issues.md
Labels: documentation, mergequeue

#3406 Remove all uses of CORSO_URL_LOGGING
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
Labels: mergequeue

#3353 Fix json tag for modified time in sharepoint info
  src/pkg/backup/details/details.go
Labels: mergequeue

#3400 insert restoreEnd event into deferred func
  src/internal/operations/backup.go
  src/internal/operations/restore.go
  src/internal/operations/restore_test.go
Labels: bug, mergequeue, supportability

#3401 logger settings cleanup
  src/cmd/factory/factory.go
  src/cmd/getM365/main.go
  src/cmd/purge/purge.go
  src/internal/kopia/wrapper_test.go
  src/internal/tester/cli.go
  src/pkg/logger/logger.go
  src/pkg/logger/logger_test.go
Labels: supportability

#3330 renaming/cleanup for sharepoint perms pt.1
  src/cli/restore/onedrive.go
  src/internal/connector/graph/middleware.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/service_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore.go
Labels: mergequeue, onedrive, tech-debt, sharepoint

#3383 add repoRef pii transformer
  src/internal/connector/graph/middleware.go
  src/pkg/path/elements.go
  src/pkg/path/elements_test.go
Labels: mergequeue, supportability, tech-debt

#3311 extend userPermissions handling
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
Labels: onedrive, sharepoint

#3412 Cleanup and simplify sanity tests
  .github/actions/backup-restore-test/action.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3398 separate log level and format config
  src/cmd/factory/factory.go
  src/cmd/getM365/main.go
  src/cmd/purge/purge.go
  src/internal/kopia/wrapper_test.go
  src/internal/tester/cli.go
  src/pkg/logger/logger.go
  src/pkg/logger/logger_test.go
Labels: mergequeue, supportability

#3396 adds strictEquals filter
  src/pkg/filters/filters.go
  src/pkg/filters/filters_test.go
Labels: enhancement

#3414 Don't display folders in restore output
  CHANGELOG.md
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/pkg/backup/details/details.go
Labels: bug, restore, mergequeue, cli

#3418 update release changelog
  CHANGELOG.md
Labels: documentation, mergequeue

#3413 Don't repeat initialization steps for sanity-test composite action
  .github/actions/backup-restore-test/action.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue

#3409 Ensure response body gets closed
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/graph/concurrency_middleware_test.go
  src/internal/connector/graph/http_wrapper_test.go
Labels: mergequeue

#3411 Convert PageLinker to DeltaPageLinker for NonDelta pagers
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/api/shared.go
  src/internal/connector/exchange/api/shared_test.go
  src/internal/connector/graph/api/api.go
Labels: mergequeue

#3415 add namespace to fault items
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/streamstore/collectables_test.go
  src/pkg/fault/example_fault_test.go
  src/pkg/fault/fault.go
  src/pkg/fault/fault_test.go
  src/pkg/fault/item.go
  src/pkg/fault/item_test.go
  src/pkg/fault/testdata/testdata.go
  src/pkg/repository/repository_unexported_test.go
Labels: bug, mergequeue, supportability

#3345 Bump msgraph deps to 1.0.0
  src/cmd/factory/impl/common.go
  src/cmd/sanity_test/sanity_tests.go
  src/go.mod
  src/go.sum
  src/internal/connector/exchange/api/contacts.go
  src/internal/connector/exchange/api/events.go
  src/internal/connector/exchange/api/mail.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/mock/mock_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/errors_test.go
  src/internal/connector/graph/middleware_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/api/drive.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/consts/consts.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/list.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/m365Support_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/sites_test.go
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/api/users_test.go
Labels: mergequeue

#3397 case sensitive selection for item IDs
  src/pkg/selectors/exchange.go
  src/pkg/selectors/helpers_test.go
  src/pkg/selectors/onedrive.go
  src/pkg/selectors/scopes_test.go
  src/pkg/selectors/selectors.go
  src/pkg/selectors/sharepoint.go
Labels: bug, enhancement, restore, mergequeue, msgraph

#3419 Only remove previous deltas from metadata under some conditions
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
Labels: mergequeue, backup, onedrive, sharepoint

#3427 Add telemetry information for maintenance operations
  src/internal/events/events.go
  src/internal/operations/maintenance.go
Labels: enhancement, telemetry, maintenance

#3355 use graph client for large data set
  src/internal/connector/exchange/attachment.go
  src/internal/connector/graph/uploadsession.go
  src/internal/connector/graph/uploadsession_test.go
  src/internal/connector/onedrive/item.go
Labels: mergequeue, reliability

#3420 Place concurrency limiter middleware after retry middlewares
  src/internal/connector/graph/service.go
Labels: mergequeue, msgraph

#3226 Create CLI command for maintenance
  src/cli/repo/repo.go
  src/cli/repo/repo_test.go
  src/cli/utils/flags.go
  src/internal/events/events.go
  src/internal/operations/maintenance.go
  src/pkg/control/repository/repo.go
Labels: enhancement, mergequeue, maintenance

#3417 migrate drive api to pkg/services/m365
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/mock/drive.go
Labels: tech-debt, msgraph

#3416 migrate exchange api to pkg/services/m365
  src/cmd/getM365/exchange/get_item.go
  src/cmd/getM365/onedrive/get_item.go
  src/internal/connector/exchange/api/api.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/folder_resolver_test.go
  src/internal/connector/exchange/mail_folder_cache_test.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_functions.go
  src/internal/connector/exchange/service_iterators.go
  src/internal/connector/exchange/service_iterators_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/restore_test.go
  src/pkg/services/m365/api/api.go
  src/pkg/services/m365/api/api_test.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_test.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/exchange_common.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/mock/drive.go
  src/pkg/services/m365/api/mock/mail.go
  src/pkg/services/m365/api/options.go
  src/pkg/services/m365/api/shared.go
  src/pkg/services/m365/api/shared_test.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, tech-debt, msgraph

#3433 purge sanity tests after run
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests, reliability

#3435 Remove 503, 504 retries from corso retry handler
  src/internal/connector/graph/middleware.go
Labels: mergequeue, msgraph

#3434 check ci.yml logging artifacts
  .github/workflows/ci.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue-priority, tests, supportability

#3446 quick logging middleware cleanup
  src/internal/connector/graph/middleware.go
Labels: mergequeue, tech-debt, msgraph

#3442 Sanity test yml refs
  .github/actions/backup-restore-test/action.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests

#3428 refactor api options
  src/cli/config/account.go
  src/cli/config/storage.go
  src/cmd/factory/impl/common.go
  src/cmd/getM365/exchange/get_item.go
  src/cmd/getM365/onedrive/get_item.go
  src/cmd/purge/purge.go
  src/internal/common/slices.go
  src/internal/common/slices_test.go
  src/internal/common/str/str.go
  src/internal/common/strings.go
  src/internal/common/tform/tform.go
  src/internal/connector/graph/cache_container.go
  src/pkg/logger/logger.go
  src/pkg/services/m365/api/attachments.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/client_test.go
  src/pkg/services/m365/api/consts.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/delta.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/options.go
  src/pkg/services/m365/api/query_params.go
  src/pkg/services/m365/api/users.go
  src/pkg/storage/s3.go
Labels: mergequeue, tech-debt, msgraph

#3447 Adding two new apis to corso for validating a user has exchange or one drive is enabled
  src/pkg/services/m365/m365.go
  src/pkg/services/m365/m365_test.go
Labels: enhancement, mergequeue, msgraph

#3464 More robust folder fetching for container cache
  CHANGELOG.md
  src/internal/connector/exchange/contact_folder_cache.go
  src/internal/connector/exchange/container_resolver.go
  src/internal/connector/exchange/container_resolver_test.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/event_calendar_cache.go
  src/internal/connector/exchange/mail_folder_cache.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
Labels: bug, restore, mergequeue-priority, backup, exchange

#3454 Add tests for older versions of backup details data
  src/cli/backup/exchange_test.go
  src/cli/backup/onedrive_test.go
  src/cli/backup/sharepoint_test.go
  src/cli/utils/testdata/opts.go
  src/pkg/backup/details/testdata/testdata.go
  src/pkg/selectors/selectors_reduce_test.go
Labels: restore, mergequeue, tests

#3449 get repoID from config for events
  src/cli/repo/s3.go
  src/cli/utils/utils.go
  src/internal/events/events.go
  src/pkg/repository/repository.go
  src/pkg/repository/repository_test.go
Labels: bug, mergequeue, telemetry

#3468 add kiota retry to http_wrapper
  src/internal/connector/graph/http_wrapper.go
Labels: bug, mergequeue-priority, msgraph

#3465 Remove older tests prior to expanded cache
  src/internal/connector/exchange/container_resolver_test.go
Labels: mergequeue, tests, supportability, exchange

#3469 Should not error out on "My site not found"
  src/pkg/services/m365/m365.go
Labels: mergequeue

#3461 follow-up refinements to m365/api
  src/internal/common/str/str.go
  src/internal/common/tform/tform.go
  src/internal/connector/graph/api/api.go
  src/internal/connector/graph/api/api_test.go
  src/internal/connector/graph/cache_container.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/sharepoint/api/api.go
  src/internal/connector/sharepoint/api/beta_service.go
  src/internal/connector/sharepoint/api/beta_service_test.go
  src/internal/connector/sharepoint/api/helper_test.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/pages_test.go
  src/internal/connector/sharepoint/collection.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/restore.go
  src/pkg/services/m365/api/config.go
  src/pkg/services/m365/api/consts.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/item_pager.go
  src/pkg/services/m365/api/item_pager_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mock/drive_pager.go
  src/pkg/services/m365/api/query_params.go
  src/pkg/services/m365/api/sites.go
  src/pkg/services/m365/api/users.go
Labels: mergequeue, tech-debt

#3452 move ad-hoc exchange graph calls to api, first pass
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
Labels: tech-debt, exchange, msgraph

#3476 Use a fork of kiota-serialization-json-go to revert use of bufferpools
  CHANGELOG.md
  src/go.mod
  src/go.sum
Labels: mergequeue

#3481 add ownerName to backup list json
  CHANGELOG.md
  src/pkg/backup/backup.go
Labels: enhancement, mergequeue-priority, backup, cli

#3479 Try to catch concurrent serialization issues
  src/pkg/services/m365/api/item_serialization_test.go
Labels: bug, mergequeue, tests, exchange

#3473 fix has drive and has mailbox conditions
  src/pkg/services/m365/api/users.go
  src/pkg/services/m365/m365.go
Labels: bug, mergequeue, msgraph

#3474 add slack failure messages to nightly
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
Labels: mergequeue, tests, supportability

#3483 Only select a test file if it's not empty
  src/internal/connector/onedrive/item_test.go
Labels: mergequeue, tests

#3470 check for log file location in artifacts
  .github/workflows/ci.yml
  .github/workflows/load_test.yml
  .github/workflows/nightly_test.yml
  .github/workflows/sanity-test.yaml
  src/cli/cli.go
  src/internal/connector/exchange/restore_test.go
  src/internal/tester/cli.go
  src/internal/tester/context.go
  src/pkg/logger/logger.go
  src/pkg/logger/logger_test.go
Labels: bug, mergequeue-priority, tests, supportability

#3486 update sanity test log files
  .github/actions/backup-restore-test/action.yml
  .github/workflows/sanity-test.yaml
Labels: bug, mergequeue

#3489 Docs: Update known issues
  website/docs/support/known-issues.md
Labels: mergequeue

#3494 Fix TestExchangeBackupListCmd_empty now that we print log file name
  src/cli/backup/exchange_e2e_test.go
Labels: mergequeue

#3493 Fix folders used for sanity-tests
  .github/workflows/load_test.yml
  .github/workflows/sanity-test.yaml
  .gitignore
  src/Makefile
Labels: mergequeue-priority

#3496 Remove a stray print statement
  src/internal/connector/onedrive/permission.go
Labels: mergequeue

#3451 move ad-hoc drive api calls into m365/api
  src/cmd/purge/purge.go
  src/internal/connector/data_collections.go
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attachment_uploadable.go
  src/internal/connector/exchange/restore_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/graph/consts.go
  src/internal/connector/graph/middleware_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/sharepoint/queries.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/attachments.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/drive.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
Labels: mergequeue, tech-debt, msgraph

#3497 update logging standards doc
  src/pkg/logger/example_logger_test.go
Labels: documentation, mergequeue

#3455 cleanup exchange api code, move out of support
  src/internal/connector/exchange/attachment.go
  src/internal/connector/exchange/attendees.go
  src/internal/connector/exchange/data_collections.go
  src/internal/connector/exchange/data_collections_test.go
  src/internal/connector/exchange/iterators_test.go
  src/internal/connector/exchange/mock/mock_test.go
  src/internal/connector/exchange/service_restore.go
  src/internal/connector/exchange/transform.go
  src/internal/connector/exchange/transform_test.go
  src/internal/connector/graph_connector_helper_test.go
  src/internal/connector/sharepoint/api/pages.go
  src/internal/connector/sharepoint/api/serialization.go
  src/internal/connector/sharepoint/api/serialization_test.go
  src/internal/connector/sharepoint/collection_test.go
  src/internal/connector/sharepoint/mock/mock_test.go
  src/internal/connector/sharepoint/restore.go
  src/internal/connector/support/m365Support.go
  src/internal/connector/support/m365Support_test.go
  src/internal/operations/backup_integration_test.go
  src/pkg/services/m365/api/client_test.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/contacts_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/events_test.go
  src/pkg/services/m365/api/item_serialization_test.go
  src/pkg/services/m365/api/mail.go
  src/pkg/services/m365/api/mail_test.go
  src/pkg/services/m365/api/serialization.go
Labels: mergequeue, tech-debt, exchange, msgraph

#3514 Reverting hack since the new incarnation of user is back to proper URL
  src/cmd/purge/scripts/onedrivePurge.ps1
Labels: mergequeue-priority

#3504 Fix slack notification for nightly tests
  .github/workflows/nightly_test.yml
Labels: mergequeue

#3513 rename ownerName to protectedResourceName
  CHANGELOG.md
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
Labels: mergequeue, cli, tech-debt

#3511 Switch back to upstream of serialization library
  src/go.mod
  src/go.sum
Labels: mergequeue, supportability, dependencies, tech-debt, msgraph

#3517 Fix more nightly test
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
Labels: mergequeue

#3509 add user info to sharepoint details
  src/internal/connector/onedrive/item.go
  src/pkg/backup/details/details.go
Labels: mergequeue, cli, community-request

#3500 Move some interfaces to kopia package
  src/internal/kopia/inject/inject.go
  src/internal/operations/backup.go
  src/internal/operations/inject/inject.go
  src/internal/operations/manifests.go
  src/internal/streamstore/streamstore.go
Labels: mergequeue

#3502 Add new code for finding bases for incremental backups
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/conn.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/snapshot_manager.go
  src/internal/kopia/snapshot_manager_test.go
  src/internal/operations/inject/inject.go
Labels: mergequeue, backup, kopia

#3426 don't throw error on backup with service disabled
  src/cli/backup/backup.go
  src/cli/backup/exchange_e2e_test.go
  src/internal/connector/data_collections.go
  src/internal/connector/mock/connector.go
  src/internal/operations/backup.go
  src/internal/operations/inject/inject.go
  src/internal/tester/config.go
  src/internal/tester/resource_owners.go
Labels: bug, mergequeue, community-request

#3532 Fix nightly tests
  .github/workflows/nightly_test.yml
  src/cli/backup/onedrive_e2e_test.go
  src/cli/backup/sharepoint_e2e_test.go
Labels: mergequeue

#3495 Do not print all the restored items if there are a lot of them
  CHANGELOG.md
  src/cli/print/print.go
  src/cli/restore/exchange.go
  src/cli/restore/onedrive.go
  src/cli/restore/sharepoint.go
  src/pkg/backup/details/details.go
Labels: restore, mergequeue, cli

#3480 update files count and total size on CLI for backup
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
  src/internal/stats/stats.go
  src/pkg/backup/backup.go
  src/pkg/backup/backup_test.go
  src/pkg/backup/details/details.go
Labels: mergequeue, backup, onedrive, ux, sharepoint

#3487 introduce backup handler
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/consts/consts.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item_backup_handler.go
  src/internal/connector/onedrive/item_backup_handler_test.go
  src/internal/connector/sharepoint/helper_test.go
  src/internal/connector/sharepoint/library_backup_handler.go
  src/internal/connector/sharepoint/library_backup_handler_test.go
  src/pkg/path/path.go
  src/pkg/services/m365/api/drive_item_pager.go
Labels: backup, onedrive, tech-debt, sharepoint

#3488 move api pagers to methods
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/library_backup_handler.go
  src/pkg/services/m365/api/contacts.go
  src/pkg/services/m365/api/drive_pager.go
  src/pkg/services/m365/api/drive_test.go
  src/pkg/services/m365/api/events.go
  src/pkg/services/m365/api/mail.go
Labels: onedrive, tech-debt, exchange, sharepoint, msgraph

#3499 move details hooks into drive handlers
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_backup_handler.go
  src/internal/connector/sharepoint/library_backup_handler.go
  src/pkg/path/drive.go
  src/testlog/test.log
Labels: onedrive, tech-debt, sharepoint, msgraph

#3501 migrate last funcs into backupHandler
  src/cmd/purge/purge.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_backup_handler.go
  src/internal/connector/sharepoint/library_backup_handler.go
  src/internal/operations/backup_test.go
  src/pkg/services/m365/api/client.go
  src/pkg/services/m365/api/drive_item_pager.go
  src/pkg/services/m365/api/drive_pager.go
Labels: onedrive, tech-debt, sharepoint, msgraph

#3524 Wrap new base finder and wire it up
  CHANGELOG.md
  src/internal/kopia/base_finder.go
  src/internal/kopia/base_finder_test.go
  src/internal/kopia/inject/inject.go
  src/internal/kopia/wrapper.go
  src/internal/operations/backup.go
  src/internal/operations/backup_test.go
  src/internal/operations/manifests.go
  src/internal/operations/manifests_test.go
Labels: mergequeue, backup, perf

#3512 establish restore handler interfaces
  src/internal/connector/data_collections.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/drivesource_string.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_handler.go
  src/internal/connector/onedrive/item_handler_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/sharepoint/library_handler.go
  src/internal/connector/sharepoint/library_handler_test.go
  src/internal/connector/sharepoint/restore.go
  src/pkg/services/m365/api/drive.go
Labels: onedrive, tech-debt, sharepoint, msgraph

#3515 getting to green following refactors, pt 1
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_handler.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/mock/handlers.go
  src/internal/connector/onedrive/permission_test.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/library_handler.go
  src/internal/operations/restore_test.go
  src/pkg/services/m365/api/client.go
Labels: onedrive, tech-debt, sharepoint, msgraph

#3516 getting to green following refactors, part 2
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/data_collections.go
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/mock/handlers.go
  src/internal/connector/sharepoint/data_collections.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/library_handler.go
  src/internal/operations/backup_integration_test.go
  src/internal/operations/backup_test.go
Labels: onedrive, tech-debt, sharepoint, msgraph

#3527 getting to green: fixed up unit tests
  src/.gitignore
  src/internal/connector/graph/errors.go
  src/internal/connector/graph_connector_onedrive_test.go
  src/internal/connector/graph_connector_test.go
  src/internal/connector/onedrive/collection.go
  src/internal/connector/onedrive/collection_test.go
  src/internal/connector/onedrive/collections_test.go
  src/internal/connector/onedrive/drive.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/metadata/permissions.go
  src/internal/connector/onedrive/metadata/permissions_test.go
  src/internal/connector/onedrive/metadata/testdata/permissions.go
  src/internal/connector/onedrive/mock/handlers.go
  src/internal/connector/onedrive/mock/item.go
  src/internal/connector/onedrive/testdata/item.go
  src/internal/connector/sharepoint/data_collections_test.go
  src/internal/connector/sharepoint/helper_test.go
Labels: onedrive, tech-debt, sharepoint, msgraph

#3547 Don't try to delete test data in the test
  src/internal/connector/exchange/restore_test.go
Labels: mergequeue, tests, exchange, reliability

#3543 post-rebase fixups
  src/.gitignore
  src/internal/connector/onedrive/drive_test.go
  src/internal/connector/onedrive/handlers.go
  src/internal/connector/onedrive/item.go
  src/internal/connector/onedrive/item_handler.go
  src/internal/connector/onedrive/item_test.go
  src/internal/connector/onedrive/permission.go
  src/internal/connector/onedrive/restore.go
  src/internal/connector/onedrive/url_cache.go
  src/internal/connector/onedrive/url_cache_test.go
  src/internal/connector/sharepoint/library_handler.go
  src/pkg/services/m365/api/drive.go
Labels: bug, onedrive, tests, sharepoint
